"use client";

import { useBom } from "@/hooks/production/useBom";
import BomView from "@/components/production/BomView";

export default function DoorConfigurator() {
  const {
    formRef,
    customerPO,
    setCustomerPO,
    orderQty,
    setOrderQty,
    doorType,
    setDoorType,
    doorThickness,
    setDoorThickness,
    doorWidth,
    setDoorWidth,
    doorHeight,
    setDoorHeight,
    surfaceMaterial,
    setSurfaceMaterial,
    surfacePrice,
    setSurfacePrice,
    surfaceThickness,
    setSurfaceThickness,
    selectedFrameCode,
    setSelectedFrameCode,
    frameCandidates,
    lockBlockPosition,
    setLockBlockPosition,
    lockBlockPiecesPerSide,
    setLockBlockPiecesPerSide,
    doubleFrameSides,
    doubleFrameCount,
    setDoubleFrameCount,
    coreType,
    setCoreType,
    selectedCoreCode,
    setSelectedCoreCode,
    availableCoreItems,
    selectedCoreItem,
    edgeBanding,
    setEdgeBanding,
    edgeMaterial,
    setEdgeMaterial,
    edgePrice,
    setEdgePrice,
    edgeSides,
    setEdgeSides,
    drilling,
    setDrilling,
    drillItems,
    setDrillItems,
    lockBlockLeft,
    lockBlockRight,
    currentFrame,
    results,
    cuttingPlan,
    coreCalculation,
    isDataComplete,
    piecesPerSide,
    doubleConfigSummary,
    handleToggleDoubleSide,
    lockBlockDesc,
    priceSummary,
    customMargin,
    setCustomMargin,
  } = useBom();

  return (
    <BomView
      formRef={formRef}
      customerPO={customerPO}
      setCustomerPO={setCustomerPO}
      orderQty={orderQty}
      setOrderQty={setOrderQty}
      doorType={doorType}
      setDoorType={setDoorType}
      doorThickness={doorThickness}
      setDoorThickness={setDoorThickness}
      doorWidth={doorWidth}
      setDoorWidth={setDoorWidth}
      doorHeight={doorHeight}
      setDoorHeight={setDoorHeight}
      surfaceMaterial={surfaceMaterial}
      setSurfaceMaterial={setSurfaceMaterial}
      surfacePrice={surfacePrice}
      setSurfacePrice={setSurfacePrice}
      surfaceThickness={surfaceThickness}
      setSurfaceThickness={setSurfaceThickness}
      selectedFrameCode={selectedFrameCode}
      setSelectedFrameCode={setSelectedFrameCode}
      frameCandidates={frameCandidates}
      lockBlockPosition={lockBlockPosition}
      setLockBlockPosition={setLockBlockPosition}
      lockBlockPiecesPerSide={lockBlockPiecesPerSide}
      setLockBlockPiecesPerSide={setLockBlockPiecesPerSide}
      doubleFrameSides={doubleFrameSides}
      doubleFrameCount={doubleFrameCount}
      setDoubleFrameCount={setDoubleFrameCount}
      coreType={coreType}
      setCoreType={setCoreType}
      selectedCoreCode={selectedCoreCode}
      setSelectedCoreCode={setSelectedCoreCode}
      availableCoreItems={availableCoreItems}
      selectedCoreItem={selectedCoreItem}
      edgeBanding={edgeBanding}
      setEdgeBanding={setEdgeBanding}
      edgeMaterial={edgeMaterial}
      setEdgeMaterial={setEdgeMaterial}
      edgePrice={edgePrice}
      setEdgePrice={setEdgePrice}
      edgeSides={edgeSides}
      setEdgeSides={setEdgeSides}
      drilling={drilling}
      setDrilling={setDrilling}
      drillItems={drillItems}
      setDrillItems={setDrillItems}
      lockBlockLeft={lockBlockLeft}
      lockBlockRight={lockBlockRight}
      currentFrame={currentFrame}
      results={results}
      cuttingPlan={cuttingPlan}
      coreCalculation={coreCalculation}
      isDataComplete={isDataComplete}
      piecesPerSide={piecesPerSide}
      doubleConfigSummary={doubleConfigSummary}
      handleToggleDoubleSide={handleToggleDoubleSide}
      lockBlockDesc={lockBlockDesc}
      priceSummary={priceSummary}
      customMargin={customMargin}
      setCustomMargin={setCustomMargin}
    />
  );
}
