// BC Sync Configuration — all entities and field mappings
// Column naming convention: bc{Entity}{BCFieldName}
// e.g. table bcCustomer, field no → bcCustomerNo

export const bcSyncConfig = [
  // ─── 1. dimensionValues (NOT stored in Supabase — used to build dimMap in memory) ───
  {
    name: "Dimension Values",
    bcEndpoint: "dimensionValues",
    supabaseTable: null, // not stored
    bcPrimaryKey: null,
    supabaseConflictCol: null,
    syncGroup: "master",
    incrementalFilter: null,
    fieldMap: {
      dimensionCode: null,
      codeValue: null,
      nameValue: null,
    },
  },

  // ─── 2. customers ───
  {
    name: "Customers",
    bcEndpoint: "customers",
    supabaseTable: "bcCustomer",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcCustomerNo",
    syncGroup: "master",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcCustomerNo",
      nameValue: "bcCustomerNameValue",
      address: "bcCustomerAddress",
      address2: "bcCustomerAddress2",
      city: "bcCustomerCity",
      postCode: "bcCustomerPostCode",
      contact: "bcCustomerContact",
      phoneNo: "bcCustomerPhoneNo",
      eMail: "bcCustomerEMail",
      salespersonCode: "bcCustomerSalespersonCode",
      customerPostingGroup: "bcCustomerCustomerPostingGroup",
      paymentTermsCode: "bcCustomerPaymentTermsCode",
      globalDimension1Code: "bcCustomerGlobalDimension1Code",
      globalDimension2Code: "bcCustomerGlobalDimension2Code",
      creditLimitLCY: "bcCustomerCreditLimitLCY",
      balanceLCY: "bcCustomerBalanceLCY",
      balanceDueLCY: "bcCustomerBalanceDueLCY",
      outstandingOrders: "bcCustomerOutstandingOrders",
      shippedNotInvoiced: "bcCustomerShippedNotInvoiced",
      blocked: "bcCustomerBlocked",
      vATRegistrationNo: "bcCustomerVATRegistrationNo",
      paymentMethodCode: "bcCustomerPaymentMethodCode",
      genBusPostingGroup: "bcCustomerGenBusPostingGroup",
      salesLCY: "bcCustomerSalesLCY",
      profitLCY: "bcCustomerProfitLCY",
      mobilePhoneNo: "bcCustomerMobilePhoneNo",
      countryRegionCode: "bcCustomerCountryRegionCode",
      outstandingInvoices: "bcCustomerOutstandingInvoices",
      createdAt: "bcCustomerCreatedAt",
      lastModifiedDateTime: "bcCustomerLastModifiedDateTime",
    },
  },

  // ─── 3. items ───
  {
    name: "Items",
    bcEndpoint: "items",
    supabaseTable: "bcItem",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcItemNo",
    syncGroup: "master",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcItemNo",
      description: "bcItemDescription",
      description2: "bcItemDescription2",
      type: "bcItemType",
      blocked: "bcItemBlocked",
      baseUnitOfMeasure: "bcItemBaseUnitOfMeasure",
      unitPrice: "bcItemUnitPrice",
      unitCost: "bcItemUnitCost",
      genProdPostingGroup: "bcItemGenProdPostingGroup",
      itemCategoryCode: "bcItemItemCategoryCode",
      inventory: "bcItemInventory",
      globalDimension1Code: "bcItemGlobalDimension1Code",
      globalDimension2Code: "bcItemGlobalDimension2Code",
      vendorNo: "bcItemVendorNo",
      standardCost: "bcItemStandardCost",
      costingMethod: "bcItemCostingMethod",
      lastDirectCost: "bcItemLastDirectCost",
      inventoryPostingGroup: "bcItemInventoryPostingGroup",
      grossWeight: "bcItemGrossWeight",
      netWeight: "bcItemNetWeight",
      productionBOMNo: "bcItemProductionBOMNo",
      createdAt: "bcItemCreatedAt",
      lastModifiedDateTime: "bcItemLastModifiedDateTime",
    },
    // bcItemRfidCode is assigned locally, NOT from BC
  },

  // ─── 4. salesOrders + salesOrderLines ───
  {
    name: "Sales Orders",
    bcEndpoint: "salesOrders",
    supabaseTable: "bcSalesOrder",
    bcPrimaryKey: "noValue",
    supabaseConflictCol: "bcSalesOrderNoValue",
    linesEndpoint: "salesOrderLines",
    linesTable: "bcSalesOrderLine",
    linesConflictCols: "bcSalesOrderLineDocumentNo,bcSalesOrderLineLineNo",
    syncGroup: "document",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      noValue: "bcSalesOrderNoValue",
      sellToCustomerNo: "bcSalesOrderSellToCustomerNo",
      sellToCustomerName: "bcSalesOrderSellToCustomerName",
      sellToAddress: "bcSalesOrderSellToAddress",
      sellToAddress2: "bcSalesOrderSellToAddress2",
      sellToCity: "bcSalesOrderSellToCity",
      sellToPostCode: "bcSalesOrderSellToPostCode",
      shipToName: "bcSalesOrderShipToName",
      shipToAddress: "bcSalesOrderShipToAddress",
      shipToAddress2: "bcSalesOrderShipToAddress2",
      shipToCity: "bcSalesOrderShipToCity",
      shipToPostCode: "bcSalesOrderShipToPostCode",
      orderDate: "bcSalesOrderOrderDate",
      dueDate: "bcSalesOrderDueDate",
      status: "bcSalesOrderStatus",
      completelyShipped: "bcSalesOrderCompletelyShipped",
      salespersonCode: "bcSalesOrderSalespersonCode",
      externalDocumentNo: "bcSalesOrderExternalDocumentNo",
      locationCode: "bcSalesOrderLocationCode",
      shortcutDimension1Code: "bcSalesOrderShortcutDimension1Code",
      shortcutDimension2Code: "bcSalesOrderShortcutDimension2Code",
      amountValue: "bcSalesOrderAmountValue",
      amountIncludingVAT: "bcSalesOrderAmountIncludingVAT",
      assignedUserID: "bcSalesOrderAssignedUserID",
      requestedDeliveryDate: "bcSalesOrderRequestedDeliveryDate",
      paymentTermsCode: "bcSalesOrderPaymentTermsCode",
      paymentMethodCode: "bcSalesOrderPaymentMethodCode",
      currencyCode: "bcSalesOrderCurrencyCode",
      quoteNo: "bcSalesOrderQuoteNo",
      invoiceDiscountAmount: "bcSalesOrderInvoiceDiscountAmount",
      postingDate: "bcSalesOrderPostingDate",
      documentDate: "bcSalesOrderDocumentDate",
      shipmentMethodCode: "bcSalesOrderShipmentMethodCode",
      shippingAgentCode: "bcSalesOrderShippingAgentCode",
      lastShipmentDate: "bcSalesOrderLastShipmentDate",
      promisedDeliveryDate: "bcSalesOrderPromisedDeliveryDate",
      sellToPhoneNo: "bcSalesOrderSellToPhoneNo",
      sellToEMail: "bcSalesOrderSellToEMail",
      noSeries: "bcSalesOrderNoSeries",
      currencyFactor: "bcSalesOrderCurrencyFactor",
      createdAt: "bcSalesOrderCreatedAt",
      lastModifiedDateTime: "bcSalesOrderLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcSalesOrderLineDocumentNo",
      lineNo: "bcSalesOrderLineLineNo",
      typeValue: "bcSalesOrderLineTypeValue",
      noValue: "bcSalesOrderLineNoValue",
      descriptionValue: "bcSalesOrderLineDescriptionValue",
      quantityValue: "bcSalesOrderLineQuantityValue",
      outstandingQuantity: "bcSalesOrderLineOutstandingQuantity",
      quantityShipped: "bcSalesOrderLineQuantityShipped",
      unitPrice: "bcSalesOrderLineUnitPrice",
      lineDiscount: "bcSalesOrderLineLineDiscount",
      lineDiscountAmount: "bcSalesOrderLineLineDiscountAmount",
      amountValue: "bcSalesOrderLineAmountValue",
      amountIncludingVAT: "bcSalesOrderLineAmountIncludingVAT",
      unitOfMeasureCode: "bcSalesOrderLineUnitOfMeasureCode",
      locationCode: "bcSalesOrderLineLocationCode",
      shortcutDimension1Code: "bcSalesOrderLineShortcutDimension1Code",
      shortcutDimension2Code: "bcSalesOrderLineShortcutDimension2Code",
      unitCost: "bcSalesOrderLineUnitCost",
      quantityInvoiced: "bcSalesOrderLineQuantityInvoiced",
      profit: "bcSalesOrderLineProfit",
      variantCode: "bcSalesOrderLineVariantCode",
      itemCategoryCode: "bcSalesOrderLineItemCategoryCode",
      genProdPostingGroup: "bcSalesOrderLineGenProdPostingGroup",
      shipmentDate: "bcSalesOrderLineShipmentDate",
      outstandingAmount: "bcSalesOrderLineOutstandingAmount",
      invDiscountAmount: "bcSalesOrderLineInvDiscountAmount",
      plannedDeliveryDate: "bcSalesOrderLinePlannedDeliveryDate",
      plannedShipmentDate: "bcSalesOrderLinePlannedShipmentDate",
      description2: "bcSalesOrderLineDescription2",
      vAT: "bcSalesOrderLineVAT",
      lineAmount: "bcSalesOrderLineLineAmount",
      qtyToShip: "bcSalesOrderLineQtyToShip",
      qtyToInvoice: "bcSalesOrderLineQtyToInvoice",
      dropShipment: "bcSalesOrderLineDropShipment",
      binCode: "bcSalesOrderLineBinCode",
      completelyShipped: "bcSalesOrderLineCompletelyShipped",
      createdAt: "bcSalesOrderLineCreatedAt",
      lastModifiedDateTime: "bcSalesOrderLineLastModifiedDateTime",
    },
  },

  // ─── 5. purchaseOrders + purchaseOrderLines ───
  {
    name: "Purchase Orders",
    bcEndpoint: "purchaseOrders",
    supabaseTable: "bcPurchaseOrder",
    bcPrimaryKey: "noValue",
    supabaseConflictCol: "bcPurchaseOrderNoValue",
    linesEndpoint: "purchaseOrderLines",
    linesTable: "bcPurchaseOrderLine",
    linesConflictCols: "bcPurchaseOrderLineDocumentNo,bcPurchaseOrderLineLineNo",
    syncGroup: "document",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      noValue: "bcPurchaseOrderNoValue",
      buyFromVendorNo: "bcPurchaseOrderBuyFromVendorNo",
      buyFromVendorName: "bcPurchaseOrderBuyFromVendorName",
      buyFromAddress: "bcPurchaseOrderBuyFromAddress",
      buyFromAddress2: "bcPurchaseOrderBuyFromAddress2",
      buyFromCity: "bcPurchaseOrderBuyFromCity",
      buyFromPostCode: "bcPurchaseOrderBuyFromPostCode",
      orderDate: "bcPurchaseOrderOrderDate",
      postingDate: "bcPurchaseOrderPostingDate",
      expectedReceiptDate: "bcPurchaseOrderExpectedReceiptDate",
      dueDate: "bcPurchaseOrderDueDate",
      documentDate: "bcPurchaseOrderDocumentDate",
      amountValue: "bcPurchaseOrderAmountValue",
      amountIncludingVAT: "bcPurchaseOrderAmountIncludingVAT",
      purchaserCode: "bcPurchaseOrderPurchaserCode",
      shortcutDimension1Code: "bcPurchaseOrderShortcutDimension1Code",
      shortcutDimension2Code: "bcPurchaseOrderShortcutDimension2Code",
      locationCode: "bcPurchaseOrderLocationCode",
      currencyCode: "bcPurchaseOrderCurrencyCode",
      currencyFactor: "bcPurchaseOrderCurrencyFactor",
      paymentTermsCode: "bcPurchaseOrderPaymentTermsCode",
      paymentMethodCode: "bcPurchaseOrderPaymentMethodCode",
      vendorInvoiceNo: "bcPurchaseOrderVendorInvoiceNo",
      vendorOrderNo: "bcPurchaseOrderVendorOrderNo",
      status: "bcPurchaseOrderStatus",
      completelyReceived: "bcPurchaseOrderCompletelyReceived",
      invoiceDiscountAmount: "bcPurchaseOrderInvoiceDiscountAmount",
      assignedUserID: "bcPurchaseOrderAssignedUserID",
      genBusPostingGroup: "bcPurchaseOrderGenBusPostingGroup",
      createdAt: "bcPurchaseOrderCreatedAt",
      lastModifiedDateTime: "bcPurchaseOrderLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcPurchaseOrderLineDocumentNo",
      lineNo: "bcPurchaseOrderLineLineNo",
      typeValue: "bcPurchaseOrderLineTypeValue",
      noValue: "bcPurchaseOrderLineNoValue",
      descriptionValue: "bcPurchaseOrderLineDescriptionValue",
      description2: "bcPurchaseOrderLineDescription2",
      quantityValue: "bcPurchaseOrderLineQuantityValue",
      outstandingQuantity: "bcPurchaseOrderLineOutstandingQuantity",
      quantityReceived: "bcPurchaseOrderLineQuantityReceived",
      quantityInvoiced: "bcPurchaseOrderLineQuantityInvoiced",
      directUnitCost: "bcPurchaseOrderLineDirectUnitCost",
      amountValue: "bcPurchaseOrderLineAmountValue",
      amountIncludingVAT: "bcPurchaseOrderLineAmountIncludingVAT",
      lineDiscount: "bcPurchaseOrderLineLineDiscount",
      unitOfMeasureCode: "bcPurchaseOrderLineUnitOfMeasureCode",
      locationCode: "bcPurchaseOrderLineLocationCode",
      shortcutDimension1Code: "bcPurchaseOrderLineShortcutDimension1Code",
      shortcutDimension2Code: "bcPurchaseOrderLineShortcutDimension2Code",
      genProdPostingGroup: "bcPurchaseOrderLineGenProdPostingGroup",
      itemCategoryCode: "bcPurchaseOrderLineItemCategoryCode",
      createdAt: "bcPurchaseOrderLineCreatedAt",
      lastModifiedDateTime: "bcPurchaseOrderLineLastModifiedDateTime",
    },
  },

  // ─── 6. salesInvoices + salesInvoiceLines ───
  {
    name: "Sales Invoices",
    bcEndpoint: "salesInvoices",
    supabaseTable: "bcSalesInvoice",
    bcPrimaryKey: "noValue",
    supabaseConflictCol: "bcSalesInvoiceNoValue",
    linesEndpoint: "salesInvoiceLines",
    linesTable: "bcSalesInvoiceLine",
    linesConflictCols: "bcSalesInvoiceLineDocumentNo,bcSalesInvoiceLineLineNo",
    syncGroup: "document",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      noValue: "bcSalesInvoiceNoValue",
      sellToCustomerNo: "bcSalesInvoiceSellToCustomerNo",
      sellToCustomerName: "bcSalesInvoiceSellToCustomerName",
      sellToAddress: "bcSalesInvoiceSellToAddress",
      sellToAddress2: "bcSalesInvoiceSellToAddress2",
      sellToCity: "bcSalesInvoiceSellToCity",
      sellToPostCode: "bcSalesInvoiceSellToPostCode",
      orderDate: "bcSalesInvoiceOrderDate",
      postingDate: "bcSalesInvoicePostingDate",
      documentDate: "bcSalesInvoiceDocumentDate",
      dueDate: "bcSalesInvoiceDueDate",
      amountValue: "bcSalesInvoiceAmountValue",
      amountIncludingVAT: "bcSalesInvoiceAmountIncludingVAT",
      salespersonCode: "bcSalesInvoiceSalespersonCode",
      shortcutDimension1Code: "bcSalesInvoiceShortcutDimension1Code",
      shortcutDimension2Code: "bcSalesInvoiceShortcutDimension2Code",
      locationCode: "bcSalesInvoiceLocationCode",
      currencyCode: "bcSalesInvoiceCurrencyCode",
      paymentTermsCode: "bcSalesInvoicePaymentTermsCode",
      paymentMethodCode: "bcSalesInvoicePaymentMethodCode",
      externalDocumentNo: "bcSalesInvoiceExternalDocumentNo",
      status: "bcSalesInvoiceStatus",
      invoiceDiscountAmount: "bcSalesInvoiceInvoiceDiscountAmount",
      createdAt: "bcSalesInvoiceCreatedAt",
      lastModifiedDateTime: "bcSalesInvoiceLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcSalesInvoiceLineDocumentNo",
      lineNo: "bcSalesInvoiceLineLineNo",
      typeValue: "bcSalesInvoiceLineTypeValue",
      noValue: "bcSalesInvoiceLineNoValue",
      descriptionValue: "bcSalesInvoiceLineDescriptionValue",
      description2: "bcSalesInvoiceLineDescription2",
      quantityValue: "bcSalesInvoiceLineQuantityValue",
      unitPrice: "bcSalesInvoiceLineUnitPrice",
      unitCost: "bcSalesInvoiceLineUnitCost",
      amountValue: "bcSalesInvoiceLineAmountValue",
      amountIncludingVAT: "bcSalesInvoiceLineAmountIncludingVAT",
      lineDiscount: "bcSalesInvoiceLineLineDiscount",
      lineDiscountAmount: "bcSalesInvoiceLineLineDiscountAmount",
      unitOfMeasureCode: "bcSalesInvoiceLineUnitOfMeasureCode",
      locationCode: "bcSalesInvoiceLineLocationCode",
      shortcutDimension1Code: "bcSalesInvoiceLineShortcutDimension1Code",
      shortcutDimension2Code: "bcSalesInvoiceLineShortcutDimension2Code",
      genProdPostingGroup: "bcSalesInvoiceLineGenProdPostingGroup",
      createdAt: "bcSalesInvoiceLineCreatedAt",
      lastModifiedDateTime: "bcSalesInvoiceLineLastModifiedDateTime",
    },
  },

  // ─── 7. productionOrders + productionOrderLines ───
  {
    name: "Production Orders",
    bcEndpoint: "productionOrders",
    supabaseTable: "bcProductionOrder",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcProductionOrderNo",
    linesEndpoint: "productionOrderLines",
    linesTable: "bcProductionOrderLine",
    linesConflictCols: "bcProductionOrderLineProdOrderNo,bcProductionOrderLineLineNo",
    syncGroup: "document",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcProductionOrderNo",
      status: "bcProductionOrderStatus",
      description: "bcProductionOrderDescription",
      description2: "bcProductionOrderDescription2",
      sourceNo: "bcProductionOrderSourceNo",
      routingNo: "bcProductionOrderRoutingNo",
      quantity: "bcProductionOrderQuantity",
      shortcutDimension1Code: "bcProductionOrderShortcutDimension1Code",
      shortcutDimension2Code: "bcProductionOrderShortcutDimension2Code",
      locationCode: "bcProductionOrderLocationCode",
      dueDate: "bcProductionOrderDueDate",
      finishedDate: "bcProductionOrderFinishedDate",
      startingDateTime: "bcProductionOrderStartingDateTime",
      endingDateTime: "bcProductionOrderEndingDateTime",
      assignedUserID: "bcProductionOrderAssignedUserID",
      searchDescription: "bcProductionOrderSearchDescription",
      costAmount: "bcProductionOrderCostAmount",
      unitCost: "bcProductionOrderUnitCost",
      sourceType: "bcProductionOrderSourceType",
      binCode: "bcProductionOrderBinCode",
      creationDate: "bcProductionOrderCreationDate",
      expectedOperationCostAmt: "bcProductionOrderExpectedOperationCostAmt",
      expectedComponentCostAmt: "bcProductionOrderExpectedComponentCostAmt",
      actualTimeUsed: "bcProductionOrderActualTimeUsed",
      completelyPicked: "bcProductionOrderCompletelyPicked",
      documentPutAwayStatus: "bcProductionOrderDocumentPutAwayStatus",
      plannedOrderNo: "bcProductionOrderPlannedOrderNo",
      createdAt: "bcProductionOrderCreatedAt",
      lastModifiedDateTime: "bcProductionOrderLastModifiedDateTime",
    },
    lineFieldMap: {
      status: "bcProductionOrderLineStatus",
      prodOrderNo: "bcProductionOrderLineProdOrderNo",
      lineNo: "bcProductionOrderLineLineNo",
      itemNo: "bcProductionOrderLineItemNo",
      description: "bcProductionOrderLineDescription",
      description2: "bcProductionOrderLineDescription2",
      quantity: "bcProductionOrderLineQuantity",
      finishedQuantity: "bcProductionOrderLineFinishedQuantity",
      remainingQuantity: "bcProductionOrderLineRemainingQuantity",
      unitOfMeasureCode: "bcProductionOrderLineUnitOfMeasureCode",
      locationCode: "bcProductionOrderLineLocationCode",
      shortcutDimension1Code: "bcProductionOrderLineShortcutDimension1Code",
      shortcutDimension2Code: "bcProductionOrderLineShortcutDimension2Code",
      dueDate: "bcProductionOrderLineDueDate",
      unitCost: "bcProductionOrderLineUnitCost",
      costAmount: "bcProductionOrderLineCostAmount",
      scrap: "bcProductionOrderLineScrap",
      routingNo: "bcProductionOrderLineRoutingNo",
      productionBOMNo: "bcProductionOrderLineProductionBOMNo",
      variantCode: "bcProductionOrderLineVariantCode",
      binCode: "bcProductionOrderLineBinCode",
      startingDateTime: "bcProductionOrderLineStartingDateTime",
      endingDateTime: "bcProductionOrderLineEndingDateTime",
      putAwayStatus: "bcProductionOrderLinePutAwayStatus",
      createdAt: "bcProductionOrderLineCreatedAt",
      lastModifiedDateTime: "bcProductionOrderLineLastModifiedDateTime",
    },
  },

  // ─── 8. postedSalesInvoices + postedSalesInvoiceLines ───
  {
    name: "Posted Sales Invoices",
    bcEndpoint: "postedSalesInvoices",
    supabaseTable: "bcPostedSalesInvoice",
    bcPrimaryKey: "noValue",
    supabaseConflictCol: "bcPostedSalesInvoiceNoValue",
    linesEndpoint: "postedSalesInvoiceLines",
    linesTable: "bcPostedSalesInvoiceLine",
    linesConflictCols: "bcPostedSalesInvoiceLineDocumentNo,bcPostedSalesInvoiceLineLineNo",
    syncGroup: "postedDoc",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      noValue: "bcPostedSalesInvoiceNoValue",
      sellToCustomerNo: "bcPostedSalesInvoiceSellToCustomerNo",
      sellToCustomerName: "bcPostedSalesInvoiceSellToCustomerName",
      sellToAddress: "bcPostedSalesInvoiceSellToAddress",
      sellToAddress2: "bcPostedSalesInvoiceSellToAddress2",
      sellToCity: "bcPostedSalesInvoiceSellToCity",
      sellToPostCode: "bcPostedSalesInvoiceSellToPostCode",
      orderNo: "bcPostedSalesInvoiceOrderNo",
      orderDate: "bcPostedSalesInvoiceOrderDate",
      postingDate: "bcPostedSalesInvoicePostingDate",
      documentDate: "bcPostedSalesInvoiceDocumentDate",
      dueDate: "bcPostedSalesInvoiceDueDate",
      amountValue: "bcPostedSalesInvoiceAmountValue",
      amountIncludingVAT: "bcPostedSalesInvoiceAmountIncludingVAT",
      salespersonCode: "bcPostedSalesInvoiceSalespersonCode",
      shortcutDimension1Code: "bcPostedSalesInvoiceShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedSalesInvoiceShortcutDimension2Code",
      locationCode: "bcPostedSalesInvoiceLocationCode",
      currencyCode: "bcPostedSalesInvoiceCurrencyCode",
      currencyFactor: "bcPostedSalesInvoiceCurrencyFactor",
      paymentTermsCode: "bcPostedSalesInvoicePaymentTermsCode",
      paymentMethodCode: "bcPostedSalesInvoicePaymentMethodCode",
      externalDocumentNo: "bcPostedSalesInvoiceExternalDocumentNo",
      genBusPostingGroup: "bcPostedSalesInvoiceGenBusPostingGroup",
      customerPostingGroup: "bcPostedSalesInvoiceCustomerPostingGroup",
      remainingAmount: "bcPostedSalesInvoiceRemainingAmount",
      closedValue: "bcPostedSalesInvoiceClosedValue",
      invoiceDiscountAmount: "bcPostedSalesInvoiceInvoiceDiscountAmount",
      createdAt: "bcPostedSalesInvoiceCreatedAt",
      lastModifiedDateTime: "bcPostedSalesInvoiceLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcPostedSalesInvoiceLineDocumentNo",
      lineNo: "bcPostedSalesInvoiceLineLineNo",
      typeValue: "bcPostedSalesInvoiceLineTypeValue",
      noValue: "bcPostedSalesInvoiceLineNoValue",
      descriptionValue: "bcPostedSalesInvoiceLineDescriptionValue",
      description2: "bcPostedSalesInvoiceLineDescription2",
      quantityValue: "bcPostedSalesInvoiceLineQuantityValue",
      unitPrice: "bcPostedSalesInvoiceLineUnitPrice",
      unitCost: "bcPostedSalesInvoiceLineUnitCost",
      amountValue: "bcPostedSalesInvoiceLineAmountValue",
      amountIncludingVAT: "bcPostedSalesInvoiceLineAmountIncludingVAT",
      lineDiscount: "bcPostedSalesInvoiceLineLineDiscount",
      lineDiscountAmount: "bcPostedSalesInvoiceLineLineDiscountAmount",
      unitOfMeasureCode: "bcPostedSalesInvoiceLineUnitOfMeasureCode",
      locationCode: "bcPostedSalesInvoiceLineLocationCode",
      shortcutDimension1Code: "bcPostedSalesInvoiceLineShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedSalesInvoiceLineShortcutDimension2Code",
      genProdPostingGroup: "bcPostedSalesInvoiceLineGenProdPostingGroup",
      itemCategoryCode: "bcPostedSalesInvoiceLineItemCategoryCode",
      variantCode: "bcPostedSalesInvoiceLineVariantCode",
      createdAt: "bcPostedSalesInvoiceLineCreatedAt",
      lastModifiedDateTime: "bcPostedSalesInvoiceLineLastModifiedDateTime",
    },
  },

  // ─── 9. postedSalesShipments + postedSalesShipmentLines ───
  {
    name: "Posted Sales Shipments",
    bcEndpoint: "postedSalesShipments",
    supabaseTable: "bcPostedSalesShipment",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcPostedSalesShipmentNo",
    linesEndpoint: "postedSalesShipmentLines",
    linesTable: "bcPostedSalesShipmentLine",
    linesConflictCols: "bcPostedSalesShipmentLineDocumentNo,bcPostedSalesShipmentLineLineNo",
    syncGroup: "postedDoc",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcPostedSalesShipmentNo",
      sellToCustomerNo: "bcPostedSalesShipmentSellToCustomerNo",
      sellToCustomerName: "bcPostedSalesShipmentSellToCustomerName",
      orderNo: "bcPostedSalesShipmentOrderNo",
      orderDate: "bcPostedSalesShipmentOrderDate",
      postingDate: "bcPostedSalesShipmentPostingDate",
      shipmentDate: "bcPostedSalesShipmentShipmentDate",
      documentDate: "bcPostedSalesShipmentDocumentDate",
      salespersonCode: "bcPostedSalesShipmentSalespersonCode",
      shortcutDimension1Code: "bcPostedSalesShipmentShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedSalesShipmentShortcutDimension2Code",
      locationCode: "bcPostedSalesShipmentLocationCode",
      currencyCode: "bcPostedSalesShipmentCurrencyCode",
      externalDocumentNo: "bcPostedSalesShipmentExternalDocumentNo",
      shipmentMethodCode: "bcPostedSalesShipmentShipmentMethodCode",
      shippingAgentCode: "bcPostedSalesShipmentShippingAgentCode",
      packageTrackingNo: "bcPostedSalesShipmentPackageTrackingNo",
      requestedDeliveryDate: "bcPostedSalesShipmentRequestedDeliveryDate",
      createdAt: "bcPostedSalesShipmentCreatedAt",
      lastModifiedDateTime: "bcPostedSalesShipmentLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcPostedSalesShipmentLineDocumentNo",
      lineNo: "bcPostedSalesShipmentLineLineNo",
      typeValue: "bcPostedSalesShipmentLineTypeValue",
      no: "bcPostedSalesShipmentLineNoValue",
      description: "bcPostedSalesShipmentLineDescriptionValue",
      description2: "bcPostedSalesShipmentLineDescription2",
      quantity: "bcPostedSalesShipmentLineQuantityValue",
      unitOfMeasureCode: "bcPostedSalesShipmentLineUnitOfMeasureCode",
      locationCode: "bcPostedSalesShipmentLineLocationCode",
      shortcutDimension1Code: "bcPostedSalesShipmentLineShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedSalesShipmentLineShortcutDimension2Code",
      genProdPostingGroup: "bcPostedSalesShipmentLineGenProdPostingGroup",
      itemCategoryCode: "bcPostedSalesShipmentLineItemCategoryCode",
      variantCode: "bcPostedSalesShipmentLineVariantCode",
      createdAt: "bcPostedSalesShipmentLineCreatedAt",
      lastModifiedDateTime: "bcPostedSalesShipmentLineLastModifiedDateTime",
    },
  },

  // ─── 10. postedSalesCreditMemos + postedSalesCreditMemoLines ───
  {
    name: "Posted Sales Credit Memos",
    bcEndpoint: "postedSalesCreditMemos",
    supabaseTable: "bcPostedSalesCreditMemo",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcPostedSalesCreditMemoNo",
    linesEndpoint: "postedSalesCreditMemoLines",
    linesTable: "bcPostedSalesCreditMemoLine",
    linesConflictCols: "bcPostedSalesCreditMemoLineDocumentNo,bcPostedSalesCreditMemoLineLineNo",
    syncGroup: "postedDoc",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcPostedSalesCreditMemoNo",
      sellToCustomerNo: "bcPostedSalesCreditMemoSellToCustomerNo",
      sellToCustomerName: "bcPostedSalesCreditMemoSellToCustomerName",
      postingDate: "bcPostedSalesCreditMemoPostingDate",
      documentDate: "bcPostedSalesCreditMemoDocumentDate",
      dueDate: "bcPostedSalesCreditMemoDueDate",
      amount: "bcPostedSalesCreditMemoAmount",
      amountIncludingVAT: "bcPostedSalesCreditMemoAmountIncludingVAT",
      salespersonCode: "bcPostedSalesCreditMemoSalespersonCode",
      shortcutDimension1Code: "bcPostedSalesCreditMemoShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedSalesCreditMemoShortcutDimension2Code",
      locationCode: "bcPostedSalesCreditMemoLocationCode",
      currencyCode: "bcPostedSalesCreditMemoCurrencyCode",
      currencyFactor: "bcPostedSalesCreditMemoCurrencyFactor",
      externalDocumentNo: "bcPostedSalesCreditMemoExternalDocumentNo",
      genBusPostingGroup: "bcPostedSalesCreditMemoGenBusPostingGroup",
      remainingAmount: "bcPostedSalesCreditMemoRemainingAmount",
      paid: "bcPostedSalesCreditMemoPaid",
      cancelled: "bcPostedSalesCreditMemoCancelled",
      corrective: "bcPostedSalesCreditMemoCorrective",
      createdAt: "bcPostedSalesCreditMemoCreatedAt",
      lastModifiedDateTime: "bcPostedSalesCreditMemoLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcPostedSalesCreditMemoLineDocumentNo",
      lineNo: "bcPostedSalesCreditMemoLineLineNo",
      typeValue: "bcPostedSalesCreditMemoLineTypeValue",
      no: "bcPostedSalesCreditMemoLineNoValue",
      description: "bcPostedSalesCreditMemoLineDescriptionValue",
      description2: "bcPostedSalesCreditMemoLineDescription2",
      quantity: "bcPostedSalesCreditMemoLineQuantityValue",
      unitPrice: "bcPostedSalesCreditMemoLineUnitPrice",
      unitCost: "bcPostedSalesCreditMemoLineUnitCost",
      amount: "bcPostedSalesCreditMemoLineAmountValue",
      amountIncludingVAT: "bcPostedSalesCreditMemoLineAmountIncludingVAT",
      lineDiscount: "bcPostedSalesCreditMemoLineLineDiscount",
      unitOfMeasureCode: "bcPostedSalesCreditMemoLineUnitOfMeasureCode",
      locationCode: "bcPostedSalesCreditMemoLineLocationCode",
      shortcutDimension1Code: "bcPostedSalesCreditMemoLineShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedSalesCreditMemoLineShortcutDimension2Code",
      createdAt: "bcPostedSalesCreditMemoLineCreatedAt",
      lastModifiedDateTime: "bcPostedSalesCreditMemoLineLastModifiedDateTime",
    },
  },

  // ─── 11. postedPurchInvoices + postedPurchInvoiceLines ───
  {
    name: "Posted Purchase Invoices",
    bcEndpoint: "postedPurchInvoices",
    supabaseTable: "bcPostedPurchInvoice",
    bcPrimaryKey: "noValue",
    supabaseConflictCol: "bcPostedPurchInvoiceNoValue",
    linesEndpoint: "postedPurchInvoiceLines",
    linesTable: "bcPostedPurchInvoiceLine",
    linesConflictCols: "bcPostedPurchInvoiceLineDocumentNo,bcPostedPurchInvoiceLineLineNo",
    syncGroup: "postedDoc",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      noValue: "bcPostedPurchInvoiceNoValue",
      buyFromVendorNo: "bcPostedPurchInvoiceBuyFromVendorNo",
      buyFromVendorName: "bcPostedPurchInvoiceBuyFromVendorName",
      orderNo: "bcPostedPurchInvoiceOrderNo",
      orderDate: "bcPostedPurchInvoiceOrderDate",
      postingDate: "bcPostedPurchInvoicePostingDate",
      documentDate: "bcPostedPurchInvoiceDocumentDate",
      dueDate: "bcPostedPurchInvoiceDueDate",
      amountValue: "bcPostedPurchInvoiceAmountValue",
      amountIncludingVAT: "bcPostedPurchInvoiceAmountIncludingVAT",
      purchaserCode: "bcPostedPurchInvoicePurchaserCode",
      shortcutDimension1Code: "bcPostedPurchInvoiceShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedPurchInvoiceShortcutDimension2Code",
      locationCode: "bcPostedPurchInvoiceLocationCode",
      currencyCode: "bcPostedPurchInvoiceCurrencyCode",
      currencyFactor: "bcPostedPurchInvoiceCurrencyFactor",
      paymentTermsCode: "bcPostedPurchInvoicePaymentTermsCode",
      paymentMethodCode: "bcPostedPurchInvoicePaymentMethodCode",
      vendorInvoiceNo: "bcPostedPurchInvoiceVendorInvoiceNo",
      vendorOrderNo: "bcPostedPurchInvoiceVendorOrderNo",
      genBusPostingGroup: "bcPostedPurchInvoiceGenBusPostingGroup",
      remainingAmount: "bcPostedPurchInvoiceRemainingAmount",
      closedValue: "bcPostedPurchInvoiceClosedValue",
      invoiceDiscountAmount: "bcPostedPurchInvoiceInvoiceDiscountAmount",
      createdAt: "bcPostedPurchInvoiceCreatedAt",
      lastModifiedDateTime: "bcPostedPurchInvoiceLastModifiedDateTime",
    },
    lineFieldMap: {
      documentNo: "bcPostedPurchInvoiceLineDocumentNo",
      lineNo: "bcPostedPurchInvoiceLineLineNo",
      typeValue: "bcPostedPurchInvoiceLineTypeValue",
      noValue: "bcPostedPurchInvoiceLineNoValue",
      descriptionValue: "bcPostedPurchInvoiceLineDescriptionValue",
      description2: "bcPostedPurchInvoiceLineDescription2",
      quantityValue: "bcPostedPurchInvoiceLineQuantityValue",
      directUnitCost: "bcPostedPurchInvoiceLineDirectUnitCost",
      amountValue: "bcPostedPurchInvoiceLineAmountValue",
      amountIncludingVAT: "bcPostedPurchInvoiceLineAmountIncludingVAT",
      lineDiscount: "bcPostedPurchInvoiceLineLineDiscount",
      unitOfMeasureCode: "bcPostedPurchInvoiceLineUnitOfMeasureCode",
      locationCode: "bcPostedPurchInvoiceLineLocationCode",
      shortcutDimension1Code: "bcPostedPurchInvoiceLineShortcutDimension1Code",
      shortcutDimension2Code: "bcPostedPurchInvoiceLineShortcutDimension2Code",
      genProdPostingGroup: "bcPostedPurchInvoiceLineGenProdPostingGroup",
      itemCategoryCode: "bcPostedPurchInvoiceLineItemCategoryCode",
      variantCode: "bcPostedPurchInvoiceLineVariantCode",
      createdAt: "bcPostedPurchInvoiceLineCreatedAt",
      lastModifiedDateTime: "bcPostedPurchInvoiceLineLastModifiedDateTime",
    },
  },

  // ─── 12. vendors ───
  {
    name: "Vendors",
    bcEndpoint: "vendors",
    supabaseTable: "bcVendor",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcVendorNo",
    syncGroup: "master",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcVendorNo",
      nameValue: "bcVendorNameValue",
      address: "bcVendorAddress",
      address2: "bcVendorAddress2",
      city: "bcVendorCity",
      postCode: "bcVendorPostCode",
      contact: "bcVendorContact",
      phoneNo: "bcVendorPhoneNo",
      eMail: "bcVendorEMail",
      mobilePhoneNo: "bcVendorMobilePhoneNo",
      vendorPostingGroup: "bcVendorVendorPostingGroup",
      paymentTermsCode: "bcVendorPaymentTermsCode",
      paymentMethodCode: "bcVendorPaymentMethodCode",
      purchaserCode: "bcVendorPurchaserCode",
      globalDimension1Code: "bcVendorGlobalDimension1Code",
      globalDimension2Code: "bcVendorGlobalDimension2Code",
      balanceLCY: "bcVendorBalanceLCY",
      balanceDueLCY: "bcVendorBalanceDueLCY",
      vATRegistrationNo: "bcVendorVATRegistrationNo",
      genBusPostingGroup: "bcVendorGenBusPostingGroup",
      blocked: "bcVendorBlocked",
      countryRegionCode: "bcVendorCountryRegionCode",
      outstandingOrders: "bcVendorOutstandingOrders",
      outstandingInvoices: "bcVendorOutstandingInvoices",
      purchasesLCY: "bcVendorPurchasesLCY",
      createdAt: "bcVendorCreatedAt",
      lastModifiedDateTime: "bcVendorLastModifiedDateTime",
    },
  },

  // ─── 13. glAccounts ───
  {
    name: "GL Accounts",
    bcEndpoint: "glAccounts",
    supabaseTable: "bcGLAccount",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcGLAccountNo",
    syncGroup: "small",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcGLAccountNo",
      nameValue: "bcGLAccountNameValue",
      accountType: "bcGLAccountAccountType",
      accountCategory: "bcGLAccountAccountCategory",
      incomeBalance: "bcGLAccountIncomeBalance",
      debitCredit: "bcGLAccountDebitCredit",
      balance: "bcGLAccountBalance",
      netChange: "bcGLAccountNetChange",
      blocked: "bcGLAccountBlocked",
      directPosting: "bcGLAccountDirectPosting",
      indentation: "bcGLAccountIndentation",
      totaling: "bcGLAccountTotaling",
      createdAt: "bcGLAccountCreatedAt",
      lastModifiedDateTime: "bcGLAccountLastModifiedDateTime",
    },
  },

  // ─── 14. bankAccounts ───
  {
    name: "Bank Accounts",
    bcEndpoint: "bankAccounts",
    supabaseTable: "bcBankAccount",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcBankAccountNo",
    syncGroup: "small",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcBankAccountNo",
      nameValue: "bcBankAccountNameValue",
      bankAccountNo: "bcBankAccountBankAccountNo",
      bankBranchNo: "bcBankAccountBankBranchNo",
      currencyCode: "bcBankAccountCurrencyCode",
      balance: "bcBankAccountBalance",
      balanceLCY: "bcBankAccountBalanceLCY",
      iBAN: "bcBankAccountIBAN",
      sWIFTCode: "bcBankAccountSWIFTCode",
      globalDimension1Code: "bcBankAccountGlobalDimension1Code",
      globalDimension2Code: "bcBankAccountGlobalDimension2Code",
      blocked: "bcBankAccountBlocked",
      createdAt: "bcBankAccountCreatedAt",
      lastModifiedDateTime: "bcBankAccountLastModifiedDateTime",
    },
  },

  // ─── 15. fixedAssets ───
  {
    name: "Fixed Assets",
    bcEndpoint: "fixedAssets",
    supabaseTable: "bcFixedAsset",
    bcPrimaryKey: "no",
    supabaseConflictCol: "bcFixedAssetNo",
    syncGroup: "small",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      no: "bcFixedAssetNo",
      description: "bcFixedAssetDescription",
      description2: "bcFixedAssetDescription2",
      fAClassCode: "bcFixedAssetFAClassCode",
      fASubclassCode: "bcFixedAssetFASubclassCode",
      globalDimension1Code: "bcFixedAssetGlobalDimension1Code",
      globalDimension2Code: "bcFixedAssetGlobalDimension2Code",
      locationCode: "bcFixedAssetLocationCode",
      fALocationCode: "bcFixedAssetFALocationCode",
      vendorNo: "bcFixedAssetVendorNo",
      responsibleEmployee: "bcFixedAssetResponsibleEmployee",
      serialNo: "bcFixedAssetSerialNo",
      warrantyDate: "bcFixedAssetWarrantyDate",
      acquired: "bcFixedAssetAcquired",
      inactive: "bcFixedAssetInactive",
      blocked: "bcFixedAssetBlocked",
      fAPostingGroup: "bcFixedAssetFAPostingGroup",
      lastDateModified: "bcFixedAssetLastDateModified",
      createdAt: "bcFixedAssetCreatedAt",
      lastModifiedDateTime: "bcFixedAssetLastModifiedDateTime",
    },
  },

  // ─── 16. dimensionSetEntries ───
  {
    name: "Dimension Set Entries",
    bcEndpoint: "dimensionSetEntries",
    supabaseTable: "bcDimensionSetEntry",
    bcPrimaryKey: null,
    supabaseConflictCol: "bcDimensionSetEntryDimensionSetID,bcDimensionSetEntryDimensionCode",
    syncGroup: "small",
    incrementalFilter: null, // always full sync
    fieldMap: {
      dimensionSetID: "bcDimensionSetEntryDimensionSetID",
      dimensionCode: "bcDimensionSetEntryDimensionCode",
      dimensionValueCode: "bcDimensionSetEntryDimensionValueCode",
      dimensionValueID: "bcDimensionSetEntryDimensionValueID",
      dimensionName: "bcDimensionSetEntryDimensionName",
      dimensionValueName: "bcDimensionSetEntryDimensionValueName",
      globalDimensionNo: "bcDimensionSetEntryGlobalDimensionNo",
      createdAt: "bcDimensionSetEntryCreatedAt",
    },
  },

  // ─── 17. salesQuotes ───
  {
    name: "Sales Quotes",
    bcEndpoint: "salesQuotes",
    supabaseTable: "bcSalesQuote",
    bcPrimaryKey: "noValue",
    supabaseConflictCol: "bcSalesQuoteNoValue",
    syncGroup: "small",
    incrementalFilter: (lastSync) =>
      `lastModifiedDateTime gt ${lastSync}`,
    fieldMap: {
      noValue: "bcSalesQuoteNoValue",
      sellToCustomerNo: "bcSalesQuoteSellToCustomerNo",
      sellToCustomerName: "bcSalesQuoteSellToCustomerName",
      orderDate: "bcSalesQuoteOrderDate",
      dueDate: "bcSalesQuoteDueDate",
      documentDate: "bcSalesQuoteDocumentDate",
      amountValue: "bcSalesQuoteAmountValue",
      amountIncludingVAT: "bcSalesQuoteAmountIncludingVAT",
      salespersonCode: "bcSalesQuoteSalespersonCode",
      shortcutDimension1Code: "bcSalesQuoteShortcutDimension1Code",
      shortcutDimension2Code: "bcSalesQuoteShortcutDimension2Code",
      locationCode: "bcSalesQuoteLocationCode",
      currencyCode: "bcSalesQuoteCurrencyCode",
      externalDocumentNo: "bcSalesQuoteExternalDocumentNo",
      status: "bcSalesQuoteStatus",
      quoteValidUntilDate: "bcSalesQuoteQuoteValidUntilDate",
      quoteAccepted: "bcSalesQuoteQuoteAccepted",
      quoteAcceptedDate: "bcSalesQuoteQuoteAcceptedDate",
      opportunityNo: "bcSalesQuoteOpportunityNo",
      assignedUserID: "bcSalesQuoteAssignedUserID",
      createdAt: "bcSalesQuoteCreatedAt",
      lastModifiedDateTime: "bcSalesQuoteLastModifiedDateTime",
    },
  },

  // ─── 18. valueEntries ───
  {
    name: "Value Entries",
    bcEndpoint: "valueEntries",
    supabaseTable: "bcValueEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcValueEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcValueEntryEntryNo",
      itemNo: "bcValueEntryItemNo",
      postingDate: "bcValueEntryPostingDate",
      documentNo: "bcValueEntryDocumentNo",
      documentType: "bcValueEntryDocumentType",
      descriptionValue: "bcValueEntryDescriptionValue",
      locationCode: "bcValueEntryLocationCode",
      valuedQuantity: "bcValueEntryValuedQuantity",
      invoicedQuantity: "bcValueEntryInvoicedQuantity",
      costPerUnit: "bcValueEntryCostPerUnit",
      itemLedgerEntryNo: "bcValueEntryItemLedgerEntryNo",
      itemLedgerEntryType: "bcValueEntryItemLedgerEntryType",
      entryType: "bcValueEntryEntryType",
      salespersPurchCode: "bcValueEntrySalespersPurchCode",
      discountAmount: "bcValueEntryDiscountAmount",
      globalDimension1Code: "bcValueEntryGlobalDimension1Code",
      globalDimension2Code: "bcValueEntryGlobalDimension2Code",
      sourceType: "bcValueEntrySourceType",
      sourceNo: "bcValueEntrySourceNo",
      genProdPostingGroup: "bcValueEntryGenProdPostingGroup",
      orderType: "bcValueEntryOrderType",
      orderNo: "bcValueEntryOrderNo",
      expectedCost: "bcValueEntryExpectedCost",
      createdAt: "bcValueEntryCreatedAt",
      lastModifiedDateTime: "bcValueEntryLastModifiedDateTime",
    },
  },

  // ─── 19. itemLedgerEntries ───
  {
    name: "Item Ledger Entries",
    bcEndpoint: "itemLedgerEntries",
    supabaseTable: "bcItemLedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcItemLedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcItemLedgerEntryEntryNo",
      itemNo: "bcItemLedgerEntryItemNo",
      postingDate: "bcItemLedgerEntryPostingDate",
      entryType: "bcItemLedgerEntryEntryType",
      documentNo: "bcItemLedgerEntryDocumentNo",
      descriptionValue: "bcItemLedgerEntryDescriptionValue",
      locationCode: "bcItemLedgerEntryLocationCode",
      quantityValue: "bcItemLedgerEntryQuantityValue",
      remainingQuantity: "bcItemLedgerEntryRemainingQuantity",
      invoicedQuantity: "bcItemLedgerEntryInvoicedQuantity",
      unitOfMeasureCode: "bcItemLedgerEntryUnitOfMeasureCode",
      globalDimension1Code: "bcItemLedgerEntryGlobalDimension1Code",
      globalDimension2Code: "bcItemLedgerEntryGlobalDimension2Code",
      openValue: "bcItemLedgerEntryOpenValue",
      orderType: "bcItemLedgerEntryOrderType",
      orderNo: "bcItemLedgerEntryOrderNo",
      orderLineNo: "bcItemLedgerEntryOrderLineNo",
      itemDescription: "bcItemLedgerEntryItemDescription",
      documentDate: "bcItemLedgerEntryDocumentDate",
      documentType: "bcItemLedgerEntryDocumentType",
      completelyInvoiced: "bcItemLedgerEntryCompletelyInvoiced",
      variantCode: "bcItemLedgerEntryVariantCode",
      serialNo: "bcItemLedgerEntrySerialNo",
      lotNo: "bcItemLedgerEntryLotNo",
      expirationDate: "bcItemLedgerEntryExpirationDate",
      itemCategoryCode: "bcItemLedgerEntryItemCategoryCode",
      sourceNo: "bcItemLedgerEntrySourceNo",
      documentLineNo: "bcItemLedgerEntryDocumentLineNo",
      createdAt: "bcItemLedgerEntryCreatedAt",
      lastModifiedDateTime: "bcItemLedgerEntryLastModifiedDateTime",
    },
  },

  // ─── 20. gLEntries ───
  {
    name: "GL Entries",
    bcEndpoint: "gLEntries",
    supabaseTable: "bcGLEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcGLEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcGLEntryEntryNo",
      gLAccountNo: "bcGLEntryGLAccountNo",
      gLAccountName: "bcGLEntryGLAccountName",
      postingDate: "bcGLEntryPostingDate",
      documentType: "bcGLEntryDocumentType",
      documentNo: "bcGLEntryDocumentNo",
      descriptionValue: "bcGLEntryDescriptionValue",
      amountValue: "bcGLEntryAmountValue",
      debitAmount: "bcGLEntryDebitAmount",
      creditAmount: "bcGLEntryCreditAmount",
      globalDimension1Code: "bcGLEntryGlobalDimension1Code",
      globalDimension2Code: "bcGLEntryGlobalDimension2Code",
      sourceType: "bcGLEntrySourceType",
      sourceNo: "bcGLEntrySourceNo",
      genPostingType: "bcGLEntryGenPostingType",
      genBusPostingGroup: "bcGLEntryGenBusPostingGroup",
      genProdPostingGroup: "bcGLEntryGenProdPostingGroup",
      documentDate: "bcGLEntryDocumentDate",
      externalDocumentNo: "bcGLEntryExternalDocumentNo",
      vATAmount: "bcGLEntryVATAmount",
      createdAt: "bcGLEntryCreatedAt",
      lastModifiedDateTime: "bcGLEntryLastModifiedDateTime",
    },
  },

  // ─── 21. customerLedgerEntries ───
  {
    name: "Customer Ledger Entries",
    bcEndpoint: "customerLedgerEntries",
    supabaseTable: "bcCustomerLedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcCustomerLedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcCustomerLedgerEntryEntryNo",
      customerNo: "bcCustomerLedgerEntryCustomerNo",
      customerName: "bcCustomerLedgerEntryCustomerName",
      postingDate: "bcCustomerLedgerEntryPostingDate",
      documentType: "bcCustomerLedgerEntryDocumentType",
      documentNo: "bcCustomerLedgerEntryDocumentNo",
      description: "bcCustomerLedgerEntryDescription",
      amount: "bcCustomerLedgerEntryAmount",
      amountLCY: "bcCustomerLedgerEntryAmountLCY",
      remainingAmount: "bcCustomerLedgerEntryRemainingAmount",
      remainingAmtLCY: "bcCustomerLedgerEntryRemainingAmtLCY",
      dueDate: "bcCustomerLedgerEntryDueDate",
      openValue: "bcCustomerLedgerEntryOpenValue",
      salesLCY: "bcCustomerLedgerEntrySalesLCY",
      profitLCY: "bcCustomerLedgerEntryProfitLCY",
      salespersonCode: "bcCustomerLedgerEntrySalespersonCode",
      globalDimension1Code: "bcCustomerLedgerEntryGlobalDimension1Code",
      globalDimension2Code: "bcCustomerLedgerEntryGlobalDimension2Code",
      customerPostingGroup: "bcCustomerLedgerEntryCustomerPostingGroup",
      sellToCustomerNo: "bcCustomerLedgerEntrySellToCustomerNo",
      currencyCode: "bcCustomerLedgerEntryCurrencyCode",
      documentDate: "bcCustomerLedgerEntryDocumentDate",
      externalDocumentNo: "bcCustomerLedgerEntryExternalDocumentNo",
      createdAt: "bcCustomerLedgerEntryCreatedAt",
      lastModifiedDateTime: "bcCustomerLedgerEntryLastModifiedDateTime",
    },
  },

  // ─── 22. vendorLedgerEntries ───
  {
    name: "Vendor Ledger Entries",
    bcEndpoint: "vendorLedgerEntries",
    supabaseTable: "bcVendorLedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcVendorLedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcVendorLedgerEntryEntryNo",
      vendorNo: "bcVendorLedgerEntryVendorNo",
      vendorName: "bcVendorLedgerEntryVendorName",
      postingDate: "bcVendorLedgerEntryPostingDate",
      documentType: "bcVendorLedgerEntryDocumentType",
      documentNo: "bcVendorLedgerEntryDocumentNo",
      description: "bcVendorLedgerEntryDescription",
      amount: "bcVendorLedgerEntryAmount",
      amountLCY: "bcVendorLedgerEntryAmountLCY",
      remainingAmount: "bcVendorLedgerEntryRemainingAmount",
      remainingAmtLCY: "bcVendorLedgerEntryRemainingAmtLCY",
      dueDate: "bcVendorLedgerEntryDueDate",
      openValue: "bcVendorLedgerEntryOpenValue",
      purchaseLCY: "bcVendorLedgerEntryPurchaseLCY",
      purchaserCode: "bcVendorLedgerEntryPurchaserCode",
      globalDimension1Code: "bcVendorLedgerEntryGlobalDimension1Code",
      globalDimension2Code: "bcVendorLedgerEntryGlobalDimension2Code",
      vendorPostingGroup: "bcVendorLedgerEntryVendorPostingGroup",
      buyFromVendorNo: "bcVendorLedgerEntryBuyFromVendorNo",
      currencyCode: "bcVendorLedgerEntryCurrencyCode",
      documentDate: "bcVendorLedgerEntryDocumentDate",
      externalDocumentNo: "bcVendorLedgerEntryExternalDocumentNo",
      createdAt: "bcVendorLedgerEntryCreatedAt",
      lastModifiedDateTime: "bcVendorLedgerEntryLastModifiedDateTime",
    },
  },

  // ─── 23. detailedCustLedgerEntries ───
  {
    name: "Detailed Cust. Ledger Entries",
    bcEndpoint: "detailedCustLedgerEntries",
    supabaseTable: "bcDetailedCustLedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcDetailedCustLedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcDetailedCustLedgerEntryEntryNo",
      custLedgerEntryNo: "bcDetailedCustLedgerEntryCustLedgerEntryNo",
      entryType: "bcDetailedCustLedgerEntryEntryType",
      postingDate: "bcDetailedCustLedgerEntryPostingDate",
      documentType: "bcDetailedCustLedgerEntryDocumentType",
      documentNo: "bcDetailedCustLedgerEntryDocumentNo",
      amount: "bcDetailedCustLedgerEntryAmount",
      amountLCY: "bcDetailedCustLedgerEntryAmountLCY",
      customerNo: "bcDetailedCustLedgerEntryCustomerNo",
      currencyCode: "bcDetailedCustLedgerEntryCurrencyCode",
      debitAmount: "bcDetailedCustLedgerEntryDebitAmount",
      creditAmount: "bcDetailedCustLedgerEntryCreditAmount",
      initialEntryDueDate: "bcDetailedCustLedgerEntryInitialEntryDueDate",
      initialEntryGlobalDim1: "bcDetailedCustLedgerEntryInitialEntryGlobalDim1",
      initialEntryGlobalDim2: "bcDetailedCustLedgerEntryInitialEntryGlobalDim2",
      initialDocumentType: "bcDetailedCustLedgerEntryInitialDocumentType",
      appliedCustLedgerEntryNo: "bcDetailedCustLedgerEntryAppliedCustLedgerEntryNo",
      unapplied: "bcDetailedCustLedgerEntryUnapplied",
      createdAt: "bcDetailedCustLedgerEntryCreatedAt",
      lastModifiedDateTime: "bcDetailedCustLedgerEntryLastModifiedDateTime",
    },
  },

  // ─── 24. detailedVendorLedgerEntries ───
  {
    name: "Detailed Vendor Ledger Entries",
    bcEndpoint: "detailedVendorLedgerEntries",
    supabaseTable: "bcDetailedVendorLedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcDetailedVendorLedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcDetailedVendorLedgerEntryEntryNo",
      vendorLedgerEntryNo: "bcDetailedVendorLedgerEntryVendorLedgerEntryNo",
      entryType: "bcDetailedVendorLedgerEntryEntryType",
      postingDate: "bcDetailedVendorLedgerEntryPostingDate",
      documentType: "bcDetailedVendorLedgerEntryDocumentType",
      documentNo: "bcDetailedVendorLedgerEntryDocumentNo",
      amount: "bcDetailedVendorLedgerEntryAmount",
      amountLCY: "bcDetailedVendorLedgerEntryAmountLCY",
      vendorNo: "bcDetailedVendorLedgerEntryVendorNo",
      currencyCode: "bcDetailedVendorLedgerEntryCurrencyCode",
      debitAmount: "bcDetailedVendorLedgerEntryDebitAmount",
      creditAmount: "bcDetailedVendorLedgerEntryCreditAmount",
      initialEntryDueDate: "bcDetailedVendorLedgerEntryInitialEntryDueDate",
      initialEntryGlobalDim1: "bcDetailedVendorLedgerEntryInitialEntryGlobalDim1",
      initialEntryGlobalDim2: "bcDetailedVendorLedgerEntryInitialEntryGlobalDim2",
      initialDocumentType: "bcDetailedVendorLedgerEntryInitialDocumentType",
      appliedVendLedgerEntryNo: "bcDetailedVendorLedgerEntryAppliedVendLedgerEntryNo",
      unapplied: "bcDetailedVendorLedgerEntryUnapplied",
      createdAt: "bcDetailedVendorLedgerEntryCreatedAt",
      lastModifiedDateTime: "bcDetailedVendorLedgerEntryLastModifiedDateTime",
    },
  },

  // ─── 25. bankAccountLedgerEntries ───
  {
    name: "Bank Account Ledger Entries",
    bcEndpoint: "bankAccountLedgerEntries",
    supabaseTable: "bcBankAccountLedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcBankAccountLedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcBankAccountLedgerEntryEntryNo",
      bankAccountNo: "bcBankAccountLedgerEntryBankAccountNo",
      postingDate: "bcBankAccountLedgerEntryPostingDate",
      documentType: "bcBankAccountLedgerEntryDocumentType",
      documentNo: "bcBankAccountLedgerEntryDocumentNo",
      description: "bcBankAccountLedgerEntryDescription",
      amount: "bcBankAccountLedgerEntryAmount",
      remainingAmount: "bcBankAccountLedgerEntryRemainingAmount",
      amountLCY: "bcBankAccountLedgerEntryAmountLCY",
      debitAmount: "bcBankAccountLedgerEntryDebitAmount",
      creditAmount: "bcBankAccountLedgerEntryCreditAmount",
      globalDimension1Code: "bcBankAccountLedgerEntryGlobalDimension1Code",
      globalDimension2Code: "bcBankAccountLedgerEntryGlobalDimension2Code",
      openValue: "bcBankAccountLedgerEntryOpenValue",
      currencyCode: "bcBankAccountLedgerEntryCurrencyCode",
      documentDate: "bcBankAccountLedgerEntryDocumentDate",
      externalDocumentNo: "bcBankAccountLedgerEntryExternalDocumentNo",
      statementStatus: "bcBankAccountLedgerEntryStatementStatus",
      createdAt: "bcBankAccountLedgerEntryCreatedAt",
      lastModifiedDateTime: "bcBankAccountLedgerEntryLastModifiedDateTime",
    },
  },

  // ─── 26. faLedgerEntries ───
  {
    name: "FA Ledger Entries",
    bcEndpoint: "faLedgerEntries",
    supabaseTable: "bcFALedgerEntry",
    bcPrimaryKey: "entryNo",
    supabaseConflictCol: "bcFALedgerEntryEntryNo",
    syncGroup: "ledger",
    incrementalFilter: (_lastSync, lastEntryNo) =>
      `entryNo gt ${lastEntryNo}`,
    fieldMap: {
      entryNo: "bcFALedgerEntryEntryNo",
      fANo: "bcFALedgerEntryFANo",
      fAPostingDate: "bcFALedgerEntryFAPostingDate",
      postingDate: "bcFALedgerEntryPostingDate",
      documentType: "bcFALedgerEntryDocumentType",
      documentNo: "bcFALedgerEntryDocumentNo",
      description: "bcFALedgerEntryDescription",
      fAPostingType: "bcFALedgerEntryFAPostingType",
      amount: "bcFALedgerEntryAmount",
      debitAmount: "bcFALedgerEntryDebitAmount",
      creditAmount: "bcFALedgerEntryCreditAmount",
      depreciationBookCode: "bcFALedgerEntryDepreciationBookCode",
      globalDimension1Code: "bcFALedgerEntryGlobalDimension1Code",
      globalDimension2Code: "bcFALedgerEntryGlobalDimension2Code",
      noOfDepreciationDays: "bcFALedgerEntryNoOfDepreciationDays",
      fAClassCode: "bcFALedgerEntryFAClassCode",
      createdAt: "bcFALedgerEntryCreatedAt",
      lastModifiedDateTime: "bcFALedgerEntryLastModifiedDateTime",
    },
  },
];

// Helper to get all tables that need to be truncated in full sync
export function getAllSupabaseTables() {
  const tables = [];
  for (const cfg of bcSyncConfig) {
    if (cfg.supabaseTable) tables.push(cfg.supabaseTable);
    if (cfg.linesTable) tables.push(cfg.linesTable);
  }
  return tables;
}

// Helper to get configs by sync group
export function getConfigsByGroup(group) {
  return bcSyncConfig.filter((c) => c.syncGroup === group);
}

// Date field names that need null-coercion
const DATE_FIELDS = new Set([
  "orderDate", "dueDate", "postingDate", "documentDate", "shipmentDate",
  "creationDate", "finishedDate", "warrantyDate", "lastDateModified",
  "expirationDate", "fAPostingDate", "requestedDeliveryDate",
  "promisedDeliveryDate", "lastShipmentDate", "expectedReceiptDate",
  "quoteValidUntilDate", "quoteAcceptedDate", "initialEntryDueDate",
  "plannedDeliveryDate", "plannedShipmentDate",
]);

const TIMESTAMP_FIELDS = new Set([
  "startingDateTime", "endingDateTime", "createdAt", "lastModifiedDateTime",
]);

export function bcDate(val) {
  if (!val || val === "0001-01-01") return null;
  return val;
}

export function bcTimestamp(val) {
  if (!val || val.startsWith("0001-01-01")) return null;
  return val;
}

// Transform a BC record using a fieldMap, handling date/timestamp coercion
export function transformRecord(record, fieldMap) {
  const row = {};
  for (const [bcField, supaCol] of Object.entries(fieldMap)) {
    if (!supaCol) continue; // skip null mappings (e.g. dimensionValues)
    const val = record[bcField];
    if (DATE_FIELDS.has(bcField)) {
      row[supaCol] = bcDate(val);
    } else if (TIMESTAMP_FIELDS.has(bcField)) {
      row[supaCol] = bcTimestamp(val);
    } else {
      row[supaCol] = val ?? null;
    }
  }
  return row;
}
