import {
  Key,
  LayoutDashboard,
  User,
  Computer,
  DollarSign,
  ShoppingCart,
  Megaphone,
  Settings,
  Package,
  Factory,
  BadgeCheck,
  Lightbulb,
  HeadphonesIcon,
  Truck,
  TrendingUp,
  FileText,
  Users,
  Briefcase,
  Calendar,
  Wallet,
  Receipt,
  BarChart3,
  Target,
  Mail,
  Globe,
  Boxes,
  ScanLine,
  ClipboardList,
  Wrench,
  Phone,
  MessageCircle,
  MapPin,
  Scale,
  FileCheck,
  List,
  Search,
  PieChart,
  CreditCard,
  Server,
  Shield,
  FlaskConical,
  TrendingDown,
  Lock,
  Zap,
  GitBranch,
  Workflow,
  Home,
  Activity,
  Clock,
  Star,
  Building2,
  AlertTriangle,
  RefreshCw,
  Landmark,
} from "lucide-react";

export const menuData = [
  {
    id: "overview",
    name: "Overview",
    icon: LayoutDashboard,
    href: "/overview/dashboard",
    subMenus: [
      { name: "Overview", icon: Home, href: "/overview/dashboard" },
      { name: "Analytics", icon: BarChart3, href: "/overview/analytics" },
      { name: "Activities", icon: Activity, href: "/overview/activities" },
      { name: "Recent Updates", icon: Clock, href: "/overview/updates" },
      { name: "Favorites", icon: Star, href: "/overview/favorites" },
      { name: "Reports", icon: FileText, href: "/overview/reports" },
    ],
  },
  {
    id: "hr",
    name: "Human Resources",
    icon: User,
    href: "/hr/employees",
    subMenus: [
      { name: "Human Resources", icon: LayoutDashboard, href: "/hr/dashboard" },
      { name: "Employee List", icon: Users, href: "/hr/employees" },
      { name: "Divisions", icon: Building2, href: "/hr/divisions" },
      { name: "Departments", icon: Building2, href: "/hr/departments" },
      { name: "Positions", icon: Briefcase, href: "/hr/positions" },
      { name: "Recruitment", icon: Briefcase },
      { name: "Attendance", icon: Calendar },
      { name: "Payroll", icon: Wallet },
      { name: "Performance", icon: Target },
    ],
  },
  {
    id: "it",
    name: "Information Technology",
    icon: Computer,
    href: "/it/dashboard",
    subMenus: [
      { name: "IT Dashboard", icon: LayoutDashboard, href: "/it/dashboard" },
      { name: "Assets", icon: Server, href: "/it/assets" },
      { name: "Help Desk", icon: HeadphonesIcon, href: "/it/helpdesk" },
      { name: "System Access", icon: Shield, href: "/it/systemAccess" },
      { name: "Network", icon: Globe, href: "/it/network" },
      { name: "Software", icon: FileText, href: "/it/software" },
      { name: "Security", icon: Lock, href: "/it/security" },
      { name: "Development", icon: GitBranch, href: "/it/development" },
    ],
  },
  {
    id: "finance",
    name: "Finance & Accounting",
    icon: DollarSign,
    subMenus: [
      { name: "General Ledger", icon: FileText },
      { name: "Accounts Payable", icon: Receipt },
      { name: "Accounts Receivable", icon: CreditCard },
      { name: "Budget", icon: PieChart },
      { name: "Financial Reports", icon: BarChart3 },
      { name: "Tax", icon: FileCheck },
    ],
  },
  {
    id: "sales",
    name: "Sales",
    icon: TrendingUp,
    href: "/sales/dashboard",
    subMenus: [
      { name: "Dashboard", icon: LayoutDashboard, href: "/sales/dashboard" },
      { name: "Leads", icon: Target, href: "/sales/leads" },
      { name: "Contacts", icon: Users, href: "/sales/contacts" },
      { name: "Accounts", icon: Building2, href: "/sales/accounts" },
      { name: "Opportunities", icon: Briefcase, href: "/sales/opportunities" },
      { name: "Quotations", icon: FileText, href: "/sales/quotations" },
      { name: "Orders", icon: ShoppingCart, href: "/sales/orders" },
      { name: "Activities", icon: Calendar, href: "/sales/activities" },
      { name: "Reports", icon: BarChart3, href: "/sales/reports" },
      { name: "BCI Projects", icon: Landmark, href: "/sales/bci-projects" },
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    icon: Megaphone,
    href: "/marketing/omnichannel",
    subMenus: [
      { name: "Analytics", icon: BarChart3, href: "/marketing/analytics" },
      {
        name: "Sales Orders",
        icon: ShoppingCart,
        href: "/marketing/salesOrders",
      },
      {
        name: "Quotation",
        icon: FileText,
        href: "/marketing/omnichannel/quotations",
      },
      {
        name: "Price List",
        icon: Package,
        href: "/marketing/omnichannel/stockItems",
      },
      {
        name: "Omnichannel Chat",
        icon: MessageCircle,
        href: "/marketing/omnichannel",
      },
      { name: "Campaigns", icon: Target },
      { name: "Social Media", icon: Globe },
      { name: "Email Marketing", icon: Mail },
      { name: "Events", icon: Calendar },
      { name: "Content", icon: FileText },
    ],
  },
  {
    id: "operations",
    name: "Operations",
    icon: Settings,
    subMenus: [
      { name: "Process Management", icon: ClipboardList },
      { name: "Resource Planning", icon: Calendar },
      { name: "KPI Dashboard", icon: BarChart3 },
      { name: "Workflow", icon: List },
      { name: "Reports", icon: FileText },
      { name: "Audit", icon: FileCheck },
    ],
  },
  {
    id: "procurement",
    name: "Procurement",
    icon: ShoppingCart,
    subMenus: [
      { name: "Purchase Requests", icon: FileText },
      { name: "Purchase Orders", icon: ClipboardList },
      { name: "Vendors", icon: Users },
      { name: "Contracts", icon: FileCheck },
      { name: "Negotiations", icon: Target },
      { name: "Spend Analysis", icon: PieChart },
    ],
  },
  {
    id: "production",
    name: "Production",
    icon: Factory,
    subMenus: [
      { name: "Production Plan", icon: Calendar },
      { name: "Work Orders", icon: ClipboardList },
      { name: "BOM", icon: List },
      { name: "Machine Status", icon: Settings },
      { name: "Efficiency", icon: TrendingUp },
      { name: "Maintenance", icon: Wrench },
    ],
  },
  {
    id: "qa",
    name: "Quality Assurance",
    icon: BadgeCheck,
    subMenus: [
      { name: "Inspections", icon: ScanLine },
      { name: "Test Reports", icon: FileText },
      { name: "NCR", icon: AlertTriangle },
      { name: "CAPA", icon: Target },
      { name: "Standards", icon: FileCheck },
      { name: "Audits", icon: Shield },
    ],
  },
  {
    id: "rnd",
    name: "R&D",
    icon: Lightbulb,
    subMenus: [
      { name: "Projects", icon: Briefcase },
      { name: "Experiments", icon: FlaskConical },
      { name: "Prototypes", icon: Settings },
      { name: "Patents", icon: FileCheck },
      { name: "Research", icon: Search },
      { name: "Innovation", icon: Lightbulb },
    ],
  },
  {
    id: "cs",
    name: "Customer Service",
    icon: HeadphonesIcon,
    subMenus: [
      { name: "Tickets", icon: ClipboardList },
      { name: "Call Center", icon: Phone },
      { name: "Live Chat", icon: MessageCircle },
      { name: "Feedback", icon: FileText },
      { name: "FAQ", icon: List },
      { name: "SLA", icon: Target },
    ],
  },
  {
    id: "logistics",
    name: "ระบบขนส่ง",
    icon: Truck,
    href: "/tms/dashboard",
    subMenus: [
      { name: "แดชบอร์ด", icon: LayoutDashboard, href: "/tms/dashboard" },
      { name: "ยานพาหนะ", icon: Truck, href: "/tms/vehicles" },
      { name: "พนักงานขับรถ", icon: Users, href: "/tms/drivers" },
      { name: "การขนส่ง", icon: Package, href: "/tms/shipments" },
      { name: "เส้นทาง", icon: MapPin, href: "/tms/routes" },
      { name: "การจัดส่ง", icon: FileCheck, href: "/tms/deliveries" },
      { name: "บันทึกน้ำมัน", icon: Boxes, href: "/tms/fuelLogs" },
      { name: "ซ่อมบำรุง", icon: Wrench, href: "/tms/maintenance" },
      { name: "ติดตาม GPS", icon: MapPin, href: "/tms/tracking" },
      { name: "รายงาน", icon: BarChart3, href: "/tms/reports" },
      {
        name: "การแจ้งเตือน",
        icon: AlertTriangle,
        href: "/tms/alerts",
        badgeKey: "tmsAlertCount",
      },
    ],
  },
  {
    id: "warehouse",
    name: "Warehouse",
    icon: Package,
    href: "/warehouse/inventory",
    subMenus: [
      { name: "ภาพรวมคลัง", icon: Boxes, href: "/warehouse/inventory" },
      { name: "ตั้งค่าเครื่องพิมพ์", icon: Settings, href: "/warehouse/printer-config" },
    ],
  },
  {
    id: "legal",
    name: "Legal & Compliance",
    icon: FileText,
    subMenus: [
      { name: "Contracts", icon: FileCheck },
      { name: "Regulations", icon: Scale },
      { name: "Policies", icon: FileText },
      { name: "Litigation", icon: Shield },
      { name: "Compliance", icon: BadgeCheck },
      { name: "Risk", icon: TrendingDown },
    ],
  },
  {
    id: "bc",
    name: "365 Business Central",
    icon: Building2,
    href: "/bc/customers",
    subMenus: [
      { name: "Customers", icon: Users, href: "/bc/customers" },
      { name: "Items", icon: Package, href: "/bc/items" },
      { name: "Sales Orders", icon: ShoppingCart, href: "/bc/salesOrders" },
    ],
  },
  {
    id: "settings",
    name: "Settings",
    icon: Settings,
    href: "/settings/configCheck",
    subMenus: [
      { name: "Config Check", icon: Activity, href: "/settings/configCheck" },
      { name: "Sync BC", icon: RefreshCw, href: "/settings/sync-bc" },
    ],
  },
  {
    id: "rbac",
    name: "Access Control",
    icon: Shield,
    href: "/rbac/roles",
    subMenus: [
      { name: "Roles", icon: Key, href: "/rbac/roles" },
      { name: "Users", icon: Users, href: "/rbac/users" },
      { name: "Resources", icon: Server, href: "/rbac/resources" },
      { name: "Actions", icon: Zap, href: "/rbac/actions" },
      { name: "Permissions", icon: Lock, href: "/rbac/permissions" },
      {
        name: "Approval Hierarchy",
        icon: GitBranch,
        href: "/rbac/approvalHierarchy",
      },
      {
        name: "Approval Workflows",
        icon: Workflow,
        href: "/rbac/approvalWorkflows",
      },
      { name: "Access Logs", icon: FileText, href: "/rbac/accessLogs" },
    ],
  },
];

export function findActiveMenuByPathname(pathname) {
  return (
    menuData.find((menu) => {
      if (menu.href && pathname.startsWith(menu.href)) return true;
      if (menu.subMenus) {
        return menu.subMenus.some(
          (sub) => sub.href && pathname.startsWith(sub.href),
        );
      }
      return false;
    }) || menuData[0]
  );
}
