import {
  Key,
  LayoutDashboard,
  User,
  Computer,
  DollarSign,
  ShoppingCart,
  Megaphone,
  Settings,
  Package,
  Factory,
  BadgeCheck,
  Lightbulb,
  HeadphonesIcon,
  Truck,
  TrendingUp,
  FileText,
  Users,
  Briefcase,
  Calendar,
  Wallet,
  Receipt,
  BarChart3,
  Target,
  Mail,
  Globe,
  Boxes,
  ScanLine,
  ClipboardList,
  Wrench,
  Phone,
  MessageCircle,
  MapPin,
  Scale,
  FileCheck,
  List,
  Search,
  PieChart,
  CreditCard,
  Server,
  Shield,
  FlaskConical,
  TrendingDown,
  Lock,
  Zap,
  GitBranch,
  Workflow,
  Home,
  Activity,
  Clock,
  Star,
  Building2,
  AlertTriangle,
  RefreshCw,
  Landmark,
  Printer,
} from "lucide-react";

export const menuData = [
  {
    id: "overview",
    name: "ภาพรวม",
    icon: LayoutDashboard,
    href: "/overview/dashboard",
    subMenus: [
      { name: "ภาพรวม", icon: Home, href: "/overview/dashboard" },
      { name: "วิเคราะห์", icon: BarChart3, href: "/overview/analytics" },
      { name: "กิจกรรม", icon: Activity, href: "/overview/activities" },
      { name: "อัปเดตล่าสุด", icon: Clock, href: "/overview/updates" },
      { name: "รายการโปรด", icon: Star, href: "/overview/favorites" },
      { name: "รายงาน", icon: FileText, href: "/overview/reports" },
    ],
  },
  {
    id: "hr",
    name: "ทรัพยากรบุคคล",
    icon: User,
    href: "/hr/employees",
    subMenus: [
      { name: "ทรัพยากรบุคคล", icon: LayoutDashboard, href: "/hr/dashboard" },
      { name: "รายชื่อพนักงาน", icon: Users, href: "/hr/employees" },
      { name: "ฝ่าย", icon: Building2, href: "/hr/divisions" },
      { name: "แผนก", icon: Building2, href: "/hr/departments" },
      { name: "ตำแหน่ง", icon: Briefcase, href: "/hr/positions" },
      { name: "สรรหาบุคลากร", icon: Briefcase },
      { name: "การลงเวลา", icon: Calendar },
      { name: "เงินเดือน", icon: Wallet },
    ],
  },
  {
    id: "performance",
    name: "ผลการปฏิบัติงาน",
    icon: Target,
    href: "/performance/evaluation",
    subMenus: [
      {
        name: "ประเมินค่านิยม",
        icon: ClipboardList,
        href: "/performance/evaluation",
      },
      { name: "OKR", icon: Target, href: "/performance/okr" },
      { name: "KPI", icon: BarChart3, href: "/performance/kpi" },
      { name: "ประเมิน 360 องศา", icon: RefreshCw, href: "/performance/360" },
    ],
  },
  {
    id: "it",
    name: "เทคโนโลยีสารสนเทศ",
    icon: Computer,
    href: "/it/dashboard",
    subMenus: [
      { name: "แดชบอร์ด IT", icon: LayoutDashboard, href: "/it/dashboard" },
      { name: "ทรัพย์สิน", icon: Server, href: "/it/assets" },
      { name: "ศูนย์ช่วยเหลือ", icon: HeadphonesIcon, href: "/it/helpdesk" },
      { name: "การเข้าถึงระบบ", icon: Shield, href: "/it/systemAccess" },
      { name: "เครือข่าย", icon: Globe, href: "/it/network" },
      { name: "ซอฟต์แวร์", icon: FileText, href: "/it/software" },
      { name: "ความปลอดภัย", icon: Lock, href: "/it/security" },
      { name: "พัฒนาระบบ", icon: GitBranch, href: "/it/development" },
    ],
  },
  {
    id: "finance",
    name: "การเงินและบัญชี",
    icon: DollarSign,
    subMenus: [
      { name: "บัญชีแยกประเภท", icon: FileText },
      { name: "เจ้าหนี้", icon: Receipt },
      { name: "ลูกหนี้", icon: CreditCard },
      { name: "งบประมาณ", icon: PieChart },
      { name: "รายงานการเงิน", icon: BarChart3 },
      { name: "ภาษี", icon: FileCheck },
    ],
  },
  {
    id: "sales",
    name: "การขาย",
    icon: TrendingUp,
    href: "/sales/dashboard",
    subMenus: [
      { name: "แดชบอร์ด", icon: LayoutDashboard, href: "/sales/dashboard" },
      { name: "ลีด", icon: Target, href: "/sales/leads" },
      { name: "ผู้ติดต่อ", icon: Users, href: "/sales/contacts" },
      { name: "บัญชีลูกค้า", icon: Building2, href: "/sales/accounts" },
      { name: "โอกาสขาย", icon: Briefcase, href: "/sales/opportunities" },
      { name: "ใบเสนอราคา", icon: FileText, href: "/sales/quotations" },
      { name: "คำสั่งซื้อ", icon: ShoppingCart, href: "/sales/orders" },
      { name: "กิจกรรม", icon: Calendar, href: "/sales/activities" },
      { name: "รายงาน", icon: BarChart3, href: "/sales/reports" },
      { name: "โปรเจค BCI", icon: Landmark, href: "/sales/bci-projects" },
    ],
  },
  {
    id: "marketing",
    name: "การตลาด",
    icon: Megaphone,
    href: "/marketing/omnichannel",
    subMenus: [
      { name: "วิเคราะห์", icon: BarChart3, href: "/marketing/analytics" },
      {
        name: "คำสั่งขาย",
        icon: ShoppingCart,
        href: "/marketing/salesOrders",
      },
      {
        name: "ใบเสนอราคา",
        icon: FileText,
        href: "/marketing/omnichannel/quotations",
      },
      {
        name: "รายการราคา",
        icon: Package,
        href: "/marketing/omnichannel/stockItems",
      },
      {
        name: "แชทรวมช่องทาง",
        icon: MessageCircle,
        href: "/marketing/omnichannel",
      },
      { name: "แคมเปญ", icon: Target },
      { name: "โซเชียลมีเดีย", icon: Globe },
      { name: "อีเมลมาร์เก็ตติ้ง", icon: Mail },
      { name: "อีเวนต์", icon: Calendar },
      { name: "คอนเทนต์", icon: FileText },
    ],
  },
  {
    id: "operations",
    name: "ปฏิบัติการ",
    icon: Settings,
    subMenus: [
      { name: "จัดการกระบวนการ", icon: ClipboardList },
      { name: "วางแผนทรัพยากร", icon: Calendar },
      { name: "แดชบอร์ด KPI", icon: BarChart3 },
      { name: "เวิร์กโฟลว์", icon: List },
      { name: "รายงาน", icon: FileText },
      { name: "ตรวจสอบ", icon: FileCheck },
    ],
  },
  {
    id: "procurement",
    name: "จัดซื้อจัดจ้าง",
    icon: ShoppingCart,
    subMenus: [
      { name: "ใบขอซื้อ", icon: FileText },
      { name: "ใบสั่งซื้อ", icon: ClipboardList },
      { name: "ผู้ขาย", icon: Users },
      { name: "สัญญา", icon: FileCheck },
      { name: "การเจรจา", icon: Target },
      { name: "วิเคราะห์การใช้จ่าย", icon: PieChart },
    ],
  },
  {
    id: "production",
    name: "การผลิต",
    icon: Factory,
    href: "/production/dashboard",
    subMenus: [
      {
        name: "แดชบอร์ด",
        icon: LayoutDashboard,
        href: "/production/dashboard",
      },
      { name: "เบิก/ผลิตรายวัน", icon: Calendar, href: "/production/daily" },
      { name: "ใบสั่งผลิต", icon: ClipboardList, href: "/production/orders" },
      { name: "แผนการผลิต", icon: FileText },

      { name: "BOM", icon: List },
      { name: "สถานะเครื่องจักร", icon: Settings },
      { name: "ประสิทธิภาพ", icon: TrendingUp },
      { name: "ซ่อมบำรุง", icon: Wrench },
    ],
  },
  {
    id: "qa",
    name: "ประกันคุณภาพ",
    icon: BadgeCheck,
    subMenus: [
      { name: "ตรวจสอบ", icon: ScanLine },
      { name: "รายงานทดสอบ", icon: FileText },
      { name: "NCR", icon: AlertTriangle },
      { name: "CAPA", icon: Target },
      { name: "มาตรฐาน", icon: FileCheck },
      { name: "การตรวจสอบ", icon: Shield },
    ],
  },
  {
    id: "rnd",
    name: "วิจัยและพัฒนา",
    icon: Lightbulb,
    subMenus: [
      { name: "โปรเจค", icon: Briefcase },
      { name: "การทดลอง", icon: FlaskConical },
      { name: "ต้นแบบ", icon: Settings },
      { name: "สิทธิบัตร", icon: FileCheck },
      { name: "วิจัย", icon: Search },
      { name: "นวัตกรรม", icon: Lightbulb },
    ],
  },
  {
    id: "cs",
    name: "บริการลูกค้า",
    icon: HeadphonesIcon,
    subMenus: [
      { name: "ตั๋วแจ้งปัญหา", icon: ClipboardList },
      { name: "คอลเซ็นเตอร์", icon: Phone },
      { name: "แชทสด", icon: MessageCircle },
      { name: "ความคิดเห็น", icon: FileText },
      { name: "คำถามที่พบบ่อย", icon: List },
      { name: "SLA", icon: Target },
    ],
  },
  {
    id: "logistics",
    name: "ระบบขนส่ง",
    icon: Truck,
    href: "/tms/dashboard",
    subMenus: [
      { name: "แดชบอร์ด", icon: LayoutDashboard, href: "/tms/dashboard" },
      { name: "ยานพาหนะ", icon: Truck, href: "/tms/vehicles" },
      { name: "พนักงานขับรถ", icon: Users, href: "/tms/drivers" },
      { name: "การขนส่ง", icon: Package, href: "/tms/shipments" },
      { name: "เส้นทาง", icon: MapPin, href: "/tms/routes" },
      { name: "การจัดส่ง", icon: FileCheck, href: "/tms/deliveries" },
      { name: "บันทึกน้ำมัน", icon: Boxes, href: "/tms/fuelLogs" },
      { name: "ซ่อมบำรุง", icon: Wrench, href: "/tms/maintenance" },
      { name: "ติดตาม GPS", icon: MapPin, href: "/tms/tracking" },
      { name: "รายงาน", icon: BarChart3, href: "/tms/reports" },
      {
        name: "การแจ้งเตือน",
        icon: AlertTriangle,
        href: "/tms/alerts",
        badgeKey: "tmsAlertCount",
      },
    ],
  },
  {
    id: "warehouse",
    name: "คลังสินค้า",
    icon: Package,
    href: "/warehouse/inventory",
    subMenus: [
      { name: "ภาพรวมคลัง", icon: Boxes, href: "/warehouse/inventory" },
    ],
  },
  {
    id: "legal",
    name: "กฎหมายและกำกับดูแล",
    icon: FileText,
    subMenus: [
      { name: "สัญญา", icon: FileCheck },
      { name: "กฎระเบียบ", icon: Scale },
      { name: "นโยบาย", icon: FileText },
      { name: "คดีความ", icon: Shield },
      { name: "การปฏิบัติตาม", icon: BadgeCheck },
      { name: "ความเสี่ยง", icon: TrendingDown },
    ],
  },
  {
    id: "bc",
    name: "365 Business Central",
    icon: Building2,
    href: "/bc/customers",
    subMenus: [
      { name: "ลูกค้า", icon: Users, href: "/bc/customers" },
      { name: "สินค้า", icon: Package, href: "/bc/items" },
      { name: "คำสั่งขาย", icon: ShoppingCart, href: "/bc/salesOrders" },
      {
        name: "เคลื่อนไหวสินค้า",
        icon: ClipboardList,
        href: "/bc/itemLedgerEntries",
      },
    ],
  },
  {
    id: "settings",
    name: "ตั้งค่า",
    icon: Settings,
    href: "/settings/configCheck",
    subMenus: [
      {
        name: "ตรวจสอบการตั้งค่า",
        icon: Activity,
        href: "/settings/configCheck",
      },
      { name: "ซิงค์ BC", icon: RefreshCw, href: "/settings/sync-bc" },
      { name: "เครื่องพิมพ์", icon: Printer, href: "/settings/printer-config" },
    ],
  },
  {
    id: "rbac",
    name: "ควบคุมการเข้าถึง",
    icon: Shield,
    href: "/rbac/roles",
    subMenus: [
      { name: "บทบาท", icon: Key, href: "/rbac/roles" },
      { name: "ผู้ใช้", icon: Users, href: "/rbac/users" },
      { name: "ทรัพยากร", icon: Server, href: "/rbac/resources" },
      { name: "การดำเนินการ", icon: Zap, href: "/rbac/actions" },
      { name: "สิทธิ์", icon: Lock, href: "/rbac/permissions" },
      {
        name: "ลำดับการอนุมัติ",
        icon: GitBranch,
        href: "/rbac/approvalHierarchy",
      },
      {
        name: "เวิร์กโฟลว์อนุมัติ",
        icon: Workflow,
        href: "/rbac/approvalWorkflows",
      },
      { name: "บันทึกการเข้าถึง", icon: FileText, href: "/rbac/accessLogs" },
    ],
  },
];

export function findActiveMenuByPathname(pathname) {
  return (
    menuData.find((menu) => {
      if (menu.href && pathname.startsWith(menu.href)) return true;
      if (menu.subMenus) {
        return menu.subMenus.some(
          (sub) => sub.href && pathname.startsWith(sub.href),
        );
      }
      return false;
    }) || menuData[0]
  );
}
