package bc

import "strings"

// EntityConfig describes one BC entity to sync into Supabase.
type EntityConfig struct {
	Name                  string
	BCEndpoint            string
	SupabaseTable         string // "" if not stored (e.g. dimensionValues)
	BCPrimaryKey          string // "" if none
	SupabaseConflictCol   string
	LinesEndpoint         string // "" if no child lines
	LinesTable            string
	LinesConflictCols     string
	SyncGroup             string
	IncrementalFilterType string // "timestamp", "entryNo", or ""
	FieldMap              map[string]string
	LineFieldMap          map[string]string // nil if no child lines
}

// SyncConfig contains all 26 BC entities to sync.
var SyncConfig = []EntityConfig{
	// ─── 1. dimensionValues (NOT stored in Supabase — used to build dimMap in memory) ───
	{
		Name:                  "Dimension Values",
		BCEndpoint:            "dimensionValues",
		SupabaseTable:         "",
		BCPrimaryKey:          "",
		SupabaseConflictCol:   "",
		SyncGroup:             "master",
		IncrementalFilterType: "",
		FieldMap: map[string]string{
			"dimensionCode": "",
			"codeValue":     "",
			"nameValue":     "",
		},
	},

	// ─── 2. customers ───
	{
		Name:                  "Customers",
		BCEndpoint:            "customers",
		SupabaseTable:         "bcCustomer",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcCustomerNo",
		SyncGroup:             "master",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                   "bcCustomerNo",
			"nameValue":            "bcCustomerNameValue",
			"address":              "bcCustomerAddress",
			"address2":             "bcCustomerAddress2",
			"city":                 "bcCustomerCity",
			"postCode":             "bcCustomerPostCode",
			"contact":              "bcCustomerContact",
			"phoneNo":              "bcCustomerPhoneNo",
			"eMail":                "bcCustomerEMail",
			"salespersonCode":      "bcCustomerSalespersonCode",
			"customerPostingGroup": "bcCustomerCustomerPostingGroup",
			"paymentTermsCode":     "bcCustomerPaymentTermsCode",
			"globalDimension1Code": "bcCustomerGlobalDimension1Code",
			"globalDimension2Code": "bcCustomerGlobalDimension2Code",
			"creditLimitLCY":       "bcCustomerCreditLimitLCY",
			"balanceLCY":           "bcCustomerBalanceLCY",
			"balanceDueLCY":        "bcCustomerBalanceDueLCY",
			"outstandingOrders":    "bcCustomerOutstandingOrders",
			"shippedNotInvoiced":   "bcCustomerShippedNotInvoiced",
			"blocked":              "bcCustomerBlocked",
			"vATRegistrationNo":    "bcCustomerVATRegistrationNo",
			"paymentMethodCode":    "bcCustomerPaymentMethodCode",
			"genBusPostingGroup":   "bcCustomerGenBusPostingGroup",
			"salesLCY":             "bcCustomerSalesLCY",
			"profitLCY":            "bcCustomerProfitLCY",
			"mobilePhoneNo":        "bcCustomerMobilePhoneNo",
			"countryRegionCode":    "bcCustomerCountryRegionCode",
			"outstandingInvoices":  "bcCustomerOutstandingInvoices",
			"createdAt":            "bcCustomerCreatedAt",
			"lastModifiedDateTime": "bcCustomerLastModifiedDateTime",
		},
	},

	// ─── 3. items ───
	{
		Name:                  "Items",
		BCEndpoint:            "items",
		SupabaseTable:         "bcItem",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcItemNo",
		SyncGroup:             "master",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                    "bcItemNo",
			"description":           "bcItemDescription",
			"description2":          "bcItemDescription2",
			"type":                  "bcItemType",
			"blocked":               "bcItemBlocked",
			"baseUnitOfMeasure":     "bcItemBaseUnitOfMeasure",
			"unitPrice":             "bcItemUnitPrice",
			"unitCost":              "bcItemUnitCost",
			"genProdPostingGroup":   "bcItemGenProdPostingGroup",
			"itemCategoryCode":      "bcItemItemCategoryCode",
			"inventory":             "bcItemInventory",
			"globalDimension1Code":  "bcItemGlobalDimension1Code",
			"globalDimension2Code":  "bcItemGlobalDimension2Code",
			"vendorNo":              "bcItemVendorNo",
			"standardCost":          "bcItemStandardCost",
			"costingMethod":         "bcItemCostingMethod",
			"lastDirectCost":        "bcItemLastDirectCost",
			"inventoryPostingGroup": "bcItemInventoryPostingGroup",
			"grossWeight":           "bcItemGrossWeight",
			"netWeight":             "bcItemNetWeight",
			"productionBOMNo":       "bcItemProductionBOMNo",
			"createdAt":             "bcItemCreatedAt",
			"lastModifiedDateTime":  "bcItemLastModifiedDateTime",
		},
	},

	// ─── 4. salesOrders + salesOrderLines ───
	{
		Name:                  "Sales Orders",
		BCEndpoint:            "salesOrders",
		SupabaseTable:         "bcSalesOrder",
		BCPrimaryKey:          "noValue",
		SupabaseConflictCol:   "bcSalesOrderNoValue",
		LinesEndpoint:         "salesOrderLines",
		LinesTable:            "bcSalesOrderLine",
		LinesConflictCols:     "bcSalesOrderLineDocumentNo,bcSalesOrderLineLineNo",
		SyncGroup:             "document",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"noValue":                "bcSalesOrderNoValue",
			"sellToCustomerNo":       "bcSalesOrderSellToCustomerNo",
			"sellToCustomerName":     "bcSalesOrderSellToCustomerName",
			"sellToAddress":          "bcSalesOrderSellToAddress",
			"sellToAddress2":         "bcSalesOrderSellToAddress2",
			"sellToCity":             "bcSalesOrderSellToCity",
			"sellToPostCode":         "bcSalesOrderSellToPostCode",
			"shipToName":             "bcSalesOrderShipToName",
			"shipToAddress":          "bcSalesOrderShipToAddress",
			"shipToAddress2":         "bcSalesOrderShipToAddress2",
			"shipToCity":             "bcSalesOrderShipToCity",
			"shipToPostCode":         "bcSalesOrderShipToPostCode",
			"orderDate":              "bcSalesOrderOrderDate",
			"dueDate":                "bcSalesOrderDueDate",
			"status":                 "bcSalesOrderStatus",
			"completelyShipped":      "bcSalesOrderCompletelyShipped",
			"salespersonCode":        "bcSalesOrderSalespersonCode",
			"externalDocumentNo":     "bcSalesOrderExternalDocumentNo",
			"locationCode":           "bcSalesOrderLocationCode",
			"shortcutDimension1Code": "bcSalesOrderShortcutDimension1Code",
			"shortcutDimension2Code": "bcSalesOrderShortcutDimension2Code",
			"amountValue":            "bcSalesOrderAmountValue",
			"amountIncludingVAT":     "bcSalesOrderAmountIncludingVAT",
			"assignedUserID":         "bcSalesOrderAssignedUserID",
			"requestedDeliveryDate":  "bcSalesOrderRequestedDeliveryDate",
			"paymentTermsCode":       "bcSalesOrderPaymentTermsCode",
			"paymentMethodCode":      "bcSalesOrderPaymentMethodCode",
			"currencyCode":           "bcSalesOrderCurrencyCode",
			"quoteNo":                "bcSalesOrderQuoteNo",
			"invoiceDiscountAmount":  "bcSalesOrderInvoiceDiscountAmount",
			"postingDate":            "bcSalesOrderPostingDate",
			"documentDate":           "bcSalesOrderDocumentDate",
			"shipmentMethodCode":     "bcSalesOrderShipmentMethodCode",
			"shippingAgentCode":      "bcSalesOrderShippingAgentCode",
			"lastShipmentDate":       "bcSalesOrderLastShipmentDate",
			"promisedDeliveryDate":   "bcSalesOrderPromisedDeliveryDate",
			"sellToPhoneNo":          "bcSalesOrderSellToPhoneNo",
			"sellToEMail":            "bcSalesOrderSellToEMail",
			"noSeries":               "bcSalesOrderNoSeries",
			"currencyFactor":         "bcSalesOrderCurrencyFactor",
			"createdAt":              "bcSalesOrderCreatedAt",
			"lastModifiedDateTime":   "bcSalesOrderLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcSalesOrderLineDocumentNo",
			"lineNo":                 "bcSalesOrderLineLineNo",
			"typeValue":              "bcSalesOrderLineTypeValue",
			"noValue":                "bcSalesOrderLineNoValue",
			"descriptionValue":       "bcSalesOrderLineDescriptionValue",
			"quantityValue":          "bcSalesOrderLineQuantityValue",
			"outstandingQuantity":    "bcSalesOrderLineOutstandingQuantity",
			"quantityShipped":        "bcSalesOrderLineQuantityShipped",
			"unitPrice":              "bcSalesOrderLineUnitPrice",
			"lineDiscount":           "bcSalesOrderLineLineDiscount",
			"lineDiscountAmount":     "bcSalesOrderLineLineDiscountAmount",
			"amountValue":            "bcSalesOrderLineAmountValue",
			"amountIncludingVAT":     "bcSalesOrderLineAmountIncludingVAT",
			"unitOfMeasureCode":      "bcSalesOrderLineUnitOfMeasureCode",
			"locationCode":           "bcSalesOrderLineLocationCode",
			"shortcutDimension1Code": "bcSalesOrderLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcSalesOrderLineShortcutDimension2Code",
			"unitCost":               "bcSalesOrderLineUnitCost",
			"quantityInvoiced":       "bcSalesOrderLineQuantityInvoiced",
			"profit":                 "bcSalesOrderLineProfit",
			"variantCode":            "bcSalesOrderLineVariantCode",
			"itemCategoryCode":       "bcSalesOrderLineItemCategoryCode",
			"genProdPostingGroup":    "bcSalesOrderLineGenProdPostingGroup",
			"shipmentDate":           "bcSalesOrderLineShipmentDate",
			"outstandingAmount":      "bcSalesOrderLineOutstandingAmount",
			"invDiscountAmount":      "bcSalesOrderLineInvDiscountAmount",
			"plannedDeliveryDate":    "bcSalesOrderLinePlannedDeliveryDate",
			"plannedShipmentDate":    "bcSalesOrderLinePlannedShipmentDate",
			"description2":           "bcSalesOrderLineDescription2",
			"vAT":                    "bcSalesOrderLineVAT",
			"lineAmount":             "bcSalesOrderLineLineAmount",
			"qtyToShip":              "bcSalesOrderLineQtyToShip",
			"qtyToInvoice":           "bcSalesOrderLineQtyToInvoice",
			"dropShipment":           "bcSalesOrderLineDropShipment",
			"binCode":                "bcSalesOrderLineBinCode",
			"completelyShipped":      "bcSalesOrderLineCompletelyShipped",
			"createdAt":              "bcSalesOrderLineCreatedAt",
			"lastModifiedDateTime":   "bcSalesOrderLineLastModifiedDateTime",
		},
	},

	// ─── 5. purchaseOrders + purchaseOrderLines ───
	{
		Name:                  "Purchase Orders",
		BCEndpoint:            "purchaseOrders",
		SupabaseTable:         "bcPurchaseOrder",
		BCPrimaryKey:          "noValue",
		SupabaseConflictCol:   "bcPurchaseOrderNoValue",
		LinesEndpoint:         "purchaseOrderLines",
		LinesTable:            "bcPurchaseOrderLine",
		LinesConflictCols:     "bcPurchaseOrderLineDocumentNo,bcPurchaseOrderLineLineNo",
		SyncGroup:             "document",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"noValue":                "bcPurchaseOrderNoValue",
			"buyFromVendorNo":        "bcPurchaseOrderBuyFromVendorNo",
			"buyFromVendorName":      "bcPurchaseOrderBuyFromVendorName",
			"buyFromAddress":         "bcPurchaseOrderBuyFromAddress",
			"buyFromAddress2":        "bcPurchaseOrderBuyFromAddress2",
			"buyFromCity":            "bcPurchaseOrderBuyFromCity",
			"buyFromPostCode":        "bcPurchaseOrderBuyFromPostCode",
			"orderDate":              "bcPurchaseOrderOrderDate",
			"postingDate":            "bcPurchaseOrderPostingDate",
			"expectedReceiptDate":    "bcPurchaseOrderExpectedReceiptDate",
			"dueDate":                "bcPurchaseOrderDueDate",
			"documentDate":           "bcPurchaseOrderDocumentDate",
			"amountValue":            "bcPurchaseOrderAmountValue",
			"amountIncludingVAT":     "bcPurchaseOrderAmountIncludingVAT",
			"purchaserCode":          "bcPurchaseOrderPurchaserCode",
			"shortcutDimension1Code": "bcPurchaseOrderShortcutDimension1Code",
			"shortcutDimension2Code": "bcPurchaseOrderShortcutDimension2Code",
			"locationCode":           "bcPurchaseOrderLocationCode",
			"currencyCode":           "bcPurchaseOrderCurrencyCode",
			"currencyFactor":         "bcPurchaseOrderCurrencyFactor",
			"paymentTermsCode":       "bcPurchaseOrderPaymentTermsCode",
			"paymentMethodCode":      "bcPurchaseOrderPaymentMethodCode",
			"vendorInvoiceNo":        "bcPurchaseOrderVendorInvoiceNo",
			"vendorOrderNo":          "bcPurchaseOrderVendorOrderNo",
			"status":                 "bcPurchaseOrderStatus",
			"completelyReceived":     "bcPurchaseOrderCompletelyReceived",
			"invoiceDiscountAmount":  "bcPurchaseOrderInvoiceDiscountAmount",
			"assignedUserID":         "bcPurchaseOrderAssignedUserID",
			"genBusPostingGroup":     "bcPurchaseOrderGenBusPostingGroup",
			"createdAt":              "bcPurchaseOrderCreatedAt",
			"lastModifiedDateTime":   "bcPurchaseOrderLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcPurchaseOrderLineDocumentNo",
			"lineNo":                 "bcPurchaseOrderLineLineNo",
			"typeValue":              "bcPurchaseOrderLineTypeValue",
			"noValue":                "bcPurchaseOrderLineNoValue",
			"descriptionValue":       "bcPurchaseOrderLineDescriptionValue",
			"description2":           "bcPurchaseOrderLineDescription2",
			"quantityValue":          "bcPurchaseOrderLineQuantityValue",
			"outstandingQuantity":    "bcPurchaseOrderLineOutstandingQuantity",
			"quantityReceived":       "bcPurchaseOrderLineQuantityReceived",
			"quantityInvoiced":       "bcPurchaseOrderLineQuantityInvoiced",
			"directUnitCost":         "bcPurchaseOrderLineDirectUnitCost",
			"amountValue":            "bcPurchaseOrderLineAmountValue",
			"amountIncludingVAT":     "bcPurchaseOrderLineAmountIncludingVAT",
			"lineDiscount":           "bcPurchaseOrderLineLineDiscount",
			"unitOfMeasureCode":      "bcPurchaseOrderLineUnitOfMeasureCode",
			"locationCode":           "bcPurchaseOrderLineLocationCode",
			"shortcutDimension1Code": "bcPurchaseOrderLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcPurchaseOrderLineShortcutDimension2Code",
			"genProdPostingGroup":    "bcPurchaseOrderLineGenProdPostingGroup",
			"itemCategoryCode":       "bcPurchaseOrderLineItemCategoryCode",
			"createdAt":              "bcPurchaseOrderLineCreatedAt",
			"lastModifiedDateTime":   "bcPurchaseOrderLineLastModifiedDateTime",
		},
	},

	// ─── 6. salesInvoices + salesInvoiceLines ───
	{
		Name:                  "Sales Invoices",
		BCEndpoint:            "salesInvoices",
		SupabaseTable:         "bcSalesInvoice",
		BCPrimaryKey:          "noValue",
		SupabaseConflictCol:   "bcSalesInvoiceNoValue",
		LinesEndpoint:         "salesInvoiceLines",
		LinesTable:            "bcSalesInvoiceLine",
		LinesConflictCols:     "bcSalesInvoiceLineDocumentNo,bcSalesInvoiceLineLineNo",
		SyncGroup:             "document",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"noValue":                "bcSalesInvoiceNoValue",
			"sellToCustomerNo":       "bcSalesInvoiceSellToCustomerNo",
			"sellToCustomerName":     "bcSalesInvoiceSellToCustomerName",
			"sellToAddress":          "bcSalesInvoiceSellToAddress",
			"sellToAddress2":         "bcSalesInvoiceSellToAddress2",
			"sellToCity":             "bcSalesInvoiceSellToCity",
			"sellToPostCode":         "bcSalesInvoiceSellToPostCode",
			"orderDate":              "bcSalesInvoiceOrderDate",
			"postingDate":            "bcSalesInvoicePostingDate",
			"documentDate":           "bcSalesInvoiceDocumentDate",
			"dueDate":                "bcSalesInvoiceDueDate",
			"amountValue":            "bcSalesInvoiceAmountValue",
			"amountIncludingVAT":     "bcSalesInvoiceAmountIncludingVAT",
			"salespersonCode":        "bcSalesInvoiceSalespersonCode",
			"shortcutDimension1Code": "bcSalesInvoiceShortcutDimension1Code",
			"shortcutDimension2Code": "bcSalesInvoiceShortcutDimension2Code",
			"locationCode":           "bcSalesInvoiceLocationCode",
			"currencyCode":           "bcSalesInvoiceCurrencyCode",
			"paymentTermsCode":       "bcSalesInvoicePaymentTermsCode",
			"paymentMethodCode":      "bcSalesInvoicePaymentMethodCode",
			"externalDocumentNo":     "bcSalesInvoiceExternalDocumentNo",
			"status":                 "bcSalesInvoiceStatus",
			"invoiceDiscountAmount":  "bcSalesInvoiceInvoiceDiscountAmount",
			"createdAt":              "bcSalesInvoiceCreatedAt",
			"lastModifiedDateTime":   "bcSalesInvoiceLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcSalesInvoiceLineDocumentNo",
			"lineNo":                 "bcSalesInvoiceLineLineNo",
			"typeValue":              "bcSalesInvoiceLineTypeValue",
			"noValue":                "bcSalesInvoiceLineNoValue",
			"descriptionValue":       "bcSalesInvoiceLineDescriptionValue",
			"description2":           "bcSalesInvoiceLineDescription2",
			"quantityValue":          "bcSalesInvoiceLineQuantityValue",
			"unitPrice":              "bcSalesInvoiceLineUnitPrice",
			"unitCost":               "bcSalesInvoiceLineUnitCost",
			"amountValue":            "bcSalesInvoiceLineAmountValue",
			"amountIncludingVAT":     "bcSalesInvoiceLineAmountIncludingVAT",
			"lineDiscount":           "bcSalesInvoiceLineLineDiscount",
			"lineDiscountAmount":     "bcSalesInvoiceLineLineDiscountAmount",
			"unitOfMeasureCode":      "bcSalesInvoiceLineUnitOfMeasureCode",
			"locationCode":           "bcSalesInvoiceLineLocationCode",
			"shortcutDimension1Code": "bcSalesInvoiceLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcSalesInvoiceLineShortcutDimension2Code",
			"genProdPostingGroup":    "bcSalesInvoiceLineGenProdPostingGroup",
			"createdAt":              "bcSalesInvoiceLineCreatedAt",
			"lastModifiedDateTime":   "bcSalesInvoiceLineLastModifiedDateTime",
		},
	},

	// ─── 7. productionOrders + productionOrderLines ───
	{
		Name:                  "Production Orders",
		BCEndpoint:            "productionOrders",
		SupabaseTable:         "bcProductionOrder",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcProductionOrderNo",
		LinesEndpoint:         "productionOrderLines",
		LinesTable:            "bcProductionOrderLine",
		LinesConflictCols:     "bcProductionOrderLineProdOrderNo,bcProductionOrderLineLineNo",
		SyncGroup:             "document",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                          "bcProductionOrderNo",
			"status":                      "bcProductionOrderStatus",
			"description":                 "bcProductionOrderDescription",
			"description2":                "bcProductionOrderDescription2",
			"sourceNo":                    "bcProductionOrderSourceNo",
			"routingNo":                   "bcProductionOrderRoutingNo",
			"quantity":                    "bcProductionOrderQuantity",
			"shortcutDimension1Code":      "bcProductionOrderShortcutDimension1Code",
			"shortcutDimension2Code":      "bcProductionOrderShortcutDimension2Code",
			"locationCode":                "bcProductionOrderLocationCode",
			"dueDate":                     "bcProductionOrderDueDate",
			"finishedDate":                "bcProductionOrderFinishedDate",
			"startingDateTime":            "bcProductionOrderStartingDateTime",
			"endingDateTime":              "bcProductionOrderEndingDateTime",
			"assignedUserID":              "bcProductionOrderAssignedUserID",
			"searchDescription":           "bcProductionOrderSearchDescription",
			"costAmount":                  "bcProductionOrderCostAmount",
			"unitCost":                    "bcProductionOrderUnitCost",
			"sourceType":                  "bcProductionOrderSourceType",
			"binCode":                     "bcProductionOrderBinCode",
			"creationDate":                "bcProductionOrderCreationDate",
			"expectedOperationCostAmt":    "bcProductionOrderExpectedOperationCostAmt",
			"expectedComponentCostAmt":    "bcProductionOrderExpectedComponentCostAmt",
			"actualTimeUsed":              "bcProductionOrderActualTimeUsed",
			"completelyPicked":            "bcProductionOrderCompletelyPicked",
			"documentPutAwayStatus":       "bcProductionOrderDocumentPutAwayStatus",
			"plannedOrderNo":              "bcProductionOrderPlannedOrderNo",
			"createdAt":                   "bcProductionOrderCreatedAt",
			"lastModifiedDateTime":        "bcProductionOrderLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"status":                 "bcProductionOrderLineStatus",
			"prodOrderNo":            "bcProductionOrderLineProdOrderNo",
			"lineNo":                 "bcProductionOrderLineLineNo",
			"itemNo":                 "bcProductionOrderLineItemNo",
			"description":            "bcProductionOrderLineDescription",
			"description2":           "bcProductionOrderLineDescription2",
			"quantity":               "bcProductionOrderLineQuantity",
			"finishedQuantity":       "bcProductionOrderLineFinishedQuantity",
			"remainingQuantity":      "bcProductionOrderLineRemainingQuantity",
			"unitOfMeasureCode":      "bcProductionOrderLineUnitOfMeasureCode",
			"locationCode":           "bcProductionOrderLineLocationCode",
			"shortcutDimension1Code": "bcProductionOrderLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcProductionOrderLineShortcutDimension2Code",
			"dueDate":                "bcProductionOrderLineDueDate",
			"unitCost":               "bcProductionOrderLineUnitCost",
			"costAmount":             "bcProductionOrderLineCostAmount",
			"scrap":                  "bcProductionOrderLineScrap",
			"routingNo":              "bcProductionOrderLineRoutingNo",
			"productionBOMNo":        "bcProductionOrderLineProductionBOMNo",
			"variantCode":            "bcProductionOrderLineVariantCode",
			"binCode":                "bcProductionOrderLineBinCode",
			"startingDateTime":       "bcProductionOrderLineStartingDateTime",
			"endingDateTime":         "bcProductionOrderLineEndingDateTime",
			"putAwayStatus":          "bcProductionOrderLinePutAwayStatus",
			"createdAt":              "bcProductionOrderLineCreatedAt",
			"lastModifiedDateTime":   "bcProductionOrderLineLastModifiedDateTime",
		},
	},

	// ─── 8. postedSalesInvoices + postedSalesInvoiceLines ───
	{
		Name:                  "Posted Sales Invoices",
		BCEndpoint:            "postedSalesInvoices",
		SupabaseTable:         "bcPostedSalesInvoice",
		BCPrimaryKey:          "noValue",
		SupabaseConflictCol:   "bcPostedSalesInvoiceNoValue",
		LinesEndpoint:         "postedSalesInvoiceLines",
		LinesTable:            "bcPostedSalesInvoiceLine",
		LinesConflictCols:     "bcPostedSalesInvoiceLineDocumentNo,bcPostedSalesInvoiceLineLineNo",
		SyncGroup:             "postedDoc",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"noValue":                "bcPostedSalesInvoiceNoValue",
			"sellToCustomerNo":       "bcPostedSalesInvoiceSellToCustomerNo",
			"sellToCustomerName":     "bcPostedSalesInvoiceSellToCustomerName",
			"sellToAddress":          "bcPostedSalesInvoiceSellToAddress",
			"sellToAddress2":         "bcPostedSalesInvoiceSellToAddress2",
			"sellToCity":             "bcPostedSalesInvoiceSellToCity",
			"sellToPostCode":         "bcPostedSalesInvoiceSellToPostCode",
			"orderNo":                "bcPostedSalesInvoiceOrderNo",
			"orderDate":              "bcPostedSalesInvoiceOrderDate",
			"postingDate":            "bcPostedSalesInvoicePostingDate",
			"documentDate":           "bcPostedSalesInvoiceDocumentDate",
			"dueDate":                "bcPostedSalesInvoiceDueDate",
			"amountValue":            "bcPostedSalesInvoiceAmountValue",
			"amountIncludingVAT":     "bcPostedSalesInvoiceAmountIncludingVAT",
			"salespersonCode":        "bcPostedSalesInvoiceSalespersonCode",
			"shortcutDimension1Code": "bcPostedSalesInvoiceShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedSalesInvoiceShortcutDimension2Code",
			"locationCode":           "bcPostedSalesInvoiceLocationCode",
			"currencyCode":           "bcPostedSalesInvoiceCurrencyCode",
			"currencyFactor":         "bcPostedSalesInvoiceCurrencyFactor",
			"paymentTermsCode":       "bcPostedSalesInvoicePaymentTermsCode",
			"paymentMethodCode":      "bcPostedSalesInvoicePaymentMethodCode",
			"externalDocumentNo":     "bcPostedSalesInvoiceExternalDocumentNo",
			"genBusPostingGroup":     "bcPostedSalesInvoiceGenBusPostingGroup",
			"customerPostingGroup":   "bcPostedSalesInvoiceCustomerPostingGroup",
			"remainingAmount":        "bcPostedSalesInvoiceRemainingAmount",
			"closedValue":            "bcPostedSalesInvoiceClosedValue",
			"invoiceDiscountAmount":  "bcPostedSalesInvoiceInvoiceDiscountAmount",
			"createdAt":              "bcPostedSalesInvoiceCreatedAt",
			"lastModifiedDateTime":   "bcPostedSalesInvoiceLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcPostedSalesInvoiceLineDocumentNo",
			"lineNo":                 "bcPostedSalesInvoiceLineLineNo",
			"typeValue":              "bcPostedSalesInvoiceLineTypeValue",
			"noValue":                "bcPostedSalesInvoiceLineNoValue",
			"descriptionValue":       "bcPostedSalesInvoiceLineDescriptionValue",
			"description2":           "bcPostedSalesInvoiceLineDescription2",
			"quantityValue":          "bcPostedSalesInvoiceLineQuantityValue",
			"unitPrice":              "bcPostedSalesInvoiceLineUnitPrice",
			"unitCost":               "bcPostedSalesInvoiceLineUnitCost",
			"amountValue":            "bcPostedSalesInvoiceLineAmountValue",
			"amountIncludingVAT":     "bcPostedSalesInvoiceLineAmountIncludingVAT",
			"lineDiscount":           "bcPostedSalesInvoiceLineLineDiscount",
			"lineDiscountAmount":     "bcPostedSalesInvoiceLineLineDiscountAmount",
			"unitOfMeasureCode":      "bcPostedSalesInvoiceLineUnitOfMeasureCode",
			"locationCode":           "bcPostedSalesInvoiceLineLocationCode",
			"shortcutDimension1Code": "bcPostedSalesInvoiceLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedSalesInvoiceLineShortcutDimension2Code",
			"genProdPostingGroup":    "bcPostedSalesInvoiceLineGenProdPostingGroup",
			"itemCategoryCode":       "bcPostedSalesInvoiceLineItemCategoryCode",
			"variantCode":            "bcPostedSalesInvoiceLineVariantCode",
			"createdAt":              "bcPostedSalesInvoiceLineCreatedAt",
			"lastModifiedDateTime":   "bcPostedSalesInvoiceLineLastModifiedDateTime",
		},
	},

	// ─── 9. postedSalesShipments + postedSalesShipmentLines ───
	{
		Name:                  "Posted Sales Shipments",
		BCEndpoint:            "postedSalesShipments",
		SupabaseTable:         "bcPostedSalesShipment",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcPostedSalesShipmentNo",
		LinesEndpoint:         "postedSalesShipmentLines",
		LinesTable:            "bcPostedSalesShipmentLine",
		LinesConflictCols:     "bcPostedSalesShipmentLineDocumentNo,bcPostedSalesShipmentLineLineNo",
		SyncGroup:             "postedDoc",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                     "bcPostedSalesShipmentNo",
			"sellToCustomerNo":       "bcPostedSalesShipmentSellToCustomerNo",
			"sellToCustomerName":     "bcPostedSalesShipmentSellToCustomerName",
			"orderNo":                "bcPostedSalesShipmentOrderNo",
			"orderDate":              "bcPostedSalesShipmentOrderDate",
			"postingDate":            "bcPostedSalesShipmentPostingDate",
			"shipmentDate":           "bcPostedSalesShipmentShipmentDate",
			"documentDate":           "bcPostedSalesShipmentDocumentDate",
			"salespersonCode":        "bcPostedSalesShipmentSalespersonCode",
			"shortcutDimension1Code": "bcPostedSalesShipmentShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedSalesShipmentShortcutDimension2Code",
			"locationCode":           "bcPostedSalesShipmentLocationCode",
			"currencyCode":           "bcPostedSalesShipmentCurrencyCode",
			"externalDocumentNo":     "bcPostedSalesShipmentExternalDocumentNo",
			"shipmentMethodCode":     "bcPostedSalesShipmentShipmentMethodCode",
			"shippingAgentCode":      "bcPostedSalesShipmentShippingAgentCode",
			"packageTrackingNo":      "bcPostedSalesShipmentPackageTrackingNo",
			"requestedDeliveryDate":  "bcPostedSalesShipmentRequestedDeliveryDate",
			"createdAt":              "bcPostedSalesShipmentCreatedAt",
			"lastModifiedDateTime":   "bcPostedSalesShipmentLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcPostedSalesShipmentLineDocumentNo",
			"lineNo":                 "bcPostedSalesShipmentLineLineNo",
			"typeValue":              "bcPostedSalesShipmentLineTypeValue",
			"no":                     "bcPostedSalesShipmentLineNoValue",
			"description":            "bcPostedSalesShipmentLineDescriptionValue",
			"description2":           "bcPostedSalesShipmentLineDescription2",
			"quantity":               "bcPostedSalesShipmentLineQuantityValue",
			"unitOfMeasureCode":      "bcPostedSalesShipmentLineUnitOfMeasureCode",
			"locationCode":           "bcPostedSalesShipmentLineLocationCode",
			"shortcutDimension1Code": "bcPostedSalesShipmentLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedSalesShipmentLineShortcutDimension2Code",
			"genProdPostingGroup":    "bcPostedSalesShipmentLineGenProdPostingGroup",
			"itemCategoryCode":       "bcPostedSalesShipmentLineItemCategoryCode",
			"variantCode":            "bcPostedSalesShipmentLineVariantCode",
			"createdAt":              "bcPostedSalesShipmentLineCreatedAt",
			"lastModifiedDateTime":   "bcPostedSalesShipmentLineLastModifiedDateTime",
		},
	},

	// ─── 10. postedSalesCreditMemos + postedSalesCreditMemoLines ───
	{
		Name:                  "Posted Sales Credit Memos",
		BCEndpoint:            "postedSalesCreditMemos",
		SupabaseTable:         "bcPostedSalesCreditMemo",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcPostedSalesCreditMemoNo",
		LinesEndpoint:         "postedSalesCreditMemoLines",
		LinesTable:            "bcPostedSalesCreditMemoLine",
		LinesConflictCols:     "bcPostedSalesCreditMemoLineDocumentNo,bcPostedSalesCreditMemoLineLineNo",
		SyncGroup:             "postedDoc",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                     "bcPostedSalesCreditMemoNo",
			"sellToCustomerNo":       "bcPostedSalesCreditMemoSellToCustomerNo",
			"sellToCustomerName":     "bcPostedSalesCreditMemoSellToCustomerName",
			"postingDate":            "bcPostedSalesCreditMemoPostingDate",
			"documentDate":           "bcPostedSalesCreditMemoDocumentDate",
			"dueDate":                "bcPostedSalesCreditMemoDueDate",
			"amount":                 "bcPostedSalesCreditMemoAmount",
			"amountIncludingVAT":     "bcPostedSalesCreditMemoAmountIncludingVAT",
			"salespersonCode":        "bcPostedSalesCreditMemoSalespersonCode",
			"shortcutDimension1Code": "bcPostedSalesCreditMemoShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedSalesCreditMemoShortcutDimension2Code",
			"locationCode":           "bcPostedSalesCreditMemoLocationCode",
			"currencyCode":           "bcPostedSalesCreditMemoCurrencyCode",
			"currencyFactor":         "bcPostedSalesCreditMemoCurrencyFactor",
			"externalDocumentNo":     "bcPostedSalesCreditMemoExternalDocumentNo",
			"genBusPostingGroup":     "bcPostedSalesCreditMemoGenBusPostingGroup",
			"remainingAmount":        "bcPostedSalesCreditMemoRemainingAmount",
			"paid":                   "bcPostedSalesCreditMemoPaid",
			"cancelled":              "bcPostedSalesCreditMemoCancelled",
			"corrective":             "bcPostedSalesCreditMemoCorrective",
			"createdAt":              "bcPostedSalesCreditMemoCreatedAt",
			"lastModifiedDateTime":   "bcPostedSalesCreditMemoLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcPostedSalesCreditMemoLineDocumentNo",
			"lineNo":                 "bcPostedSalesCreditMemoLineLineNo",
			"typeValue":              "bcPostedSalesCreditMemoLineTypeValue",
			"no":                     "bcPostedSalesCreditMemoLineNoValue",
			"description":            "bcPostedSalesCreditMemoLineDescriptionValue",
			"description2":           "bcPostedSalesCreditMemoLineDescription2",
			"quantity":               "bcPostedSalesCreditMemoLineQuantityValue",
			"unitPrice":              "bcPostedSalesCreditMemoLineUnitPrice",
			"unitCost":               "bcPostedSalesCreditMemoLineUnitCost",
			"amount":                 "bcPostedSalesCreditMemoLineAmountValue",
			"amountIncludingVAT":     "bcPostedSalesCreditMemoLineAmountIncludingVAT",
			"lineDiscount":           "bcPostedSalesCreditMemoLineLineDiscount",
			"unitOfMeasureCode":      "bcPostedSalesCreditMemoLineUnitOfMeasureCode",
			"locationCode":           "bcPostedSalesCreditMemoLineLocationCode",
			"shortcutDimension1Code": "bcPostedSalesCreditMemoLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedSalesCreditMemoLineShortcutDimension2Code",
			"createdAt":              "bcPostedSalesCreditMemoLineCreatedAt",
			"lastModifiedDateTime":   "bcPostedSalesCreditMemoLineLastModifiedDateTime",
		},
	},

	// ─── 11. postedPurchInvoices + postedPurchInvoiceLines ───
	{
		Name:                  "Posted Purchase Invoices",
		BCEndpoint:            "postedPurchInvoices",
		SupabaseTable:         "bcPostedPurchInvoice",
		BCPrimaryKey:          "noValue",
		SupabaseConflictCol:   "bcPostedPurchInvoiceNoValue",
		LinesEndpoint:         "postedPurchInvoiceLines",
		LinesTable:            "bcPostedPurchInvoiceLine",
		LinesConflictCols:     "bcPostedPurchInvoiceLineDocumentNo,bcPostedPurchInvoiceLineLineNo",
		SyncGroup:             "postedDoc",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"noValue":                "bcPostedPurchInvoiceNoValue",
			"buyFromVendorNo":        "bcPostedPurchInvoiceBuyFromVendorNo",
			"buyFromVendorName":      "bcPostedPurchInvoiceBuyFromVendorName",
			"orderNo":                "bcPostedPurchInvoiceOrderNo",
			"orderDate":              "bcPostedPurchInvoiceOrderDate",
			"postingDate":            "bcPostedPurchInvoicePostingDate",
			"documentDate":           "bcPostedPurchInvoiceDocumentDate",
			"dueDate":                "bcPostedPurchInvoiceDueDate",
			"amountValue":            "bcPostedPurchInvoiceAmountValue",
			"amountIncludingVAT":     "bcPostedPurchInvoiceAmountIncludingVAT",
			"purchaserCode":          "bcPostedPurchInvoicePurchaserCode",
			"shortcutDimension1Code": "bcPostedPurchInvoiceShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedPurchInvoiceShortcutDimension2Code",
			"locationCode":           "bcPostedPurchInvoiceLocationCode",
			"currencyCode":           "bcPostedPurchInvoiceCurrencyCode",
			"currencyFactor":         "bcPostedPurchInvoiceCurrencyFactor",
			"paymentTermsCode":       "bcPostedPurchInvoicePaymentTermsCode",
			"paymentMethodCode":      "bcPostedPurchInvoicePaymentMethodCode",
			"vendorInvoiceNo":        "bcPostedPurchInvoiceVendorInvoiceNo",
			"vendorOrderNo":          "bcPostedPurchInvoiceVendorOrderNo",
			"genBusPostingGroup":     "bcPostedPurchInvoiceGenBusPostingGroup",
			"remainingAmount":        "bcPostedPurchInvoiceRemainingAmount",
			"closedValue":            "bcPostedPurchInvoiceClosedValue",
			"invoiceDiscountAmount":  "bcPostedPurchInvoiceInvoiceDiscountAmount",
			"createdAt":              "bcPostedPurchInvoiceCreatedAt",
			"lastModifiedDateTime":   "bcPostedPurchInvoiceLastModifiedDateTime",
		},
		LineFieldMap: map[string]string{
			"documentNo":             "bcPostedPurchInvoiceLineDocumentNo",
			"lineNo":                 "bcPostedPurchInvoiceLineLineNo",
			"typeValue":              "bcPostedPurchInvoiceLineTypeValue",
			"noValue":                "bcPostedPurchInvoiceLineNoValue",
			"descriptionValue":       "bcPostedPurchInvoiceLineDescriptionValue",
			"description2":           "bcPostedPurchInvoiceLineDescription2",
			"quantityValue":          "bcPostedPurchInvoiceLineQuantityValue",
			"directUnitCost":         "bcPostedPurchInvoiceLineDirectUnitCost",
			"amountValue":            "bcPostedPurchInvoiceLineAmountValue",
			"amountIncludingVAT":     "bcPostedPurchInvoiceLineAmountIncludingVAT",
			"lineDiscount":           "bcPostedPurchInvoiceLineLineDiscount",
			"unitOfMeasureCode":      "bcPostedPurchInvoiceLineUnitOfMeasureCode",
			"locationCode":           "bcPostedPurchInvoiceLineLocationCode",
			"shortcutDimension1Code": "bcPostedPurchInvoiceLineShortcutDimension1Code",
			"shortcutDimension2Code": "bcPostedPurchInvoiceLineShortcutDimension2Code",
			"genProdPostingGroup":    "bcPostedPurchInvoiceLineGenProdPostingGroup",
			"itemCategoryCode":       "bcPostedPurchInvoiceLineItemCategoryCode",
			"variantCode":            "bcPostedPurchInvoiceLineVariantCode",
			"createdAt":              "bcPostedPurchInvoiceLineCreatedAt",
			"lastModifiedDateTime":   "bcPostedPurchInvoiceLineLastModifiedDateTime",
		},
	},

	// ─── 12. vendors ───
	{
		Name:                  "Vendors",
		BCEndpoint:            "vendors",
		SupabaseTable:         "bcVendor",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcVendorNo",
		SyncGroup:             "master",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                   "bcVendorNo",
			"nameValue":            "bcVendorNameValue",
			"address":              "bcVendorAddress",
			"address2":             "bcVendorAddress2",
			"city":                 "bcVendorCity",
			"postCode":             "bcVendorPostCode",
			"contact":              "bcVendorContact",
			"phoneNo":              "bcVendorPhoneNo",
			"eMail":                "bcVendorEMail",
			"mobilePhoneNo":        "bcVendorMobilePhoneNo",
			"vendorPostingGroup":   "bcVendorVendorPostingGroup",
			"paymentTermsCode":     "bcVendorPaymentTermsCode",
			"paymentMethodCode":    "bcVendorPaymentMethodCode",
			"purchaserCode":        "bcVendorPurchaserCode",
			"globalDimension1Code": "bcVendorGlobalDimension1Code",
			"globalDimension2Code": "bcVendorGlobalDimension2Code",
			"balanceLCY":           "bcVendorBalanceLCY",
			"balanceDueLCY":        "bcVendorBalanceDueLCY",
			"vATRegistrationNo":    "bcVendorVATRegistrationNo",
			"genBusPostingGroup":   "bcVendorGenBusPostingGroup",
			"blocked":              "bcVendorBlocked",
			"countryRegionCode":    "bcVendorCountryRegionCode",
			"outstandingOrders":    "bcVendorOutstandingOrders",
			"outstandingInvoices":  "bcVendorOutstandingInvoices",
			"purchasesLCY":         "bcVendorPurchasesLCY",
			"createdAt":            "bcVendorCreatedAt",
			"lastModifiedDateTime": "bcVendorLastModifiedDateTime",
		},
	},

	// ─── 13. glAccounts ───
	{
		Name:                  "GL Accounts",
		BCEndpoint:            "glAccounts",
		SupabaseTable:         "bcGLAccount",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcGLAccountNo",
		SyncGroup:             "small",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                   "bcGLAccountNo",
			"nameValue":            "bcGLAccountNameValue",
			"accountType":          "bcGLAccountAccountType",
			"accountCategory":      "bcGLAccountAccountCategory",
			"incomeBalance":        "bcGLAccountIncomeBalance",
			"debitCredit":          "bcGLAccountDebitCredit",
			"balance":              "bcGLAccountBalance",
			"netChange":            "bcGLAccountNetChange",
			"blocked":              "bcGLAccountBlocked",
			"directPosting":        "bcGLAccountDirectPosting",
			"indentation":          "bcGLAccountIndentation",
			"totaling":             "bcGLAccountTotaling",
			"createdAt":            "bcGLAccountCreatedAt",
			"lastModifiedDateTime": "bcGLAccountLastModifiedDateTime",
		},
	},

	// ─── 14. bankAccounts ───
	{
		Name:                  "Bank Accounts",
		BCEndpoint:            "bankAccounts",
		SupabaseTable:         "bcBankAccount",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcBankAccountNo",
		SyncGroup:             "small",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                   "bcBankAccountNo",
			"nameValue":            "bcBankAccountNameValue",
			"bankAccountNo":        "bcBankAccountBankAccountNo",
			"bankBranchNo":         "bcBankAccountBankBranchNo",
			"currencyCode":         "bcBankAccountCurrencyCode",
			"balance":              "bcBankAccountBalance",
			"balanceLCY":           "bcBankAccountBalanceLCY",
			"iBAN":                 "bcBankAccountIBAN",
			"sWIFTCode":            "bcBankAccountSWIFTCode",
			"globalDimension1Code": "bcBankAccountGlobalDimension1Code",
			"globalDimension2Code": "bcBankAccountGlobalDimension2Code",
			"blocked":              "bcBankAccountBlocked",
			"createdAt":            "bcBankAccountCreatedAt",
			"lastModifiedDateTime": "bcBankAccountLastModifiedDateTime",
		},
	},

	// ─── 15. fixedAssets ───
	{
		Name:                  "Fixed Assets",
		BCEndpoint:            "fixedAssets",
		SupabaseTable:         "bcFixedAsset",
		BCPrimaryKey:          "no",
		SupabaseConflictCol:   "bcFixedAssetNo",
		SyncGroup:             "small",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"no":                   "bcFixedAssetNo",
			"description":          "bcFixedAssetDescription",
			"description2":         "bcFixedAssetDescription2",
			"fAClassCode":          "bcFixedAssetFAClassCode",
			"fASubclassCode":       "bcFixedAssetFASubclassCode",
			"globalDimension1Code": "bcFixedAssetGlobalDimension1Code",
			"globalDimension2Code": "bcFixedAssetGlobalDimension2Code",
			"locationCode":         "bcFixedAssetLocationCode",
			"fALocationCode":       "bcFixedAssetFALocationCode",
			"vendorNo":             "bcFixedAssetVendorNo",
			"responsibleEmployee":  "bcFixedAssetResponsibleEmployee",
			"serialNo":             "bcFixedAssetSerialNo",
			"warrantyDate":         "bcFixedAssetWarrantyDate",
			"acquired":             "bcFixedAssetAcquired",
			"inactive":             "bcFixedAssetInactive",
			"blocked":              "bcFixedAssetBlocked",
			"fAPostingGroup":       "bcFixedAssetFAPostingGroup",
			"lastDateModified":     "bcFixedAssetLastDateModified",
			"createdAt":            "bcFixedAssetCreatedAt",
			"lastModifiedDateTime": "bcFixedAssetLastModifiedDateTime",
		},
	},

	// ─── 16. dimensionSetEntries ───
	{
		Name:                  "Dimension Set Entries",
		BCEndpoint:            "dimensionSetEntries",
		SupabaseTable:         "bcDimensionSetEntry",
		BCPrimaryKey:          "",
		SupabaseConflictCol:   "bcDimensionSetEntryDimensionSetID,bcDimensionSetEntryDimensionCode",
		SyncGroup:             "small",
		IncrementalFilterType: "",
		FieldMap: map[string]string{
			"dimensionSetID":     "bcDimensionSetEntryDimensionSetID",
			"dimensionCode":      "bcDimensionSetEntryDimensionCode",
			"dimensionValueCode": "bcDimensionSetEntryDimensionValueCode",
			"dimensionValueID":   "bcDimensionSetEntryDimensionValueID",
			"dimensionName":      "bcDimensionSetEntryDimensionName",
			"dimensionValueName": "bcDimensionSetEntryDimensionValueName",
			"globalDimensionNo":  "bcDimensionSetEntryGlobalDimensionNo",
			"createdAt":          "bcDimensionSetEntryCreatedAt",
		},
	},

	// ─── 17. salesQuotes ───
	{
		Name:                  "Sales Quotes",
		BCEndpoint:            "salesQuotes",
		SupabaseTable:         "bcSalesQuote",
		BCPrimaryKey:          "noValue",
		SupabaseConflictCol:   "bcSalesQuoteNoValue",
		SyncGroup:             "small",
		IncrementalFilterType: "timestamp",
		FieldMap: map[string]string{
			"noValue":                "bcSalesQuoteNoValue",
			"sellToCustomerNo":       "bcSalesQuoteSellToCustomerNo",
			"sellToCustomerName":     "bcSalesQuoteSellToCustomerName",
			"orderDate":              "bcSalesQuoteOrderDate",
			"dueDate":                "bcSalesQuoteDueDate",
			"documentDate":           "bcSalesQuoteDocumentDate",
			"amountValue":            "bcSalesQuoteAmountValue",
			"amountIncludingVAT":     "bcSalesQuoteAmountIncludingVAT",
			"salespersonCode":        "bcSalesQuoteSalespersonCode",
			"shortcutDimension1Code": "bcSalesQuoteShortcutDimension1Code",
			"shortcutDimension2Code": "bcSalesQuoteShortcutDimension2Code",
			"locationCode":           "bcSalesQuoteLocationCode",
			"currencyCode":           "bcSalesQuoteCurrencyCode",
			"externalDocumentNo":     "bcSalesQuoteExternalDocumentNo",
			"status":                 "bcSalesQuoteStatus",
			"quoteValidUntilDate":    "bcSalesQuoteQuoteValidUntilDate",
			"quoteAccepted":          "bcSalesQuoteQuoteAccepted",
			"quoteAcceptedDate":      "bcSalesQuoteQuoteAcceptedDate",
			"opportunityNo":          "bcSalesQuoteOpportunityNo",
			"assignedUserID":         "bcSalesQuoteAssignedUserID",
			"createdAt":              "bcSalesQuoteCreatedAt",
			"lastModifiedDateTime":   "bcSalesQuoteLastModifiedDateTime",
		},
	},

	// ─── 18. valueEntries ───
	{
		Name:                  "Value Entries",
		BCEndpoint:            "valueEntries",
		SupabaseTable:         "bcValueEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcValueEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":              "bcValueEntryEntryNo",
			"itemNo":               "bcValueEntryItemNo",
			"postingDate":          "bcValueEntryPostingDate",
			"documentNo":           "bcValueEntryDocumentNo",
			"documentType":         "bcValueEntryDocumentType",
			"descriptionValue":     "bcValueEntryDescriptionValue",
			"locationCode":         "bcValueEntryLocationCode",
			"valuedQuantity":       "bcValueEntryValuedQuantity",
			"invoicedQuantity":     "bcValueEntryInvoicedQuantity",
			"costPerUnit":          "bcValueEntryCostPerUnit",
			"itemLedgerEntryNo":    "bcValueEntryItemLedgerEntryNo",
			"itemLedgerEntryType":  "bcValueEntryItemLedgerEntryType",
			"entryType":            "bcValueEntryEntryType",
			"salespersPurchCode":   "bcValueEntrySalespersPurchCode",
			"discountAmount":       "bcValueEntryDiscountAmount",
			"globalDimension1Code": "bcValueEntryGlobalDimension1Code",
			"globalDimension2Code": "bcValueEntryGlobalDimension2Code",
			"sourceType":           "bcValueEntrySourceType",
			"sourceNo":             "bcValueEntrySourceNo",
			"genProdPostingGroup":  "bcValueEntryGenProdPostingGroup",
			"orderType":            "bcValueEntryOrderType",
			"orderNo":              "bcValueEntryOrderNo",
			"expectedCost":         "bcValueEntryExpectedCost",
			"createdAt":            "bcValueEntryCreatedAt",
			"lastModifiedDateTime": "bcValueEntryLastModifiedDateTime",
		},
	},

	// ─── 19. itemLedgerEntries ───
	{
		Name:                  "Item Ledger Entries",
		BCEndpoint:            "itemLedgerEntries",
		SupabaseTable:         "bcItemLedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcItemLedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":              "bcItemLedgerEntryEntryNo",
			"itemNo":               "bcItemLedgerEntryItemNo",
			"postingDate":          "bcItemLedgerEntryPostingDate",
			"entryType":            "bcItemLedgerEntryEntryType",
			"documentNo":           "bcItemLedgerEntryDocumentNo",
			"descriptionValue":     "bcItemLedgerEntryDescriptionValue",
			"locationCode":         "bcItemLedgerEntryLocationCode",
			"quantityValue":        "bcItemLedgerEntryQuantityValue",
			"remainingQuantity":    "bcItemLedgerEntryRemainingQuantity",
			"invoicedQuantity":     "bcItemLedgerEntryInvoicedQuantity",
			"unitOfMeasureCode":    "bcItemLedgerEntryUnitOfMeasureCode",
			"globalDimension1Code": "bcItemLedgerEntryGlobalDimension1Code",
			"globalDimension2Code": "bcItemLedgerEntryGlobalDimension2Code",
			"openValue":            "bcItemLedgerEntryOpenValue",
			"orderType":            "bcItemLedgerEntryOrderType",
			"orderNo":              "bcItemLedgerEntryOrderNo",
			"orderLineNo":          "bcItemLedgerEntryOrderLineNo",
			"itemDescription":      "bcItemLedgerEntryItemDescription",
			"documentDate":         "bcItemLedgerEntryDocumentDate",
			"documentType":         "bcItemLedgerEntryDocumentType",
			"completelyInvoiced":   "bcItemLedgerEntryCompletelyInvoiced",
			"variantCode":          "bcItemLedgerEntryVariantCode",
			"serialNo":             "bcItemLedgerEntrySerialNo",
			"lotNo":                "bcItemLedgerEntryLotNo",
			"expirationDate":       "bcItemLedgerEntryExpirationDate",
			"itemCategoryCode":     "bcItemLedgerEntryItemCategoryCode",
			"sourceNo":             "bcItemLedgerEntrySourceNo",
			"documentLineNo":       "bcItemLedgerEntryDocumentLineNo",
			"createdAt":            "bcItemLedgerEntryCreatedAt",
			"lastModifiedDateTime": "bcItemLedgerEntryLastModifiedDateTime",
		},
	},

	// ─── 20. gLEntries ───
	{
		Name:                  "GL Entries",
		BCEndpoint:            "gLEntries",
		SupabaseTable:         "bcGLEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcGLEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":              "bcGLEntryEntryNo",
			"gLAccountNo":          "bcGLEntryGLAccountNo",
			"gLAccountName":        "bcGLEntryGLAccountName",
			"postingDate":          "bcGLEntryPostingDate",
			"documentType":         "bcGLEntryDocumentType",
			"documentNo":           "bcGLEntryDocumentNo",
			"descriptionValue":     "bcGLEntryDescriptionValue",
			"amountValue":          "bcGLEntryAmountValue",
			"debitAmount":          "bcGLEntryDebitAmount",
			"creditAmount":         "bcGLEntryCreditAmount",
			"globalDimension1Code": "bcGLEntryGlobalDimension1Code",
			"globalDimension2Code": "bcGLEntryGlobalDimension2Code",
			"sourceType":           "bcGLEntrySourceType",
			"sourceNo":             "bcGLEntrySourceNo",
			"genPostingType":       "bcGLEntryGenPostingType",
			"genBusPostingGroup":   "bcGLEntryGenBusPostingGroup",
			"genProdPostingGroup":  "bcGLEntryGenProdPostingGroup",
			"documentDate":         "bcGLEntryDocumentDate",
			"externalDocumentNo":   "bcGLEntryExternalDocumentNo",
			"vATAmount":            "bcGLEntryVATAmount",
			"createdAt":            "bcGLEntryCreatedAt",
			"lastModifiedDateTime": "bcGLEntryLastModifiedDateTime",
		},
	},

	// ─── 21. customerLedgerEntries ───
	{
		Name:                  "Customer Ledger Entries",
		BCEndpoint:            "customerLedgerEntries",
		SupabaseTable:         "bcCustomerLedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcCustomerLedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":              "bcCustomerLedgerEntryEntryNo",
			"customerNo":           "bcCustomerLedgerEntryCustomerNo",
			"customerName":         "bcCustomerLedgerEntryCustomerName",
			"postingDate":          "bcCustomerLedgerEntryPostingDate",
			"documentType":         "bcCustomerLedgerEntryDocumentType",
			"documentNo":           "bcCustomerLedgerEntryDocumentNo",
			"description":          "bcCustomerLedgerEntryDescription",
			"amount":               "bcCustomerLedgerEntryAmount",
			"amountLCY":            "bcCustomerLedgerEntryAmountLCY",
			"remainingAmount":      "bcCustomerLedgerEntryRemainingAmount",
			"remainingAmtLCY":      "bcCustomerLedgerEntryRemainingAmtLCY",
			"dueDate":              "bcCustomerLedgerEntryDueDate",
			"openValue":            "bcCustomerLedgerEntryOpenValue",
			"salesLCY":             "bcCustomerLedgerEntrySalesLCY",
			"profitLCY":            "bcCustomerLedgerEntryProfitLCY",
			"salespersonCode":      "bcCustomerLedgerEntrySalespersonCode",
			"globalDimension1Code": "bcCustomerLedgerEntryGlobalDimension1Code",
			"globalDimension2Code": "bcCustomerLedgerEntryGlobalDimension2Code",
			"customerPostingGroup": "bcCustomerLedgerEntryCustomerPostingGroup",
			"sellToCustomerNo":     "bcCustomerLedgerEntrySellToCustomerNo",
			"currencyCode":         "bcCustomerLedgerEntryCurrencyCode",
			"documentDate":         "bcCustomerLedgerEntryDocumentDate",
			"externalDocumentNo":   "bcCustomerLedgerEntryExternalDocumentNo",
			"createdAt":            "bcCustomerLedgerEntryCreatedAt",
			"lastModifiedDateTime": "bcCustomerLedgerEntryLastModifiedDateTime",
		},
	},

	// ─── 22. vendorLedgerEntries ───
	{
		Name:                  "Vendor Ledger Entries",
		BCEndpoint:            "vendorLedgerEntries",
		SupabaseTable:         "bcVendorLedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcVendorLedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":              "bcVendorLedgerEntryEntryNo",
			"vendorNo":             "bcVendorLedgerEntryVendorNo",
			"vendorName":           "bcVendorLedgerEntryVendorName",
			"postingDate":          "bcVendorLedgerEntryPostingDate",
			"documentType":         "bcVendorLedgerEntryDocumentType",
			"documentNo":           "bcVendorLedgerEntryDocumentNo",
			"description":          "bcVendorLedgerEntryDescription",
			"amount":               "bcVendorLedgerEntryAmount",
			"amountLCY":            "bcVendorLedgerEntryAmountLCY",
			"remainingAmount":      "bcVendorLedgerEntryRemainingAmount",
			"remainingAmtLCY":      "bcVendorLedgerEntryRemainingAmtLCY",
			"dueDate":              "bcVendorLedgerEntryDueDate",
			"openValue":            "bcVendorLedgerEntryOpenValue",
			"purchaseLCY":          "bcVendorLedgerEntryPurchaseLCY",
			"purchaserCode":        "bcVendorLedgerEntryPurchaserCode",
			"globalDimension1Code": "bcVendorLedgerEntryGlobalDimension1Code",
			"globalDimension2Code": "bcVendorLedgerEntryGlobalDimension2Code",
			"vendorPostingGroup":   "bcVendorLedgerEntryVendorPostingGroup",
			"buyFromVendorNo":      "bcVendorLedgerEntryBuyFromVendorNo",
			"currencyCode":         "bcVendorLedgerEntryCurrencyCode",
			"documentDate":         "bcVendorLedgerEntryDocumentDate",
			"externalDocumentNo":   "bcVendorLedgerEntryExternalDocumentNo",
			"createdAt":            "bcVendorLedgerEntryCreatedAt",
			"lastModifiedDateTime": "bcVendorLedgerEntryLastModifiedDateTime",
		},
	},

	// ─── 23. detailedCustLedgerEntries ───
	{
		Name:                  "Detailed Cust. Ledger Entries",
		BCEndpoint:            "detailedCustLedgerEntries",
		SupabaseTable:         "bcDetailedCustLedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcDetailedCustLedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":                  "bcDetailedCustLedgerEntryEntryNo",
			"custLedgerEntryNo":        "bcDetailedCustLedgerEntryCustLedgerEntryNo",
			"entryType":                "bcDetailedCustLedgerEntryEntryType",
			"postingDate":              "bcDetailedCustLedgerEntryPostingDate",
			"documentType":             "bcDetailedCustLedgerEntryDocumentType",
			"documentNo":               "bcDetailedCustLedgerEntryDocumentNo",
			"amount":                   "bcDetailedCustLedgerEntryAmount",
			"amountLCY":                "bcDetailedCustLedgerEntryAmountLCY",
			"customerNo":               "bcDetailedCustLedgerEntryCustomerNo",
			"currencyCode":             "bcDetailedCustLedgerEntryCurrencyCode",
			"debitAmount":              "bcDetailedCustLedgerEntryDebitAmount",
			"creditAmount":             "bcDetailedCustLedgerEntryCreditAmount",
			"initialEntryDueDate":      "bcDetailedCustLedgerEntryInitialEntryDueDate",
			"initialEntryGlobalDim1":   "bcDetailedCustLedgerEntryInitialEntryGlobalDim1",
			"initialEntryGlobalDim2":   "bcDetailedCustLedgerEntryInitialEntryGlobalDim2",
			"initialDocumentType":      "bcDetailedCustLedgerEntryInitialDocumentType",
			"appliedCustLedgerEntryNo": "bcDetailedCustLedgerEntryAppliedCustLedgerEntryNo",
			"unapplied":                "bcDetailedCustLedgerEntryUnapplied",
			"createdAt":                "bcDetailedCustLedgerEntryCreatedAt",
			"lastModifiedDateTime":     "bcDetailedCustLedgerEntryLastModifiedDateTime",
		},
	},

	// ─── 24. detailedVendorLedgerEntries ───
	{
		Name:                  "Detailed Vendor Ledger Entries",
		BCEndpoint:            "detailedVendorLedgerEntries",
		SupabaseTable:         "bcDetailedVendorLedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcDetailedVendorLedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":                   "bcDetailedVendorLedgerEntryEntryNo",
			"vendorLedgerEntryNo":       "bcDetailedVendorLedgerEntryVendorLedgerEntryNo",
			"entryType":                 "bcDetailedVendorLedgerEntryEntryType",
			"postingDate":               "bcDetailedVendorLedgerEntryPostingDate",
			"documentType":              "bcDetailedVendorLedgerEntryDocumentType",
			"documentNo":                "bcDetailedVendorLedgerEntryDocumentNo",
			"amount":                    "bcDetailedVendorLedgerEntryAmount",
			"amountLCY":                 "bcDetailedVendorLedgerEntryAmountLCY",
			"vendorNo":                  "bcDetailedVendorLedgerEntryVendorNo",
			"currencyCode":              "bcDetailedVendorLedgerEntryCurrencyCode",
			"debitAmount":               "bcDetailedVendorLedgerEntryDebitAmount",
			"creditAmount":              "bcDetailedVendorLedgerEntryCreditAmount",
			"initialEntryDueDate":       "bcDetailedVendorLedgerEntryInitialEntryDueDate",
			"initialEntryGlobalDim1":    "bcDetailedVendorLedgerEntryInitialEntryGlobalDim1",
			"initialEntryGlobalDim2":    "bcDetailedVendorLedgerEntryInitialEntryGlobalDim2",
			"initialDocumentType":       "bcDetailedVendorLedgerEntryInitialDocumentType",
			"appliedVendLedgerEntryNo":  "bcDetailedVendorLedgerEntryAppliedVendLedgerEntryNo",
			"unapplied":                 "bcDetailedVendorLedgerEntryUnapplied",
			"createdAt":                 "bcDetailedVendorLedgerEntryCreatedAt",
			"lastModifiedDateTime":      "bcDetailedVendorLedgerEntryLastModifiedDateTime",
		},
	},

	// ─── 25. bankAccountLedgerEntries ───
	{
		Name:                  "Bank Account Ledger Entries",
		BCEndpoint:            "bankAccountLedgerEntries",
		SupabaseTable:         "bcBankAccountLedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcBankAccountLedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":              "bcBankAccountLedgerEntryEntryNo",
			"bankAccountNo":        "bcBankAccountLedgerEntryBankAccountNo",
			"postingDate":          "bcBankAccountLedgerEntryPostingDate",
			"documentType":         "bcBankAccountLedgerEntryDocumentType",
			"documentNo":           "bcBankAccountLedgerEntryDocumentNo",
			"description":          "bcBankAccountLedgerEntryDescription",
			"amount":               "bcBankAccountLedgerEntryAmount",
			"remainingAmount":      "bcBankAccountLedgerEntryRemainingAmount",
			"amountLCY":            "bcBankAccountLedgerEntryAmountLCY",
			"debitAmount":          "bcBankAccountLedgerEntryDebitAmount",
			"creditAmount":         "bcBankAccountLedgerEntryCreditAmount",
			"globalDimension1Code": "bcBankAccountLedgerEntryGlobalDimension1Code",
			"globalDimension2Code": "bcBankAccountLedgerEntryGlobalDimension2Code",
			"openValue":            "bcBankAccountLedgerEntryOpenValue",
			"currencyCode":         "bcBankAccountLedgerEntryCurrencyCode",
			"documentDate":         "bcBankAccountLedgerEntryDocumentDate",
			"externalDocumentNo":   "bcBankAccountLedgerEntryExternalDocumentNo",
			"statementStatus":      "bcBankAccountLedgerEntryStatementStatus",
			"createdAt":            "bcBankAccountLedgerEntryCreatedAt",
			"lastModifiedDateTime": "bcBankAccountLedgerEntryLastModifiedDateTime",
		},
	},

	// ─── 26. faLedgerEntries ───
	{
		Name:                  "FA Ledger Entries",
		BCEndpoint:            "faLedgerEntries",
		SupabaseTable:         "bcFALedgerEntry",
		BCPrimaryKey:          "entryNo",
		SupabaseConflictCol:   "bcFALedgerEntryEntryNo",
		SyncGroup:             "ledger",
		IncrementalFilterType: "entryNo",
		FieldMap: map[string]string{
			"entryNo":               "bcFALedgerEntryEntryNo",
			"fANo":                  "bcFALedgerEntryFANo",
			"fAPostingDate":         "bcFALedgerEntryFAPostingDate",
			"postingDate":           "bcFALedgerEntryPostingDate",
			"documentType":          "bcFALedgerEntryDocumentType",
			"documentNo":            "bcFALedgerEntryDocumentNo",
			"description":           "bcFALedgerEntryDescription",
			"fAPostingType":         "bcFALedgerEntryFAPostingType",
			"amount":                "bcFALedgerEntryAmount",
			"debitAmount":           "bcFALedgerEntryDebitAmount",
			"creditAmount":          "bcFALedgerEntryCreditAmount",
			"depreciationBookCode":  "bcFALedgerEntryDepreciationBookCode",
			"globalDimension1Code":  "bcFALedgerEntryGlobalDimension1Code",
			"globalDimension2Code":  "bcFALedgerEntryGlobalDimension2Code",
			"noOfDepreciationDays":  "bcFALedgerEntryNoOfDepreciationDays",
			"fAClassCode":           "bcFALedgerEntryFAClassCode",
			"createdAt":             "bcFALedgerEntryCreatedAt",
			"lastModifiedDateTime":  "bcFALedgerEntryLastModifiedDateTime",
		},
	},
}

// Date field names that need null-coercion (BC sends "0001-01-01" for empty dates).
var dateFields = map[string]bool{
	"orderDate":              true,
	"dueDate":                true,
	"postingDate":            true,
	"documentDate":           true,
	"shipmentDate":           true,
	"creationDate":           true,
	"finishedDate":           true,
	"warrantyDate":           true,
	"lastDateModified":       true,
	"expirationDate":         true,
	"fAPostingDate":          true,
	"requestedDeliveryDate":  true,
	"promisedDeliveryDate":   true,
	"lastShipmentDate":       true,
	"expectedReceiptDate":    true,
	"quoteValidUntilDate":    true,
	"quoteAcceptedDate":      true,
	"initialEntryDueDate":    true,
	"plannedDeliveryDate":    true,
	"plannedShipmentDate":    true,
}

// Timestamp field names that need null-coercion.
var timestampFields = map[string]bool{
	"startingDateTime":    true,
	"endingDateTime":      true,
	"createdAt":           true,
	"lastModifiedDateTime": true,
}

// GetAllSupabaseTables returns every Supabase table name (headers + lines) that
// the sync writes to. Useful for full-sync truncation.
func GetAllSupabaseTables() []string {
	var tables []string
	for _, cfg := range SyncConfig {
		if cfg.SupabaseTable != "" {
			tables = append(tables, cfg.SupabaseTable)
		}
		if cfg.LinesTable != "" {
			tables = append(tables, cfg.LinesTable)
		}
	}
	return tables
}

// GetConfigsByGroup returns the subset of SyncConfig belonging to the given
// sync group (e.g. "master", "document", "postedDoc", "small", "ledger").
func GetConfigsByGroup(group string) []EntityConfig {
	var out []EntityConfig
	for _, cfg := range SyncConfig {
		if cfg.SyncGroup == group {
			out = append(out, cfg)
		}
	}
	return out
}

// bcDate coerces BC sentinel dates to nil.
func bcDate(val any) any {
	s, ok := val.(string)
	if !ok || s == "" || s == "0001-01-01" {
		return nil
	}
	return val
}

// bcTimestamp coerces BC sentinel timestamps to nil.
func bcTimestamp(val any) any {
	s, ok := val.(string)
	if !ok || s == "" || strings.HasPrefix(s, "0001-01-01") {
		return nil
	}
	return val
}

// TransformRecord maps a raw BC JSON record through a fieldMap, applying
// date/timestamp null-coercion. Fields whose fieldMap value is "" are skipped
// (e.g. dimensionValues fields that are kept only in memory).
func TransformRecord(record map[string]any, fieldMap map[string]string) map[string]any {
	row := make(map[string]any, len(fieldMap))
	for bcField, supaCol := range fieldMap {
		if supaCol == "" {
			continue
		}
		val := record[bcField]
		switch {
		case dateFields[bcField]:
			row[supaCol] = bcDate(val)
		case timestampFields[bcField]:
			row[supaCol] = bcTimestamp(val)
		default:
			if val == nil {
				row[supaCol] = nil
			} else {
				row[supaCol] = val
			}
		}
	}
	return row
}
