-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.arFollowUp (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customerNumber text NOT NULL,
  customerName text NOT NULL,
  invoiceNumber text,
  contactDate date NOT NULL DEFAULT CURRENT_DATE,
  contactMethod text NOT NULL DEFAULT 'phone'::text,
  reason text NOT NULL,
  reasonDetail text,
  note text,
  promiseDate date,
  promiseAmount numeric,
  status text NOT NULL DEFAULT 'pending'::text,
  nextFollowUpDate date,
  assignedTo text,
  createdBy uuid NOT NULL,
  createdByName text NOT NULL DEFAULT ''::text,
  createdAt timestamp with time zone DEFAULT now(),
  updatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT arFollowUp_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bankEntry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  statementId uuid NOT NULL,
  lineNumber integer NOT NULL,
  txDate date NOT NULL,
  txTime time without time zone,
  channel text,
  description text,
  txType text,
  amount numeric NOT NULL,
  balance numeric,
  direction text NOT NULL,
  matchStatus text NOT NULL DEFAULT 'unmatched'::text,
  matchConfidence numeric,
  matchMethod text,
  matchNote text,
  matchedBy uuid,
  matchedAt timestamp with time zone,
  createdAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bankEntry_pkey PRIMARY KEY (id),
  CONSTRAINT bankEntry_statementId_fkey FOREIGN KEY (statementId) REFERENCES public.bankStatement(id)
);
CREATE TABLE public.bankMatch (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entryId uuid NOT NULL,
  invoiceNumber text NOT NULL,
  customerNumber text,
  customerName text,
  invoiceAmount numeric,
  remainingAmount numeric,
  matchedAmount numeric NOT NULL,
  createdAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bankMatch_pkey PRIMARY KEY (id),
  CONSTRAINT bankMatch_entryId_fkey FOREIGN KEY (entryId) REFERENCES public.bankEntry(id)
);
CREATE TABLE public.bankStatement (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bankCode text NOT NULL DEFAULT 'KBANK'::text,
  accountNumber text,
  periodStart date,
  periodEnd date,
  fileName text NOT NULL,
  fileUrl text NOT NULL,
  openingBalance numeric,
  closingBalance numeric,
  entryCount integer DEFAULT 0,
  matchedCount integer DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text,
  parseError text,
  createdBy uuid,
  createdByName text,
  createdAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bankStatement_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcBankAccount (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcBankAccountNo text NOT NULL UNIQUE,
  bcBankAccountNameValue text,
  bcBankAccountBankAccountNo text,
  bcBankAccountBankBranchNo text,
  bcBankAccountCurrencyCode text,
  bcBankAccountBalance numeric,
  bcBankAccountBalanceLCY numeric,
  bcBankAccountIBAN text,
  bcBankAccountSWIFTCode text,
  bcBankAccountGlobalDimension1Code text,
  bcBankAccountGlobalDimension2Code text,
  bcBankAccountBlocked text,
  bcBankAccountCreatedAt timestamp with time zone,
  bcBankAccountLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcBankAccount_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcBankAccountLedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcBankAccountLedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcBankAccountLedgerEntryBankAccountNo text,
  bcBankAccountLedgerEntryPostingDate date,
  bcBankAccountLedgerEntryDocumentType text,
  bcBankAccountLedgerEntryDocumentNo text,
  bcBankAccountLedgerEntryDocumentDate date,
  bcBankAccountLedgerEntryDescription text,
  bcBankAccountLedgerEntryAmount numeric,
  bcBankAccountLedgerEntryRemainingAmount numeric,
  bcBankAccountLedgerEntryAmountLCY numeric,
  bcBankAccountLedgerEntryDebitAmount numeric,
  bcBankAccountLedgerEntryCreditAmount numeric,
  bcBankAccountLedgerEntryGlobalDimension1Code text,
  bcBankAccountLedgerEntryGlobalDimension2Code text,
  bcBankAccountLedgerEntryOpenValue text,
  bcBankAccountLedgerEntryCurrencyCode text,
  bcBankAccountLedgerEntryExternalDocumentNo text,
  bcBankAccountLedgerEntryStatementStatus text,
  bcBankAccountLedgerEntryCreatedAt timestamp with time zone,
  bcBankAccountLedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcBankAccountLedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcCustomer (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcCustomerNo text NOT NULL UNIQUE,
  bcCustomerNameValue text,
  bcCustomerAddress text,
  bcCustomerAddress2 text,
  bcCustomerCity text,
  bcCustomerPostCode text,
  bcCustomerContact text,
  bcCustomerPhoneNo text,
  bcCustomerEMail text,
  bcCustomerMobilePhoneNo text,
  bcCustomerSalespersonCode text,
  bcCustomerCustomerPostingGroup text,
  bcCustomerPaymentTermsCode text,
  bcCustomerPaymentMethodCode text,
  bcCustomerGlobalDimension1Code text,
  bcCustomerGlobalDimension2Code text,
  bcCustomerCreditLimitLCY numeric,
  bcCustomerBalanceLCY numeric,
  bcCustomerBalanceDueLCY numeric,
  bcCustomerOutstandingOrders numeric,
  bcCustomerShippedNotInvoiced numeric,
  bcCustomerOutstandingInvoices numeric,
  bcCustomerBlocked text,
  bcCustomerVATRegistrationNo text,
  bcCustomerGenBusPostingGroup text,
  bcCustomerSalesLCY numeric,
  bcCustomerProfitLCY numeric,
  bcCustomerCountryRegionCode text,
  bcCustomerCreatedAt timestamp with time zone,
  bcCustomerLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcCustomer_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcCustomerLedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcCustomerLedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcCustomerLedgerEntryCustomerNo text,
  bcCustomerLedgerEntryCustomerName text,
  bcCustomerLedgerEntryPostingDate date,
  bcCustomerLedgerEntryDocumentType text,
  bcCustomerLedgerEntryDocumentNo text,
  bcCustomerLedgerEntryDocumentDate date,
  bcCustomerLedgerEntryDescription text,
  bcCustomerLedgerEntryAmount numeric,
  bcCustomerLedgerEntryAmountLCY numeric,
  bcCustomerLedgerEntryRemainingAmount numeric,
  bcCustomerLedgerEntryRemainingAmtLCY numeric,
  bcCustomerLedgerEntryDueDate date,
  bcCustomerLedgerEntryOpenValue text,
  bcCustomerLedgerEntrySalesLCY numeric,
  bcCustomerLedgerEntryProfitLCY numeric,
  bcCustomerLedgerEntrySalespersonCode text,
  bcCustomerLedgerEntryGlobalDimension1Code text,
  bcCustomerLedgerEntryGlobalDimension2Code text,
  bcCustomerLedgerEntryCustomerPostingGroup text,
  bcCustomerLedgerEntrySellToCustomerNo text,
  bcCustomerLedgerEntryCurrencyCode text,
  bcCustomerLedgerEntryExternalDocumentNo text,
  bcCustomerLedgerEntryCreatedAt timestamp with time zone,
  bcCustomerLedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcCustomerLedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcDetailedCustLedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcDetailedCustLedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcDetailedCustLedgerEntryCustLedgerEntryNo integer,
  bcDetailedCustLedgerEntryEntryType text,
  bcDetailedCustLedgerEntryPostingDate date,
  bcDetailedCustLedgerEntryDocumentType text,
  bcDetailedCustLedgerEntryDocumentNo text,
  bcDetailedCustLedgerEntryAmount numeric,
  bcDetailedCustLedgerEntryAmountLCY numeric,
  bcDetailedCustLedgerEntryCustomerNo text,
  bcDetailedCustLedgerEntryCurrencyCode text,
  bcDetailedCustLedgerEntryDebitAmount numeric,
  bcDetailedCustLedgerEntryCreditAmount numeric,
  bcDetailedCustLedgerEntryInitialEntryDueDate date,
  bcDetailedCustLedgerEntryInitialEntryGlobalDim1 text,
  bcDetailedCustLedgerEntryInitialEntryGlobalDim2 text,
  bcDetailedCustLedgerEntryInitialDocumentType text,
  bcDetailedCustLedgerEntryAppliedCustLedgerEntryNo integer,
  bcDetailedCustLedgerEntryUnapplied boolean,
  bcDetailedCustLedgerEntryCreatedAt timestamp with time zone,
  bcDetailedCustLedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcDetailedCustLedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcDetailedVendorLedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcDetailedVendorLedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcDetailedVendorLedgerEntryVendorLedgerEntryNo integer,
  bcDetailedVendorLedgerEntryEntryType text,
  bcDetailedVendorLedgerEntryPostingDate date,
  bcDetailedVendorLedgerEntryDocumentType text,
  bcDetailedVendorLedgerEntryDocumentNo text,
  bcDetailedVendorLedgerEntryAmount numeric,
  bcDetailedVendorLedgerEntryAmountLCY numeric,
  bcDetailedVendorLedgerEntryVendorNo text,
  bcDetailedVendorLedgerEntryCurrencyCode text,
  bcDetailedVendorLedgerEntryDebitAmount numeric,
  bcDetailedVendorLedgerEntryCreditAmount numeric,
  bcDetailedVendorLedgerEntryInitialEntryDueDate date,
  bcDetailedVendorLedgerEntryInitialEntryGlobalDim1 text,
  bcDetailedVendorLedgerEntryInitialEntryGlobalDim2 text,
  bcDetailedVendorLedgerEntryInitialDocumentType text,
  bcDetailedVendorLedgerEntryAppliedVendLedgerEntryNo integer,
  bcDetailedVendorLedgerEntryUnapplied boolean,
  bcDetailedVendorLedgerEntryCreatedAt timestamp with time zone,
  bcDetailedVendorLedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcDetailedVendorLedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcDimensionSetEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcDimensionSetEntryDimensionSetID integer NOT NULL,
  bcDimensionSetEntryDimensionCode text NOT NULL,
  bcDimensionSetEntryDimensionValueCode text,
  bcDimensionSetEntryDimensionValueID integer,
  bcDimensionSetEntryDimensionName text,
  bcDimensionSetEntryDimensionValueName text,
  bcDimensionSetEntryGlobalDimensionNo integer,
  bcDimensionSetEntryCreatedAt timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcDimensionSetEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcFALedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcFALedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcFALedgerEntryFANo text,
  bcFALedgerEntryFAPostingDate date,
  bcFALedgerEntryPostingDate date,
  bcFALedgerEntryDocumentType text,
  bcFALedgerEntryDocumentNo text,
  bcFALedgerEntryDescription text,
  bcFALedgerEntryFAPostingType text,
  bcFALedgerEntryAmount numeric,
  bcFALedgerEntryDebitAmount numeric,
  bcFALedgerEntryCreditAmount numeric,
  bcFALedgerEntryDepreciationBookCode text,
  bcFALedgerEntryGlobalDimension1Code text,
  bcFALedgerEntryGlobalDimension2Code text,
  bcFALedgerEntryNoOfDepreciationDays integer,
  bcFALedgerEntryFAClassCode text,
  bcFALedgerEntryCreatedAt timestamp with time zone,
  bcFALedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcFALedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcFixedAsset (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcFixedAssetNo text NOT NULL UNIQUE,
  bcFixedAssetDescription text,
  bcFixedAssetDescription2 text,
  bcFixedAssetFAClassCode text,
  bcFixedAssetFASubclassCode text,
  bcFixedAssetGlobalDimension1Code text,
  bcFixedAssetGlobalDimension2Code text,
  bcFixedAssetLocationCode text,
  bcFixedAssetFALocationCode text,
  bcFixedAssetVendorNo text,
  bcFixedAssetResponsibleEmployee text,
  bcFixedAssetSerialNo text,
  bcFixedAssetWarrantyDate date,
  bcFixedAssetAcquired boolean,
  bcFixedAssetInactive boolean,
  bcFixedAssetBlocked text,
  bcFixedAssetFAPostingGroup text,
  bcFixedAssetLastDateModified date,
  bcFixedAssetCreatedAt timestamp with time zone,
  bcFixedAssetLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcFixedAsset_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcGLAccount (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcGLAccountNo text NOT NULL UNIQUE,
  bcGLAccountNameValue text,
  bcGLAccountAccountType text,
  bcGLAccountAccountCategory text,
  bcGLAccountIncomeBalance text,
  bcGLAccountDebitCredit text,
  bcGLAccountBalance numeric,
  bcGLAccountNetChange numeric,
  bcGLAccountBlocked text,
  bcGLAccountDirectPosting boolean,
  bcGLAccountIndentation integer,
  bcGLAccountTotaling text,
  bcGLAccountCreatedAt timestamp with time zone,
  bcGLAccountLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcGLAccount_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcGLEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcGLEntryEntryNo integer NOT NULL UNIQUE,
  bcGLEntryGLAccountNo text,
  bcGLEntryGLAccountName text,
  bcGLEntryPostingDate date,
  bcGLEntryDocumentType text,
  bcGLEntryDocumentNo text,
  bcGLEntryDocumentDate date,
  bcGLEntryDescriptionValue text,
  bcGLEntryAmountValue numeric,
  bcGLEntryDebitAmount numeric,
  bcGLEntryCreditAmount numeric,
  bcGLEntryGlobalDimension1Code text,
  bcGLEntryGlobalDimension2Code text,
  bcGLEntrySourceType text,
  bcGLEntrySourceNo text,
  bcGLEntryGenPostingType text,
  bcGLEntryGenBusPostingGroup text,
  bcGLEntryGenProdPostingGroup text,
  bcGLEntryExternalDocumentNo text,
  bcGLEntryVATAmount numeric,
  bcGLEntryCreatedAt timestamp with time zone,
  bcGLEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcGLEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcItem (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcItemNo text NOT NULL UNIQUE,
  bcItemDescription text,
  bcItemDescription2 text,
  bcItemType text,
  bcItemBlocked text,
  bcItemBaseUnitOfMeasure text,
  bcItemUnitPrice numeric,
  bcItemUnitCost numeric,
  bcItemStandardCost numeric,
  bcItemLastDirectCost numeric,
  bcItemCostingMethod text,
  bcItemGenProdPostingGroup text,
  bcItemInventoryPostingGroup text,
  bcItemItemCategoryCode text,
  bcItemInventory numeric,
  bcItemGlobalDimension1Code text,
  bcItemGlobalDimension2Code text,
  bcItemVendorNo text,
  bcItemGrossWeight numeric,
  bcItemNetWeight numeric,
  bcItemProductionBOMNo text,
  bcItemRfidCode text UNIQUE,
  bcItemCreatedAt timestamp with time zone,
  bcItemLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcItem_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcItemLedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcItemLedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcItemLedgerEntryItemNo text,
  bcItemLedgerEntryPostingDate date,
  bcItemLedgerEntryEntryType text,
  bcItemLedgerEntryDocumentNo text,
  bcItemLedgerEntryDocumentType text,
  bcItemLedgerEntryDocumentDate date,
  bcItemLedgerEntryDescriptionValue text,
  bcItemLedgerEntryLocationCode text,
  bcItemLedgerEntryQuantityValue numeric,
  bcItemLedgerEntryRemainingQuantity numeric,
  bcItemLedgerEntryInvoicedQuantity numeric,
  bcItemLedgerEntryUnitOfMeasureCode text,
  bcItemLedgerEntryGlobalDimension1Code text,
  bcItemLedgerEntryGlobalDimension2Code text,
  bcItemLedgerEntryOpenValue text,
  bcItemLedgerEntryOrderType text,
  bcItemLedgerEntryOrderNo text,
  bcItemLedgerEntryOrderLineNo integer,
  bcItemLedgerEntryItemDescription text,
  bcItemLedgerEntryCompletelyInvoiced boolean,
  bcItemLedgerEntryVariantCode text,
  bcItemLedgerEntrySerialNo text,
  bcItemLedgerEntryLotNo text,
  bcItemLedgerEntryExpirationDate date,
  bcItemLedgerEntryItemCategoryCode text,
  bcItemLedgerEntrySourceNo text,
  bcItemLedgerEntryDocumentLineNo integer,
  bcItemLedgerEntryCreatedAt timestamp with time zone,
  bcItemLedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcItemLedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedPurchInvoice (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedPurchInvoiceNoValue text NOT NULL UNIQUE,
  bcPostedPurchInvoiceBuyFromVendorNo text,
  bcPostedPurchInvoiceBuyFromVendorName text,
  bcPostedPurchInvoiceOrderNo text,
  bcPostedPurchInvoiceOrderDate date,
  bcPostedPurchInvoicePostingDate date,
  bcPostedPurchInvoiceDocumentDate date,
  bcPostedPurchInvoiceDueDate date,
  bcPostedPurchInvoiceAmountValue numeric,
  bcPostedPurchInvoiceAmountIncludingVAT numeric,
  bcPostedPurchInvoicePurchaserCode text,
  bcPostedPurchInvoiceShortcutDimension1Code text,
  bcPostedPurchInvoiceShortcutDimension2Code text,
  bcPostedPurchInvoiceLocationCode text,
  bcPostedPurchInvoiceCurrencyCode text,
  bcPostedPurchInvoiceCurrencyFactor numeric,
  bcPostedPurchInvoicePaymentTermsCode text,
  bcPostedPurchInvoicePaymentMethodCode text,
  bcPostedPurchInvoiceVendorInvoiceNo text,
  bcPostedPurchInvoiceVendorOrderNo text,
  bcPostedPurchInvoiceGenBusPostingGroup text,
  bcPostedPurchInvoiceRemainingAmount numeric,
  bcPostedPurchInvoiceClosedValue text,
  bcPostedPurchInvoiceInvoiceDiscountAmount numeric,
  bcPostedPurchInvoiceCreatedAt timestamp with time zone,
  bcPostedPurchInvoiceLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedPurchInvoice_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedPurchInvoiceLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedPurchInvoiceLineDocumentNo text NOT NULL,
  bcPostedPurchInvoiceLineLineNo integer NOT NULL,
  bcPostedPurchInvoiceLineTypeValue text,
  bcPostedPurchInvoiceLineNoValue text,
  bcPostedPurchInvoiceLineDescriptionValue text,
  bcPostedPurchInvoiceLineDescription2 text,
  bcPostedPurchInvoiceLineQuantityValue numeric,
  bcPostedPurchInvoiceLineDirectUnitCost numeric,
  bcPostedPurchInvoiceLineAmountValue numeric,
  bcPostedPurchInvoiceLineAmountIncludingVAT numeric,
  bcPostedPurchInvoiceLineLineDiscount numeric,
  bcPostedPurchInvoiceLineUnitOfMeasureCode text,
  bcPostedPurchInvoiceLineLocationCode text,
  bcPostedPurchInvoiceLineShortcutDimension1Code text,
  bcPostedPurchInvoiceLineShortcutDimension2Code text,
  bcPostedPurchInvoiceLineGenProdPostingGroup text,
  bcPostedPurchInvoiceLineItemCategoryCode text,
  bcPostedPurchInvoiceLineVariantCode text,
  bcPostedPurchInvoiceLineCreatedAt timestamp with time zone,
  bcPostedPurchInvoiceLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedPurchInvoiceLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedSalesCreditMemo (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedSalesCreditMemoNo text NOT NULL UNIQUE,
  bcPostedSalesCreditMemoSellToCustomerNo text,
  bcPostedSalesCreditMemoSellToCustomerName text,
  bcPostedSalesCreditMemoPostingDate date,
  bcPostedSalesCreditMemoDocumentDate date,
  bcPostedSalesCreditMemoDueDate date,
  bcPostedSalesCreditMemoAmount numeric,
  bcPostedSalesCreditMemoAmountIncludingVAT numeric,
  bcPostedSalesCreditMemoSalespersonCode text,
  bcPostedSalesCreditMemoShortcutDimension1Code text,
  bcPostedSalesCreditMemoShortcutDimension2Code text,
  bcPostedSalesCreditMemoLocationCode text,
  bcPostedSalesCreditMemoCurrencyCode text,
  bcPostedSalesCreditMemoCurrencyFactor numeric,
  bcPostedSalesCreditMemoExternalDocumentNo text,
  bcPostedSalesCreditMemoGenBusPostingGroup text,
  bcPostedSalesCreditMemoRemainingAmount numeric,
  bcPostedSalesCreditMemoPaid text,
  bcPostedSalesCreditMemoCancelled text,
  bcPostedSalesCreditMemoCorrective text,
  bcPostedSalesCreditMemoCreatedAt timestamp with time zone,
  bcPostedSalesCreditMemoLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedSalesCreditMemo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedSalesCreditMemoLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedSalesCreditMemoLineDocumentNo text NOT NULL,
  bcPostedSalesCreditMemoLineLineNo integer NOT NULL,
  bcPostedSalesCreditMemoLineTypeValue text,
  bcPostedSalesCreditMemoLineNoValue text,
  bcPostedSalesCreditMemoLineDescriptionValue text,
  bcPostedSalesCreditMemoLineDescription2 text,
  bcPostedSalesCreditMemoLineQuantityValue numeric,
  bcPostedSalesCreditMemoLineUnitPrice numeric,
  bcPostedSalesCreditMemoLineUnitCost numeric,
  bcPostedSalesCreditMemoLineAmountValue numeric,
  bcPostedSalesCreditMemoLineAmountIncludingVAT numeric,
  bcPostedSalesCreditMemoLineLineDiscount numeric,
  bcPostedSalesCreditMemoLineUnitOfMeasureCode text,
  bcPostedSalesCreditMemoLineLocationCode text,
  bcPostedSalesCreditMemoLineShortcutDimension1Code text,
  bcPostedSalesCreditMemoLineShortcutDimension2Code text,
  bcPostedSalesCreditMemoLineCreatedAt timestamp with time zone,
  bcPostedSalesCreditMemoLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedSalesCreditMemoLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedSalesInvoice (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedSalesInvoiceNoValue text NOT NULL UNIQUE,
  bcPostedSalesInvoiceSellToCustomerNo text,
  bcPostedSalesInvoiceSellToCustomerName text,
  bcPostedSalesInvoiceSellToAddress text,
  bcPostedSalesInvoiceSellToAddress2 text,
  bcPostedSalesInvoiceSellToCity text,
  bcPostedSalesInvoiceSellToPostCode text,
  bcPostedSalesInvoiceOrderNo text,
  bcPostedSalesInvoiceOrderDate date,
  bcPostedSalesInvoicePostingDate date,
  bcPostedSalesInvoiceDocumentDate date,
  bcPostedSalesInvoiceDueDate date,
  bcPostedSalesInvoiceAmountValue numeric,
  bcPostedSalesInvoiceAmountIncludingVAT numeric,
  bcPostedSalesInvoiceSalespersonCode text,
  bcPostedSalesInvoiceShortcutDimension1Code text,
  bcPostedSalesInvoiceShortcutDimension2Code text,
  bcPostedSalesInvoiceLocationCode text,
  bcPostedSalesInvoiceCurrencyCode text,
  bcPostedSalesInvoiceCurrencyFactor numeric,
  bcPostedSalesInvoicePaymentTermsCode text,
  bcPostedSalesInvoicePaymentMethodCode text,
  bcPostedSalesInvoiceExternalDocumentNo text,
  bcPostedSalesInvoiceGenBusPostingGroup text,
  bcPostedSalesInvoiceCustomerPostingGroup text,
  bcPostedSalesInvoiceRemainingAmount numeric,
  bcPostedSalesInvoiceClosedValue text,
  bcPostedSalesInvoiceInvoiceDiscountAmount numeric,
  bcPostedSalesInvoiceCreatedAt timestamp with time zone,
  bcPostedSalesInvoiceLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedSalesInvoice_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedSalesInvoiceLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedSalesInvoiceLineDocumentNo text NOT NULL,
  bcPostedSalesInvoiceLineLineNo integer NOT NULL,
  bcPostedSalesInvoiceLineTypeValue text,
  bcPostedSalesInvoiceLineNoValue text,
  bcPostedSalesInvoiceLineDescriptionValue text,
  bcPostedSalesInvoiceLineDescription2 text,
  bcPostedSalesInvoiceLineQuantityValue numeric,
  bcPostedSalesInvoiceLineUnitPrice numeric,
  bcPostedSalesInvoiceLineUnitCost numeric,
  bcPostedSalesInvoiceLineAmountValue numeric,
  bcPostedSalesInvoiceLineAmountIncludingVAT numeric,
  bcPostedSalesInvoiceLineLineDiscount numeric,
  bcPostedSalesInvoiceLineLineDiscountAmount numeric,
  bcPostedSalesInvoiceLineUnitOfMeasureCode text,
  bcPostedSalesInvoiceLineLocationCode text,
  bcPostedSalesInvoiceLineShortcutDimension1Code text,
  bcPostedSalesInvoiceLineShortcutDimension2Code text,
  bcPostedSalesInvoiceLineGenProdPostingGroup text,
  bcPostedSalesInvoiceLineItemCategoryCode text,
  bcPostedSalesInvoiceLineVariantCode text,
  bcPostedSalesInvoiceLineCreatedAt timestamp with time zone,
  bcPostedSalesInvoiceLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedSalesInvoiceLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedSalesShipment (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedSalesShipmentNo text NOT NULL UNIQUE,
  bcPostedSalesShipmentSellToCustomerNo text,
  bcPostedSalesShipmentSellToCustomerName text,
  bcPostedSalesShipmentOrderNo text,
  bcPostedSalesShipmentOrderDate date,
  bcPostedSalesShipmentPostingDate date,
  bcPostedSalesShipmentShipmentDate date,
  bcPostedSalesShipmentDocumentDate date,
  bcPostedSalesShipmentSalespersonCode text,
  bcPostedSalesShipmentShortcutDimension1Code text,
  bcPostedSalesShipmentShortcutDimension2Code text,
  bcPostedSalesShipmentLocationCode text,
  bcPostedSalesShipmentCurrencyCode text,
  bcPostedSalesShipmentExternalDocumentNo text,
  bcPostedSalesShipmentShipmentMethodCode text,
  bcPostedSalesShipmentShippingAgentCode text,
  bcPostedSalesShipmentPackageTrackingNo text,
  bcPostedSalesShipmentRequestedDeliveryDate date,
  bcPostedSalesShipmentCreatedAt timestamp with time zone,
  bcPostedSalesShipmentLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedSalesShipment_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPostedSalesShipmentLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPostedSalesShipmentLineDocumentNo text NOT NULL,
  bcPostedSalesShipmentLineLineNo integer NOT NULL,
  bcPostedSalesShipmentLineTypeValue text,
  bcPostedSalesShipmentLineNoValue text,
  bcPostedSalesShipmentLineDescriptionValue text,
  bcPostedSalesShipmentLineDescription2 text,
  bcPostedSalesShipmentLineQuantityValue numeric,
  bcPostedSalesShipmentLineUnitOfMeasureCode text,
  bcPostedSalesShipmentLineLocationCode text,
  bcPostedSalesShipmentLineShortcutDimension1Code text,
  bcPostedSalesShipmentLineShortcutDimension2Code text,
  bcPostedSalesShipmentLineGenProdPostingGroup text,
  bcPostedSalesShipmentLineItemCategoryCode text,
  bcPostedSalesShipmentLineVariantCode text,
  bcPostedSalesShipmentLineCreatedAt timestamp with time zone,
  bcPostedSalesShipmentLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPostedSalesShipmentLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcProductionOrder (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcProductionOrderNo text NOT NULL UNIQUE,
  bcProductionOrderStatus text,
  bcProductionOrderDescription text,
  bcProductionOrderDescription2 text,
  bcProductionOrderSourceNo text,
  bcProductionOrderSourceType text,
  bcProductionOrderRoutingNo text,
  bcProductionOrderQuantity numeric,
  bcProductionOrderShortcutDimension1Code text,
  bcProductionOrderShortcutDimension2Code text,
  bcProductionOrderLocationCode text,
  bcProductionOrderDueDate date,
  bcProductionOrderFinishedDate date,
  bcProductionOrderStartingDateTime timestamp with time zone,
  bcProductionOrderEndingDateTime timestamp with time zone,
  bcProductionOrderAssignedUserID text,
  bcProductionOrderSearchDescription text,
  bcProductionOrderCostAmount numeric,
  bcProductionOrderUnitCost numeric,
  bcProductionOrderBinCode text,
  bcProductionOrderCreationDate date,
  bcProductionOrderExpectedOperationCostAmt numeric,
  bcProductionOrderExpectedComponentCostAmt numeric,
  bcProductionOrderActualTimeUsed numeric,
  bcProductionOrderCompletelyPicked boolean,
  bcProductionOrderDocumentPutAwayStatus text,
  bcProductionOrderPlannedOrderNo text,
  bcProductionOrderCreatedAt timestamp with time zone,
  bcProductionOrderLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcProductionOrder_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcProductionOrderLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcProductionOrderLineProdOrderNo text NOT NULL,
  bcProductionOrderLineLineNo integer NOT NULL,
  bcProductionOrderLineStatus text,
  bcProductionOrderLineItemNo text,
  bcProductionOrderLineDescription text,
  bcProductionOrderLineDescription2 text,
  bcProductionOrderLineQuantity numeric,
  bcProductionOrderLineFinishedQuantity numeric,
  bcProductionOrderLineRemainingQuantity numeric,
  bcProductionOrderLineUnitOfMeasureCode text,
  bcProductionOrderLineLocationCode text,
  bcProductionOrderLineShortcutDimension1Code text,
  bcProductionOrderLineShortcutDimension2Code text,
  bcProductionOrderLineDueDate date,
  bcProductionOrderLineUnitCost numeric,
  bcProductionOrderLineCostAmount numeric,
  bcProductionOrderLineScrap numeric,
  bcProductionOrderLineRoutingNo text,
  bcProductionOrderLineProductionBOMNo text,
  bcProductionOrderLineVariantCode text,
  bcProductionOrderLineBinCode text,
  bcProductionOrderLineStartingDateTime timestamp with time zone,
  bcProductionOrderLineEndingDateTime timestamp with time zone,
  bcProductionOrderLinePutAwayStatus text,
  bcProductionOrderLineCreatedAt timestamp with time zone,
  bcProductionOrderLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcProductionOrderLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPurchaseOrder (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPurchaseOrderNoValue text NOT NULL UNIQUE,
  bcPurchaseOrderBuyFromVendorNo text,
  bcPurchaseOrderBuyFromVendorName text,
  bcPurchaseOrderBuyFromAddress text,
  bcPurchaseOrderBuyFromAddress2 text,
  bcPurchaseOrderBuyFromCity text,
  bcPurchaseOrderBuyFromPostCode text,
  bcPurchaseOrderOrderDate date,
  bcPurchaseOrderPostingDate date,
  bcPurchaseOrderExpectedReceiptDate date,
  bcPurchaseOrderDueDate date,
  bcPurchaseOrderDocumentDate date,
  bcPurchaseOrderAmountValue numeric,
  bcPurchaseOrderAmountIncludingVAT numeric,
  bcPurchaseOrderPurchaserCode text,
  bcPurchaseOrderShortcutDimension1Code text,
  bcPurchaseOrderShortcutDimension2Code text,
  bcPurchaseOrderLocationCode text,
  bcPurchaseOrderCurrencyCode text,
  bcPurchaseOrderCurrencyFactor numeric,
  bcPurchaseOrderPaymentTermsCode text,
  bcPurchaseOrderPaymentMethodCode text,
  bcPurchaseOrderVendorInvoiceNo text,
  bcPurchaseOrderVendorOrderNo text,
  bcPurchaseOrderStatus text,
  bcPurchaseOrderCompletelyReceived boolean,
  bcPurchaseOrderInvoiceDiscountAmount numeric,
  bcPurchaseOrderAssignedUserID text,
  bcPurchaseOrderGenBusPostingGroup text,
  bcPurchaseOrderCreatedAt timestamp with time zone,
  bcPurchaseOrderLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPurchaseOrder_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcPurchaseOrderLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcPurchaseOrderLineDocumentNo text NOT NULL,
  bcPurchaseOrderLineLineNo integer NOT NULL,
  bcPurchaseOrderLineTypeValue text,
  bcPurchaseOrderLineNoValue text,
  bcPurchaseOrderLineDescriptionValue text,
  bcPurchaseOrderLineDescription2 text,
  bcPurchaseOrderLineQuantityValue numeric,
  bcPurchaseOrderLineOutstandingQuantity numeric,
  bcPurchaseOrderLineQuantityReceived numeric,
  bcPurchaseOrderLineQuantityInvoiced numeric,
  bcPurchaseOrderLineDirectUnitCost numeric,
  bcPurchaseOrderLineAmountValue numeric,
  bcPurchaseOrderLineAmountIncludingVAT numeric,
  bcPurchaseOrderLineLineDiscount numeric,
  bcPurchaseOrderLineUnitOfMeasureCode text,
  bcPurchaseOrderLineLocationCode text,
  bcPurchaseOrderLineShortcutDimension1Code text,
  bcPurchaseOrderLineShortcutDimension2Code text,
  bcPurchaseOrderLineGenProdPostingGroup text,
  bcPurchaseOrderLineItemCategoryCode text,
  bcPurchaseOrderLineCreatedAt timestamp with time zone,
  bcPurchaseOrderLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcPurchaseOrderLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcSalesInvoice (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcSalesInvoiceNoValue text NOT NULL UNIQUE,
  bcSalesInvoiceSellToCustomerNo text,
  bcSalesInvoiceSellToCustomerName text,
  bcSalesInvoiceSellToAddress text,
  bcSalesInvoiceSellToAddress2 text,
  bcSalesInvoiceSellToCity text,
  bcSalesInvoiceSellToPostCode text,
  bcSalesInvoiceOrderDate date,
  bcSalesInvoicePostingDate date,
  bcSalesInvoiceDocumentDate date,
  bcSalesInvoiceDueDate date,
  bcSalesInvoiceAmountValue numeric,
  bcSalesInvoiceAmountIncludingVAT numeric,
  bcSalesInvoiceSalespersonCode text,
  bcSalesInvoiceShortcutDimension1Code text,
  bcSalesInvoiceShortcutDimension2Code text,
  bcSalesInvoiceLocationCode text,
  bcSalesInvoiceCurrencyCode text,
  bcSalesInvoicePaymentTermsCode text,
  bcSalesInvoicePaymentMethodCode text,
  bcSalesInvoiceExternalDocumentNo text,
  bcSalesInvoiceStatus text,
  bcSalesInvoiceInvoiceDiscountAmount numeric,
  bcSalesInvoiceCreatedAt timestamp with time zone,
  bcSalesInvoiceLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcSalesInvoice_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcSalesInvoiceLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcSalesInvoiceLineDocumentNo text NOT NULL,
  bcSalesInvoiceLineLineNo integer NOT NULL,
  bcSalesInvoiceLineTypeValue text,
  bcSalesInvoiceLineNoValue text,
  bcSalesInvoiceLineDescriptionValue text,
  bcSalesInvoiceLineDescription2 text,
  bcSalesInvoiceLineQuantityValue numeric,
  bcSalesInvoiceLineUnitPrice numeric,
  bcSalesInvoiceLineUnitCost numeric,
  bcSalesInvoiceLineAmountValue numeric,
  bcSalesInvoiceLineAmountIncludingVAT numeric,
  bcSalesInvoiceLineLineDiscount numeric,
  bcSalesInvoiceLineLineDiscountAmount numeric,
  bcSalesInvoiceLineUnitOfMeasureCode text,
  bcSalesInvoiceLineLocationCode text,
  bcSalesInvoiceLineShortcutDimension1Code text,
  bcSalesInvoiceLineShortcutDimension2Code text,
  bcSalesInvoiceLineGenProdPostingGroup text,
  bcSalesInvoiceLineCreatedAt timestamp with time zone,
  bcSalesInvoiceLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcSalesInvoiceLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcSalesOrder (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcSalesOrderNoValue text NOT NULL UNIQUE,
  bcSalesOrderSellToCustomerNo text,
  bcSalesOrderSellToCustomerName text,
  bcSalesOrderSellToAddress text,
  bcSalesOrderSellToAddress2 text,
  bcSalesOrderSellToCity text,
  bcSalesOrderSellToPostCode text,
  bcSalesOrderShipToName text,
  bcSalesOrderShipToAddress text,
  bcSalesOrderShipToAddress2 text,
  bcSalesOrderShipToCity text,
  bcSalesOrderShipToPostCode text,
  bcSalesOrderOrderDate date,
  bcSalesOrderDueDate date,
  bcSalesOrderPostingDate date,
  bcSalesOrderDocumentDate date,
  bcSalesOrderStatus text,
  bcSalesOrderCompletelyShipped boolean,
  bcSalesOrderSalespersonCode text,
  bcSalesOrderExternalDocumentNo text,
  bcSalesOrderLocationCode text,
  bcSalesOrderShortcutDimension1Code text,
  bcSalesOrderShortcutDimension2Code text,
  bcSalesOrderAmountValue numeric,
  bcSalesOrderAmountIncludingVAT numeric,
  bcSalesOrderAssignedUserID text,
  bcSalesOrderRequestedDeliveryDate date,
  bcSalesOrderPaymentTermsCode text,
  bcSalesOrderPaymentMethodCode text,
  bcSalesOrderCurrencyCode text,
  bcSalesOrderQuoteNo text,
  bcSalesOrderInvoiceDiscountAmount numeric,
  bcSalesOrderShipmentMethodCode text,
  bcSalesOrderShippingAgentCode text,
  bcSalesOrderLastShipmentDate date,
  bcSalesOrderPromisedDeliveryDate date,
  bcSalesOrderSellToPhoneNo text,
  bcSalesOrderSellToEMail text,
  bcSalesOrderNoSeries text,
  bcSalesOrderCurrencyFactor numeric,
  bcSalesOrderCreatedAt timestamp with time zone,
  bcSalesOrderLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcSalesOrder_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcSalesOrderLine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcSalesOrderLineDocumentNo text NOT NULL,
  bcSalesOrderLineLineNo integer NOT NULL,
  bcSalesOrderLineTypeValue text,
  bcSalesOrderLineNoValue text,
  bcSalesOrderLineDescriptionValue text,
  bcSalesOrderLineDescription2 text,
  bcSalesOrderLineQuantityValue numeric,
  bcSalesOrderLineOutstandingQuantity numeric,
  bcSalesOrderLineQuantityShipped numeric,
  bcSalesOrderLineQuantityInvoiced numeric,
  bcSalesOrderLineUnitPrice numeric,
  bcSalesOrderLineUnitCost numeric,
  bcSalesOrderLineLineDiscount numeric,
  bcSalesOrderLineLineDiscountAmount numeric,
  bcSalesOrderLineAmountValue numeric,
  bcSalesOrderLineAmountIncludingVAT numeric,
  bcSalesOrderLineUnitOfMeasureCode text,
  bcSalesOrderLineLocationCode text,
  bcSalesOrderLineShortcutDimension1Code text,
  bcSalesOrderLineShortcutDimension2Code text,
  bcSalesOrderLineProfit numeric,
  bcSalesOrderLineVariantCode text,
  bcSalesOrderLineItemCategoryCode text,
  bcSalesOrderLineGenProdPostingGroup text,
  bcSalesOrderLineShipmentDate date,
  bcSalesOrderLineOutstandingAmount numeric,
  bcSalesOrderLineInvDiscountAmount numeric,
  bcSalesOrderLinePlannedDeliveryDate date,
  bcSalesOrderLinePlannedShipmentDate date,
  bcSalesOrderLineVAT numeric,
  bcSalesOrderLineLineAmount numeric,
  bcSalesOrderLineQtyToShip numeric,
  bcSalesOrderLineQtyToInvoice numeric,
  bcSalesOrderLineDropShipment boolean,
  bcSalesOrderLineBinCode text,
  bcSalesOrderLineCompletelyShipped boolean,
  bcSalesOrderLineCreatedAt timestamp with time zone,
  bcSalesOrderLineLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcSalesOrderLine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcSalesQuote (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcSalesQuoteNoValue text NOT NULL UNIQUE,
  bcSalesQuoteSellToCustomerNo text,
  bcSalesQuoteSellToCustomerName text,
  bcSalesQuoteOrderDate date,
  bcSalesQuoteDueDate date,
  bcSalesQuoteDocumentDate date,
  bcSalesQuoteAmountValue numeric,
  bcSalesQuoteAmountIncludingVAT numeric,
  bcSalesQuoteSalespersonCode text,
  bcSalesQuoteShortcutDimension1Code text,
  bcSalesQuoteShortcutDimension2Code text,
  bcSalesQuoteLocationCode text,
  bcSalesQuoteCurrencyCode text,
  bcSalesQuoteExternalDocumentNo text,
  bcSalesQuoteStatus text,
  bcSalesQuoteQuoteValidUntilDate date,
  bcSalesQuoteQuoteAccepted boolean,
  bcSalesQuoteQuoteAcceptedDate date,
  bcSalesQuoteOpportunityNo text,
  bcSalesQuoteAssignedUserID text,
  bcSalesQuoteCreatedAt timestamp with time zone,
  bcSalesQuoteLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcSalesQuote_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcSyncState (
  key text NOT NULL,
  value text,
  updatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcSyncState_pkey PRIMARY KEY (key)
);
CREATE TABLE public.bcValueEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcValueEntryEntryNo integer NOT NULL UNIQUE,
  bcValueEntryItemNo text,
  bcValueEntryPostingDate date,
  bcValueEntryDocumentNo text,
  bcValueEntryDocumentType text,
  bcValueEntryDescriptionValue text,
  bcValueEntryLocationCode text,
  bcValueEntryValuedQuantity numeric,
  bcValueEntryInvoicedQuantity numeric,
  bcValueEntryCostPerUnit numeric,
  bcValueEntryItemLedgerEntryNo integer,
  bcValueEntryItemLedgerEntryType text,
  bcValueEntryEntryType text,
  bcValueEntrySalespersPurchCode text,
  bcValueEntryDiscountAmount numeric,
  bcValueEntryGlobalDimension1Code text,
  bcValueEntryGlobalDimension2Code text,
  bcValueEntrySourceType text,
  bcValueEntrySourceNo text,
  bcValueEntryGenProdPostingGroup text,
  bcValueEntryOrderType text,
  bcValueEntryOrderNo text,
  bcValueEntryExpectedCost boolean,
  bcValueEntryCreatedAt timestamp with time zone,
  bcValueEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcValueEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcVendor (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcVendorNo text NOT NULL UNIQUE,
  bcVendorNameValue text,
  bcVendorAddress text,
  bcVendorAddress2 text,
  bcVendorCity text,
  bcVendorPostCode text,
  bcVendorContact text,
  bcVendorPhoneNo text,
  bcVendorEMail text,
  bcVendorMobilePhoneNo text,
  bcVendorVendorPostingGroup text,
  bcVendorPaymentTermsCode text,
  bcVendorPaymentMethodCode text,
  bcVendorPurchaserCode text,
  bcVendorGlobalDimension1Code text,
  bcVendorGlobalDimension2Code text,
  bcVendorBalanceLCY numeric,
  bcVendorBalanceDueLCY numeric,
  bcVendorVATRegistrationNo text,
  bcVendorGenBusPostingGroup text,
  bcVendorBlocked text,
  bcVendorCountryRegionCode text,
  bcVendorOutstandingOrders numeric,
  bcVendorOutstandingInvoices numeric,
  bcVendorPurchasesLCY numeric,
  bcVendorCreatedAt timestamp with time zone,
  bcVendorLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcVendor_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bcVendorLedgerEntry (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bcVendorLedgerEntryEntryNo integer NOT NULL UNIQUE,
  bcVendorLedgerEntryVendorNo text,
  bcVendorLedgerEntryVendorName text,
  bcVendorLedgerEntryPostingDate date,
  bcVendorLedgerEntryDocumentType text,
  bcVendorLedgerEntryDocumentNo text,
  bcVendorLedgerEntryDocumentDate date,
  bcVendorLedgerEntryDescription text,
  bcVendorLedgerEntryAmount numeric,
  bcVendorLedgerEntryAmountLCY numeric,
  bcVendorLedgerEntryRemainingAmount numeric,
  bcVendorLedgerEntryRemainingAmtLCY numeric,
  bcVendorLedgerEntryDueDate date,
  bcVendorLedgerEntryOpenValue text,
  bcVendorLedgerEntryPurchaseLCY numeric,
  bcVendorLedgerEntryPurchaserCode text,
  bcVendorLedgerEntryGlobalDimension1Code text,
  bcVendorLedgerEntryGlobalDimension2Code text,
  bcVendorLedgerEntryVendorPostingGroup text,
  bcVendorLedgerEntryBuyFromVendorNo text,
  bcVendorLedgerEntryCurrencyCode text,
  bcVendorLedgerEntryExternalDocumentNo text,
  bcVendorLedgerEntryCreatedAt timestamp with time zone,
  bcVendorLedgerEntryLastModifiedDateTime timestamp with time zone,
  bcSyncedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT bcVendorLedgerEntry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bciProject (
  bciProjectId uuid NOT NULL DEFAULT uuid_generate_v4(),
  bciProjectExternalId integer,
  bciProjectName text,
  bciProjectType text,
  bciProjectDescription text,
  bciProjectStreetName text,
  bciProjectCityOrTown text,
  bciProjectStateProvince text,
  bciProjectRegion text,
  bciProjectCountry text,
  bciProjectValue numeric,
  bciProjectCurrency text,
  bciProjectStage text,
  bciProjectStageStatus text,
  bciProjectDevelopmentType text,
  bciProjectOwnershipType text,
  bciProjectCategory text,
  bciProjectSubCategory text,
  bciProjectStoreys integer,
  bciProjectFloorArea numeric,
  bciProjectSiteArea numeric,
  bciProjectConstructionStartDate timestamp with time zone,
  bciProjectConstructionEndDate timestamp with time zone,
  bciProjectModifiedDate timestamp with time zone,
  bciProjectPublishedDate timestamp with time zone,
  bciProjectOwnerCompany text,
  bciProjectOwnerContact text,
  bciProjectOwnerPhone text,
  bciProjectOwnerEmail text,
  bciProjectArchitectCompany text,
  bciProjectArchitectContact text,
  bciProjectArchitectPhone text,
  bciProjectArchitectEmail text,
  bciProjectContractorCompany text,
  bciProjectContractorContact text,
  bciProjectContractorPhone text,
  bciProjectContractorEmail text,
  bciProjectPmCompany text,
  bciProjectPmContact text,
  bciProjectPmPhone text,
  bciProjectPmEmail text,
  bciProjectRemarks text,
  bciProjectMainContractorMethod text,
  bciProjectLat numeric,
  bciProjectLon numeric,
  bciProjectResearcher text,
  bciProjectCategoryId text,
  bciProjectSubCategoryId text,
  bciProjectStageId text,
  bciProjectDevelopmentTypeId text,
  bciProjectOwnershipTypeId text,
  bciProjectCountryId text,
  bciProjectRegionId text,
  bciProjectStateProvinceId text,
  bciProjectSyncedAt timestamp with time zone DEFAULT now(),
  bciProjectVersion integer DEFAULT 0,
  CONSTRAINT bciProject_pkey PRIMARY KEY (bciProjectId)
);
CREATE TABLE public.hrDepartment (
  hrDepartmentId uuid NOT NULL DEFAULT uuid_generate_v4(),
  hrDepartmentName text NOT NULL,
  hrDepartmentDescription text,
  hrDepartmentDivision text,
  hrDepartmentCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT hrDepartment_pkey PRIMARY KEY (hrDepartmentId)
);
CREATE TABLE public.hrDivision (
  hrDivisionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  hrDivisionName text NOT NULL,
  hrDivisionDescription text,
  hrDivisionCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT hrDivision_pkey PRIMARY KEY (hrDivisionId)
);
CREATE TABLE public.hrEmployee (
  hrEmployeeId uuid NOT NULL DEFAULT uuid_generate_v4(),
  hrEmployeeFirstName text,
  hrEmployeeLastName text,
  hrEmployeeEmail text,
  hrEmployeePhone text,
  hrEmployeeDivision text,
  hrEmployeeDepartment text,
  hrEmployeePosition text,
  hrEmployeeUserId uuid,
  hrEmployeeCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT hrEmployee_pkey PRIMARY KEY (hrEmployeeId)
);
CREATE TABLE public.hrPosition (
  hrPositionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  hrPositionTitle text NOT NULL,
  hrPositionDescription text,
  hrPositionDepartment text,
  hrPositionCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT hrPosition_pkey PRIMARY KEY (hrPositionId)
);
CREATE TABLE public.itAsset (
  itAssetId uuid NOT NULL DEFAULT uuid_generate_v4(),
  itAssetName text,
  itAssetTag text,
  itAssetCategory text DEFAULT 'computer'::text,
  itAssetBrand text,
  itAssetModel text,
  itAssetSerialNumber text,
  itAssetStatus text DEFAULT 'active'::text,
  itAssetAssignedTo text,
  itAssetPurchaseDate date,
  itAssetWarrantyExpiry date,
  itAssetCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  itAssetLocation text,
  itAssetNotes text,
  CONSTRAINT itAsset_pkey PRIMARY KEY (itAssetId)
);
CREATE TABLE public.itDevProgressLog (
  itDevProgressLogId uuid NOT NULL DEFAULT uuid_generate_v4(),
  itDevProgressLogRequestId uuid,
  itDevProgressLogProgress integer DEFAULT 0,
  itDevProgressLogDescription text,
  itDevProgressLogCreatedBy text,
  itDevProgressLogCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT itDevProgressLog_pkey PRIMARY KEY (itDevProgressLogId),
  CONSTRAINT itDevProgressLog_itDevProgressLogRequestId_fkey FOREIGN KEY (itDevProgressLogRequestId) REFERENCES public.itDevRequest(itDevRequestId)
);
CREATE TABLE public.itDevRequest (
  itDevRequestId uuid NOT NULL DEFAULT uuid_generate_v4(),
  itDevRequestNo text,
  itDevRequestTitle text,
  itDevRequestDescription text,
  itDevRequestRequestedBy text,
  itDevRequestAssignedTo text,
  itDevRequestStatus text DEFAULT 'pending'::text,
  itDevRequestProgress integer DEFAULT 0,
  itDevRequestDueDate date,
  itDevRequestCompletedAt timestamp with time zone,
  itDevRequestCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  itDevRequestPriority text DEFAULT 'medium'::text,
  itDevRequestStartDate date,
  itDevRequestNotes text,
  CONSTRAINT itDevRequest_pkey PRIMARY KEY (itDevRequestId)
);
CREATE TABLE public.labelDesign (
  labelDesignId uuid NOT NULL DEFAULT gen_random_uuid(),
  labelDesignName text NOT NULL,
  labelDesignWidth numeric DEFAULT 100,
  labelDesignHeight numeric DEFAULT 30,
  labelDesignPreset text DEFAULT 'custom'::text,
  labelDesignElements jsonb DEFAULT '[]'::jsonb,
  labelDesignCreatedBy uuid,
  labelDesignCreatedAt timestamp with time zone DEFAULT now(),
  labelDesignUpdatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT labelDesign_pkey PRIMARY KEY (labelDesignId),
  CONSTRAINT labelDesign_labelDesignCreatedBy_fkey FOREIGN KEY (labelDesignCreatedBy) REFERENCES auth.users(id)
);
CREATE TABLE public.mktGeneratedImage (
  mktGeneratedImageId uuid NOT NULL DEFAULT gen_random_uuid(),
  mktGeneratedImagePrompt text NOT NULL,
  mktGeneratedImageOriginalUrl text NOT NULL,
  mktGeneratedImageResultUrl text NOT NULL,
  mktGeneratedImageSize character varying DEFAULT '1024x1024'::character varying,
  mktGeneratedImageCreatedBy uuid NOT NULL,
  mktGeneratedImageCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean DEFAULT true,
  CONSTRAINT mktGeneratedImage_pkey PRIMARY KEY (mktGeneratedImageId),
  CONSTRAINT mktGeneratedImage_mktGeneratedImageCreatedBy_fkey FOREIGN KEY (mktGeneratedImageCreatedBy) REFERENCES auth.users(id)
);
CREATE TABLE public.mktWorkOrder (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  mktWorkOrderNo text NOT NULL UNIQUE,
  mktWorkOrderTitle text NOT NULL,
  mktWorkOrderDescription text,
  mktWorkOrderType text,
  mktWorkOrderRequestedBy text,
  mktWorkOrderAssignedTo text,
  mktWorkOrderPriority text DEFAULT 'medium'::text,
  mktWorkOrderStatus text DEFAULT 'pending'::text,
  mktWorkOrderProgress integer DEFAULT 0,
  mktWorkOrderStartDate date,
  mktWorkOrderDueDate date,
  mktWorkOrderCompletedAt timestamp with time zone,
  mktWorkOrderNotes text,
  mktWorkOrderCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean DEFAULT true,
  CONSTRAINT mktWorkOrder_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mktWorkOrderProgressLog (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  mktWorkOrderProgressLogWorkOrderId bigint,
  mktWorkOrderProgressLogDescription text NOT NULL,
  mktWorkOrderProgressLogProgress integer NOT NULL,
  mktWorkOrderProgressLogCreatedBy text,
  mktWorkOrderProgressLogCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT mktWorkOrderProgressLog_pkey PRIMARY KEY (id),
  CONSTRAINT mktWorkOrderProgressLog_mktWorkOrderProgressLogWorkOrderId_fkey FOREIGN KEY (mktWorkOrderProgressLogWorkOrderId) REFERENCES public.mktWorkOrder(id)
);
CREATE TABLE public.omAiSetting (
  omAiSettingId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omAiSettingSystemPrompt text,
  omAiSettingModel text DEFAULT 'google/gemini-2.5-flash-lite'::text,
  omAiSettingTemperature numeric DEFAULT 0.3,
  omAiSettingMaxHistoryMessages integer DEFAULT 20,
  omAiSettingBankAccountInfo text,
  omAiSettingUpdatedAt timestamp with time zone DEFAULT now(),
  omAiSettingCreatedAt timestamp with time zone DEFAULT now(),
  omAiSettingShippingInfo text,
  omAiSettingAfterSalesInfo text,
  omAiSettingBrandStory text,
  CONSTRAINT omAiSetting_pkey PRIMARY KEY (omAiSettingId)
);
CREATE TABLE public.omChannel (
  omChannelId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omChannelType text UNIQUE,
  omChannelName text,
  omChannelAccessToken text,
  omChannelPageId text,
  omChannelSecret text,
  omChannelStatus text DEFAULT 'inactive'::text,
  omChannelCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT omChannel_pkey PRIMARY KEY (omChannelId)
);
CREATE TABLE public.omContact (
  omContactId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omContactChannelType text,
  omContactExternalId text,
  omContactDisplayName text,
  omContactAvatarUrl text,
  omContactNotes text,
  omContactCreatedAt timestamp with time zone DEFAULT now(),
  omContactTags jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT omContact_pkey PRIMARY KEY (omContactId)
);
CREATE TABLE public.omConversation (
  omConversationId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omConversationContactId uuid,
  omConversationChannelType text,
  omConversationStatus text DEFAULT 'open'::text,
  omConversationLastMessageAt timestamp with time zone,
  omConversationLastMessagePreview text,
  omConversationUnreadCount integer DEFAULT 0,
  omConversationAiAutoReply boolean DEFAULT true,
  omConversationAssignedTo text,
  omConversationCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT omConversation_pkey PRIMARY KEY (omConversationId),
  CONSTRAINT omConversation_omConversationContactId_fkey FOREIGN KEY (omConversationContactId) REFERENCES public.omContact(omContactId)
);
CREATE TABLE public.omFollowUp (
  omFollowUpId uuid NOT NULL DEFAULT gen_random_uuid(),
  omFollowUpConversationId uuid NOT NULL,
  omFollowUpScheduledAt timestamp with time zone NOT NULL,
  omFollowUpMessage text,
  omFollowUpStatus text NOT NULL DEFAULT 'pending'::text,
  omFollowUpSentAt timestamp with time zone,
  omFollowUpCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT omFollowUp_pkey PRIMARY KEY (omFollowUpId),
  CONSTRAINT omFollowUp_omFollowUpConversationId_fkey FOREIGN KEY (omFollowUpConversationId) REFERENCES public.omConversation(omConversationId)
);
CREATE TABLE public.omMessage (
  omMessageId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omMessageConversationId uuid,
  omMessageSenderType text,
  omMessageSenderId text,
  omMessageContent text,
  omMessageType text DEFAULT 'text'::text,
  omMessageExternalId text,
  omMessageMetadata jsonb,
  omMessageImageUrl text,
  omMessageIsAi boolean DEFAULT false,
  omMessageOcrData jsonb,
  omMessageCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT omMessage_pkey PRIMARY KEY (omMessageId),
  CONSTRAINT omMessage_omMessageConversationId_fkey FOREIGN KEY (omMessageConversationId) REFERENCES public.omConversation(omConversationId)
);
CREATE TABLE public.omPriceItem (
  omPriceItemId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omPriceItemNumber text UNIQUE,
  omPriceItemName text,
  omPriceItemUnitPrice numeric DEFAULT 0,
  omPriceItemUpdatedAt timestamp with time zone DEFAULT now(),
  omPriceItemUpdatedBy uuid,
  CONSTRAINT omPriceItem_pkey PRIMARY KEY (omPriceItemId)
);
CREATE TABLE public.omProductInfo (
  omProductInfoId uuid NOT NULL DEFAULT gen_random_uuid(),
  omProductInfoItemNumber text NOT NULL UNIQUE,
  omProductInfoDescription text,
  omProductInfoHighlights text,
  omProductInfoImageUrl text,
  omProductInfoCategory text,
  omProductInfoUpdatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT omProductInfo_pkey PRIMARY KEY (omProductInfoId)
);
CREATE TABLE public.omPromotion (
  omPromotionId uuid NOT NULL DEFAULT gen_random_uuid(),
  omPromotionName text NOT NULL,
  omPromotionDescription text,
  omPromotionType text NOT NULL DEFAULT 'discount_percent'::text,
  omPromotionValue numeric DEFAULT 0,
  omPromotionMinQuantity integer DEFAULT 1,
  omPromotionApplicableProducts jsonb DEFAULT '[]'::jsonb,
  omPromotionStartDate date,
  omPromotionEndDate date,
  omPromotionIsActive boolean DEFAULT true,
  omPromotionCreatedAt timestamp with time zone DEFAULT now(),
  omPromotionUpdatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT omPromotion_pkey PRIMARY KEY (omPromotionId)
);
CREATE TABLE public.omQuotation (
  omQuotationId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omQuotationConversationId uuid,
  omQuotationContactId uuid,
  omQuotationNumber text,
  omQuotationStatus text DEFAULT 'draft'::text,
  omQuotationCustomerName text,
  omQuotationCustomerPhone text,
  omQuotationCustomerAddress text,
  omQuotationPaymentMethod text,
  omQuotationNotes text,
  omQuotationSubmittedBy uuid,
  omQuotationApprovedBy uuid,
  omQuotationApprovalNote text,
  omQuotationUpdatedAt timestamp with time zone,
  omQuotationCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT omQuotation_pkey PRIMARY KEY (omQuotationId),
  CONSTRAINT omQuotation_omQuotationConversationId_fkey FOREIGN KEY (omQuotationConversationId) REFERENCES public.omConversation(omConversationId),
  CONSTRAINT omQuotation_omQuotationContactId_fkey FOREIGN KEY (omQuotationContactId) REFERENCES public.omContact(omContactId)
);
CREATE TABLE public.omQuotationLine (
  omQuotationLineId uuid NOT NULL DEFAULT uuid_generate_v4(),
  omQuotationLineQuotationId uuid,
  omQuotationLineOrder integer,
  omQuotationLineProductName text,
  omQuotationLineVariant text,
  omQuotationLineQuantity numeric DEFAULT 0,
  omQuotationLineUnitPrice numeric DEFAULT 0,
  omQuotationLineAmount numeric DEFAULT 0,
  CONSTRAINT omQuotationLine_pkey PRIMARY KEY (omQuotationLineId),
  CONSTRAINT omQuotationLine_omQuotationLineQuotationId_fkey FOREIGN KEY (omQuotationLineQuotationId) REFERENCES public.omQuotation(omQuotationId)
);
CREATE TABLE public.omRelatedProduct (
  omRelatedProductId uuid NOT NULL DEFAULT gen_random_uuid(),
  omRelatedProductSourceItem text NOT NULL,
  omRelatedProductTargetItem text NOT NULL,
  omRelatedProductType text NOT NULL DEFAULT 'cross_sell'::text,
  omRelatedProductReason text,
  omRelatedProductCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT omRelatedProduct_pkey PRIMARY KEY (omRelatedProductId)
);
CREATE TABLE public.perf360Competency (
  perf360CompetencyId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perf360CompetencyCycleId uuid,
  perf360CompetencyName text,
  perf360CompetencyDescription text,
  perf360CompetencyQuestions jsonb,
  perf360CompetencyWeight numeric DEFAULT 1,
  perf360CompetencySortOrder integer DEFAULT 0,
  CONSTRAINT perf360Competency_pkey PRIMARY KEY (perf360CompetencyId),
  CONSTRAINT perf360Competency_perf360CompetencyCycleId_fkey FOREIGN KEY (perf360CompetencyCycleId) REFERENCES public.perf360Cycle(perf360CycleId)
);
CREATE TABLE public.perf360Cycle (
  perf360CycleId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perf360CycleName text,
  perf360CycleDescription text,
  perf360CycleYear integer,
  perf360CycleQuarter integer,
  perf360CycleStatus text DEFAULT 'active'::text,
  perf360CycleResponseDeadline date,
  perf360CycleAnonymousToReviewee boolean DEFAULT true,
  perf360CycleCreatedBy uuid,
  perf360CycleCreatedAt timestamp with time zone DEFAULT now(),
  perf360CycleUpdatedAt timestamp with time zone,
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT perf360Cycle_pkey PRIMARY KEY (perf360CycleId)
);
CREATE TABLE public.perf360Nomination (
  perf360NominationId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perf360NominationCycleId uuid,
  perf360NominationRevieweeEmployeeId text,
  perf360NominationReviewerEmployeeId text,
  perf360NominationRelationshipType text,
  perf360NominationStatus text DEFAULT 'pending'::text,
  perf360NominationCompletedAt timestamp with time zone,
  perf360NominationCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT perf360Nomination_pkey PRIMARY KEY (perf360NominationId),
  CONSTRAINT perf360Nomination_perf360NominationCycleId_fkey FOREIGN KEY (perf360NominationCycleId) REFERENCES public.perf360Cycle(perf360CycleId)
);
CREATE TABLE public.perf360Response (
  perf360ResponseId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perf360ResponseNominationId uuid,
  perf360ResponseCycleId uuid,
  perf360ResponseRevieweeEmployeeId text,
  perf360ResponseReviewerEmployeeId text,
  perf360ResponseRelationshipType text,
  perf360ResponseScores jsonb,
  perf360ResponseCompetencyAverages jsonb,
  perf360ResponseOverallScore numeric,
  perf360ResponseStrengthComment text,
  perf360ResponseImprovementComment text,
  perf360ResponseComment text,
  CONSTRAINT perf360Response_pkey PRIMARY KEY (perf360ResponseId),
  CONSTRAINT perf360Response_perf360ResponseNominationId_fkey FOREIGN KEY (perf360ResponseNominationId) REFERENCES public.perf360Nomination(perf360NominationId),
  CONSTRAINT perf360Response_perf360ResponseCycleId_fkey FOREIGN KEY (perf360ResponseCycleId) REFERENCES public.perf360Cycle(perf360CycleId)
);
CREATE TABLE public.perfEvaluation (
  perfEvaluationId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfEvaluationEvaluatorId uuid,
  perfEvaluationEvaluateeEmployeeId text,
  perfEvaluationPeriod text,
  perfEvaluationYear integer,
  perfEvaluationQuarter integer,
  perfEvaluationScores jsonb,
  perfEvaluationCategoryAverages jsonb,
  perfEvaluationOverallScore numeric,
  perfEvaluationGrade text,
  perfEvaluationComment text,
  perfEvaluationCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT perfEvaluation_pkey PRIMARY KEY (perfEvaluationId)
);
CREATE TABLE public.perfEvaluationFeedback (
  perfEvaluationFeedbackId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfEvaluationFeedbackEmployeeId text,
  perfEvaluationFeedbackPeriod text,
  perfEvaluationFeedbackCategoryAverages jsonb,
  perfEvaluationFeedbackOverallScore numeric,
  perfEvaluationFeedbackGrade text,
  perfEvaluationFeedbackCompanyAverages jsonb,
  perfEvaluationFeedbackEvaluatorCount integer,
  perfEvaluationFeedbackFeedback text,
  perfEvaluationFeedbackGeneratedBy uuid,
  perfEvaluationFeedbackCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT perfEvaluationFeedback_pkey PRIMARY KEY (perfEvaluationFeedbackId)
);
CREATE TABLE public.perfKpiAssignment (
  perfKpiAssignmentId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfKpiAssignmentDefinitionId uuid,
  perfKpiAssignmentEmployeeId text,
  perfKpiAssignmentYear integer,
  perfKpiAssignmentTargetValue numeric,
  perfKpiAssignmentWeight numeric DEFAULT 1,
  perfKpiAssignmentCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT perfKpiAssignment_pkey PRIMARY KEY (perfKpiAssignmentId),
  CONSTRAINT perfKpiAssignment_perfKpiAssignmentDefinitionId_fkey FOREIGN KEY (perfKpiAssignmentDefinitionId) REFERENCES public.perfKpiDefinition(perfKpiDefinitionId)
);
CREATE TABLE public.perfKpiDefinition (
  perfKpiDefinitionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfKpiDefinitionName text,
  perfKpiDefinitionDescription text,
  perfKpiDefinitionCategory text DEFAULT 'general'::text,
  perfKpiDefinitionUnit text,
  perfKpiDefinitionFrequency text DEFAULT 'monthly'::text,
  perfKpiDefinitionTargetValue numeric,
  perfKpiDefinitionWarningThreshold numeric,
  perfKpiDefinitionCriticalThreshold numeric,
  perfKpiDefinitionHigherIsBetter boolean DEFAULT true,
  perfKpiDefinitionIsActive boolean DEFAULT true,
  perfKpiDefinitionCreatedBy uuid,
  perfKpiDefinitionCreatedAt timestamp with time zone DEFAULT now(),
  perfKpiDefinitionUpdatedAt timestamp with time zone,
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT perfKpiDefinition_pkey PRIMARY KEY (perfKpiDefinitionId)
);
CREATE TABLE public.perfKpiRecord (
  perfKpiRecordId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfKpiRecordAssignmentId uuid,
  perfKpiRecordPeriodLabel text,
  perfKpiRecordActualValue numeric,
  perfKpiRecordNote text,
  perfKpiRecordRecordedBy uuid,
  CONSTRAINT perfKpiRecord_pkey PRIMARY KEY (perfKpiRecordId),
  CONSTRAINT perfKpiRecord_perfKpiRecordAssignmentId_fkey FOREIGN KEY (perfKpiRecordAssignmentId) REFERENCES public.perfKpiAssignment(perfKpiAssignmentId)
);
CREATE TABLE public.perfOkrCheckin (
  perfOkrCheckinId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfOkrCheckinKeyResultId uuid,
  perfOkrCheckinPreviousValue numeric,
  perfOkrCheckinNewValue numeric,
  perfOkrCheckinNote text,
  perfOkrCheckinCreatedBy uuid,
  perfOkrCheckinCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT perfOkrCheckin_pkey PRIMARY KEY (perfOkrCheckinId),
  CONSTRAINT perfOkrCheckin_perfOkrCheckinKeyResultId_fkey FOREIGN KEY (perfOkrCheckinKeyResultId) REFERENCES public.perfOkrKeyResult(perfOkrKeyResultId)
);
CREATE TABLE public.perfOkrKeyResult (
  perfOkrKeyResultId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfOkrKeyResultObjectiveId uuid,
  perfOkrKeyResultTitle text,
  perfOkrKeyResultMetricType text DEFAULT 'number'::text,
  perfOkrKeyResultStartValue numeric DEFAULT 0,
  perfOkrKeyResultTargetValue numeric DEFAULT 100,
  perfOkrKeyResultCurrentValue numeric DEFAULT 0,
  perfOkrKeyResultUnit text,
  perfOkrKeyResultWeight numeric DEFAULT 1,
  perfOkrKeyResultSortOrder integer DEFAULT 0,
  perfOkrKeyResultStatus text DEFAULT 'not_started'::text,
  perfOkrKeyResultUpdatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT perfOkrKeyResult_pkey PRIMARY KEY (perfOkrKeyResultId),
  CONSTRAINT perfOkrKeyResult_perfOkrKeyResultObjectiveId_fkey FOREIGN KEY (perfOkrKeyResultObjectiveId) REFERENCES public.perfOkrObjective(perfOkrObjectiveId)
);
CREATE TABLE public.perfOkrObjective (
  perfOkrObjectiveId uuid NOT NULL DEFAULT uuid_generate_v4(),
  perfOkrObjectiveEmployeeId text,
  perfOkrObjectiveTitle text,
  perfOkrObjectiveDescription text,
  perfOkrObjectiveYear integer,
  perfOkrObjectiveQuarter integer,
  perfOkrObjectivePeriod text,
  perfOkrObjectiveVisibility text DEFAULT 'team'::text,
  perfOkrObjectiveStatus text DEFAULT 'active'::text,
  perfOkrObjectiveParentObjectiveId uuid,
  perfOkrObjectiveProgress numeric DEFAULT 0,
  perfOkrObjectiveCreatedBy uuid,
  perfOkrObjectiveCreatedAt timestamp with time zone DEFAULT now(),
  perfOkrObjectiveUpdatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT perfOkrObjective_pkey PRIMARY KEY (perfOkrObjectiveId),
  CONSTRAINT perfOkrObjective_perfOkrObjectiveParentObjectiveId_fkey FOREIGN KEY (perfOkrObjectiveParentObjectiveId) REFERENCES public.perfOkrObjective(perfOkrObjectiveId)
);
CREATE TABLE public.rbacAccessLog (
  rbacAccessLogId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacAccessLogUserId uuid,
  rbacAccessLogResource text,
  rbacAccessLogAction text,
  rbacAccessLogGranted boolean DEFAULT false,
  rbacAccessLogMetadata jsonb,
  rbacAccessLogCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT rbacAccessLog_pkey PRIMARY KEY (rbacAccessLogId)
);
CREATE TABLE public.rbacAction (
  rbacActionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacActionName text NOT NULL,
  rbacActionDescription text,
  rbacActionCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacAction_pkey PRIMARY KEY (rbacActionId)
);
CREATE TABLE public.rbacPermission (
  rbacPermissionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacPermissionResourceId uuid,
  rbacPermissionActionId uuid,
  rbacPermissionCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacPermission_pkey PRIMARY KEY (rbacPermissionId),
  CONSTRAINT rbacPermission_rbacPermissionResourceId_fkey FOREIGN KEY (rbacPermissionResourceId) REFERENCES public.rbacResource(rbacResourceId),
  CONSTRAINT rbacPermission_rbacPermissionActionId_fkey FOREIGN KEY (rbacPermissionActionId) REFERENCES public.rbacAction(rbacActionId)
);
CREATE TABLE public.rbacResource (
  rbacResourceId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacResourceName text NOT NULL,
  rbacResourceDescription text,
  rbacResourceModuleId text,
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacResource_pkey PRIMARY KEY (rbacResourceId)
);
CREATE TABLE public.rbacRole (
  rbacRoleId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacRoleName text NOT NULL,
  rbacRoleDescription text,
  rbacRoleIsSuperadmin boolean DEFAULT false,
  rbacRoleCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacRole_pkey PRIMARY KEY (rbacRoleId)
);
CREATE TABLE public.rbacRolePermission (
  rbacRolePermissionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacRolePermissionRoleId uuid NOT NULL,
  rbacRolePermissionPermissionId uuid NOT NULL,
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacRolePermission_pkey PRIMARY KEY (rbacRolePermissionId),
  CONSTRAINT rbacRolePermission_rbacRolePermissionRoleId_fkey FOREIGN KEY (rbacRolePermissionRoleId) REFERENCES public.rbacRole(rbacRoleId),
  CONSTRAINT rbacRolePermission_rbacRolePermissionPermissionId_fkey FOREIGN KEY (rbacRolePermissionPermissionId) REFERENCES public.rbacPermission(rbacPermissionId)
);
CREATE TABLE public.rbacUserProfile (
  rbacUserProfileId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacUserProfileEmail text,
  rbacUserProfileCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacUserProfile_pkey PRIMARY KEY (rbacUserProfileId)
);
CREATE TABLE public.rbacUserRole (
  rbacUserRoleId uuid NOT NULL DEFAULT uuid_generate_v4(),
  rbacUserRoleUserId uuid NOT NULL,
  rbacUserRoleRoleId uuid NOT NULL,
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT rbacUserRole_pkey PRIMARY KEY (rbacUserRoleId),
  CONSTRAINT rbacUserRole_rbacUserRoleRoleId_fkey FOREIGN KEY (rbacUserRoleRoleId) REFERENCES public.rbacRole(rbacRoleId)
);
CREATE TABLE public.salesAccount (
  crmAccountId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmAccountName text,
  crmAccountIndustry text,
  crmAccountEmail text,
  crmAccountPhone text,
  crmAccountWebsite text,
  crmAccountAddress text,
  crmAccountCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  crmAccountAnnualRevenue numeric DEFAULT 0,
  crmAccountEmployees integer,
  crmAccountNo text,
  crmAccountNotes text,
  CONSTRAINT salesAccount_pkey PRIMARY KEY (crmAccountId)
);
CREATE TABLE public.salesActivity (
  crmActivityId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmActivityType text,
  crmActivityStatus text DEFAULT 'pending'::text,
  crmActivitySubject text,
  crmActivityDueDate date,
  crmActivityContactId uuid,
  crmActivityOpportunityId uuid,
  crmActivityAccountId uuid,
  crmActivityCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  crmActivityAssignedTo text,
  crmActivityCompletedAt timestamp with time zone,
  crmActivityDescription text,
  crmActivityPriority text DEFAULT 'medium'::text,
  CONSTRAINT salesActivity_pkey PRIMARY KEY (crmActivityId),
  CONSTRAINT crmActivity_crmActivityContactId_fkey FOREIGN KEY (crmActivityContactId) REFERENCES public.salesContact(crmContactId),
  CONSTRAINT crmActivity_crmActivityOpportunityId_fkey FOREIGN KEY (crmActivityOpportunityId) REFERENCES public.salesOpportunity(crmOpportunityId),
  CONSTRAINT crmActivity_crmActivityAccountId_fkey FOREIGN KEY (crmActivityAccountId) REFERENCES public.salesAccount(crmAccountId)
);
CREATE TABLE public.salesContact (
  crmContactId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmContactFirstName text,
  crmContactLastName text,
  crmContactEmail text,
  crmContactPhone text,
  crmContactPosition text,
  crmContactAccountId uuid,
  crmContactNotes text,
  crmContactCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  crmContactAddress text,
  crmContactName text,
  crmContactNo text,
  crmContactTags jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT salesContact_pkey PRIMARY KEY (crmContactId),
  CONSTRAINT crmContact_crmContactAccountId_fkey FOREIGN KEY (crmContactAccountId) REFERENCES public.salesAccount(crmAccountId)
);
CREATE TABLE public.salesLead (
  crmLeadId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmLeadNo text,
  crmLeadName text,
  crmLeadEmail text,
  crmLeadPhone text,
  crmLeadCompany text,
  crmLeadPosition text,
  crmLeadSource text,
  crmLeadScore text DEFAULT 'warm'::text,
  crmLeadStatus text DEFAULT 'new'::text,
  crmLeadAssignedTo text,
  crmLeadNotes text,
  crmLeadConvertedContactId uuid,
  crmLeadConvertedOpportunityId uuid,
  crmLeadCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT salesLead_pkey PRIMARY KEY (crmLeadId),
  CONSTRAINT crmLead_crmLeadConvertedContactId_fkey FOREIGN KEY (crmLeadConvertedContactId) REFERENCES public.salesContact(crmContactId),
  CONSTRAINT crmLead_convertedOpp_fkey FOREIGN KEY (crmLeadConvertedOpportunityId) REFERENCES public.salesOpportunity(crmOpportunityId)
);
CREATE TABLE public.salesOpportunity (
  crmOpportunityId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmOpportunityName text,
  crmOpportunityStage text DEFAULT 'prospecting'::text,
  crmOpportunityAmount numeric DEFAULT 0,
  crmOpportunityProbability integer DEFAULT 0,
  crmOpportunityExpectedCloseDate date,
  crmOpportunityActualCloseDate date,
  crmOpportunityContactId uuid,
  crmOpportunityAccountId uuid,
  crmOpportunityAssignedTo text,
  crmOpportunitySource text,
  crmOpportunityNotes text,
  crmOpportunityCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  crmOpportunityLostReason text,
  crmOpportunityNo text,
  CONSTRAINT salesOpportunity_pkey PRIMARY KEY (crmOpportunityId),
  CONSTRAINT crmOpportunity_crmOpportunityContactId_fkey FOREIGN KEY (crmOpportunityContactId) REFERENCES public.salesContact(crmContactId),
  CONSTRAINT crmOpportunity_crmOpportunityAccountId_fkey FOREIGN KEY (crmOpportunityAccountId) REFERENCES public.salesAccount(crmAccountId)
);
CREATE TABLE public.salesOrder (
  crmOrderId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmOrderNo text,
  crmOrderQuotationId uuid,
  crmOrderOpportunityId uuid,
  crmOrderContactId uuid,
  crmOrderAccountId uuid,
  crmOrderStatus text DEFAULT 'pending'::text,
  crmOrderSubtotal numeric DEFAULT 0,
  crmOrderDiscount numeric DEFAULT 0,
  crmOrderTax numeric DEFAULT 0,
  crmOrderTotal numeric DEFAULT 0,
  crmOrderShippingAddress text,
  crmOrderTrackingNumber text,
  crmOrderNotes text,
  crmOrderCreatedBy text,
  crmOrderCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  crmOrderDeliveryDate date,
  CONSTRAINT salesOrder_pkey PRIMARY KEY (crmOrderId),
  CONSTRAINT crmOrder_crmOrderQuotationId_fkey FOREIGN KEY (crmOrderQuotationId) REFERENCES public.salesQuotation(crmQuotationId),
  CONSTRAINT crmOrder_crmOrderOpportunityId_fkey FOREIGN KEY (crmOrderOpportunityId) REFERENCES public.salesOpportunity(crmOpportunityId),
  CONSTRAINT crmOrder_crmOrderContactId_fkey FOREIGN KEY (crmOrderContactId) REFERENCES public.salesContact(crmContactId),
  CONSTRAINT crmOrder_crmOrderAccountId_fkey FOREIGN KEY (crmOrderAccountId) REFERENCES public.salesAccount(crmAccountId)
);
CREATE TABLE public.salesPipelineStage (
  crmPipelineStageId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmPipelineStageName text,
  crmPipelineStageColor text,
  crmPipelineStageOrder integer,
  crmPipelineStageCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT salesPipelineStage_pkey PRIMARY KEY (crmPipelineStageId)
);
CREATE TABLE public.salesQuotation (
  crmQuotationId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmQuotationNo text,
  crmQuotationStatus text DEFAULT 'draft'::text,
  crmQuotationOpportunityId uuid,
  crmQuotationContactId uuid,
  crmQuotationAccountId uuid,
  crmQuotationSubtotal numeric DEFAULT 0,
  crmQuotationDiscount numeric DEFAULT 0,
  crmQuotationTax numeric DEFAULT 0,
  crmQuotationTotal numeric DEFAULT 0,
  crmQuotationApprovedBy text,
  crmQuotationApprovalNote text,
  crmQuotationNotes text,
  crmQuotationCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  crmQuotationTerms text,
  crmQuotationValidUntil date,
  CONSTRAINT salesQuotation_pkey PRIMARY KEY (crmQuotationId),
  CONSTRAINT crmQuotation_crmQuotationOpportunityId_fkey FOREIGN KEY (crmQuotationOpportunityId) REFERENCES public.salesOpportunity(crmOpportunityId),
  CONSTRAINT crmQuotation_crmQuotationContactId_fkey FOREIGN KEY (crmQuotationContactId) REFERENCES public.salesContact(crmContactId),
  CONSTRAINT crmQuotation_crmQuotationAccountId_fkey FOREIGN KEY (crmQuotationAccountId) REFERENCES public.salesAccount(crmAccountId)
);
CREATE TABLE public.salesQuotationLine (
  crmQuotationLineId uuid NOT NULL DEFAULT uuid_generate_v4(),
  crmQuotationLineQuotationId uuid,
  crmQuotationLineOrder integer,
  crmQuotationLineProductName text,
  crmQuotationLineDescription text,
  crmQuotationLineQuantity numeric DEFAULT 0,
  crmQuotationLineUnitPrice numeric DEFAULT 0,
  crmQuotationLineDiscount numeric DEFAULT 0,
  crmQuotationLineAmount numeric DEFAULT 0,
  isActive boolean NOT NULL DEFAULT true,
  CONSTRAINT salesQuotationLine_pkey PRIMARY KEY (crmQuotationLineId),
  CONSTRAINT crmQuotationLine_crmQuotationLineQuotationId_fkey FOREIGN KEY (crmQuotationLineQuotationId) REFERENCES public.salesQuotation(crmQuotationId)
);
CREATE TABLE public.tmsDelivery (
  tmsDeliveryId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsDeliveryShipmentId uuid,
  tmsDeliveryStatus text DEFAULT 'pending'::text,
  tmsDeliveryCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  tmsDeliveryNotes text,
  tmsDeliverySignatureUrl text,
  tmsDeliveryPhotoUrls jsonb,
  tmsDeliveryReceiverName text,
  tmsDeliveryReceiverPhone text,
  tmsDeliveryReceivedAt timestamp with time zone,
  CONSTRAINT tmsDelivery_pkey PRIMARY KEY (tmsDeliveryId),
  CONSTRAINT tmsDelivery_tmsDeliveryShipmentId_fkey FOREIGN KEY (tmsDeliveryShipmentId) REFERENCES public.tmsShipment(tmsShipmentId)
);
CREATE TABLE public.tmsDeliveryItem (
  tmsDeliveryItemId bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  tmsDeliveryItemDeliveryId uuid NOT NULL,
  tmsDeliveryItemDescription text NOT NULL,
  tmsDeliveryItemUom text,
  tmsDeliveryItemPlannedQty numeric NOT NULL DEFAULT 0,
  tmsDeliveryItemDeliveredQty numeric NOT NULL DEFAULT 0,
  tmsDeliveryItemDamagedQty numeric NOT NULL DEFAULT 0,
  tmsDeliveryItemReturnedQty numeric NOT NULL DEFAULT 0,
  tmsDeliveryItemDamageNotes text,
  tmsDeliveryItemSoNo text,
  tmsDeliveryItemCreatedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT tmsDeliveryItem_pkey PRIMARY KEY (tmsDeliveryItemId),
  CONSTRAINT tmsDeliveryItem_tmsDeliveryItemDeliveryId_fkey FOREIGN KEY (tmsDeliveryItemDeliveryId) REFERENCES public.tmsDelivery(tmsDeliveryId)
);
CREATE TABLE public.tmsDeliveryPlan (
  tmsDeliveryPlanId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsDeliveryPlanDate date NOT NULL,
  tmsDeliveryPlanStatus text DEFAULT 'planned'::text,
  tmsDeliveryPlanNotes text,
  tmsDeliveryPlanCreatedBy uuid,
  tmsDeliveryPlanCreatedAt timestamp with time zone DEFAULT now(),
  tmsDeliveryPlanUpdatedAt timestamp with time zone DEFAULT now(),
  tmsDeliveryPlanPriority text DEFAULT 'normal'::text,
  tmsDeliveryPlanAddress text,
  tmsDeliveryPlanLat numeric,
  tmsDeliveryPlanLng numeric,
  tmsDeliveryPlanShipmentId uuid,
  tmsDeliveryPlanShipmentNumber text,
  tmsDeliveryPlanSequence integer,
  CONSTRAINT tmsDeliveryPlan_pkey PRIMARY KEY (tmsDeliveryPlanId)
);
CREATE TABLE public.tmsDeliveryPlanItem (
  tmsDeliveryPlanItemId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsDeliveryPlanItemPlanId uuid,
  tmsDeliveryPlanItemSalesOrderNo text,
  tmsDeliveryPlanItemCustomerName text,
  tmsDeliveryPlanItemSalesOrderLineNo integer,
  tmsDeliveryPlanItemItemNo text,
  tmsDeliveryPlanItemDescription text,
  tmsDeliveryPlanItemUom text,
  tmsDeliveryPlanItemOrderedQty numeric DEFAULT 0,
  tmsDeliveryPlanItemShippedQty numeric DEFAULT 0,
  tmsDeliveryPlanItemOutstandingQty numeric DEFAULT 0,
  tmsDeliveryPlanItemPlannedQty numeric NOT NULL,
  tmsDeliveryPlanItemCreatedAt timestamp with time zone DEFAULT now(),
  tmsDeliveryPlanItemCustomerPhone text,
  CONSTRAINT tmsDeliveryPlanItem_pkey PRIMARY KEY (tmsDeliveryPlanItemId),
  CONSTRAINT tmsDeliveryPlanItem_tmsDeliveryPlanItemPlanId_fkey FOREIGN KEY (tmsDeliveryPlanItemPlanId) REFERENCES public.tmsDeliveryPlan(tmsDeliveryPlanId)
);
CREATE TABLE public.tmsFuelLog (
  tmsFuelLogId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsFuelLogVehicleId uuid,
  tmsFuelLogDate date,
  tmsFuelLogFuelType text,
  tmsFuelLogLiters numeric,
  tmsFuelLogPricePerLiter numeric,
  tmsFuelLogTotalCost numeric,
  tmsFuelLogCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  tmsFuelLogReceiptUrl text,
  CONSTRAINT tmsFuelLog_pkey PRIMARY KEY (tmsFuelLogId),
  CONSTRAINT tmsFuelLog_tmsFuelLogVehicleId_fkey FOREIGN KEY (tmsFuelLogVehicleId) REFERENCES public.tmsVehicle(tmsVehicleId)
);
CREATE TABLE public.tmsGpsLog (
  tmsGpsLogId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsGpsLogVehicleId uuid,
  tmsGpsLogShipmentId uuid,
  tmsGpsLogLatitude numeric,
  tmsGpsLogLongitude numeric,
  tmsGpsLogSpeed numeric,
  tmsGpsLogRecordedAt timestamp with time zone DEFAULT now(),
  tmsGpsLogCreatedAt timestamp with time zone DEFAULT now(),
  tmsGpsLogEngine text,
  tmsGpsLogDriver text,
  tmsGpsLogAddress text,
  tmsGpsLogFuel numeric,
  tmsGpsLogTemperature integer,
  tmsGpsLogCOG integer,
  tmsGpsLogPowerStatus text,
  tmsGpsLogExternalBatt text,
  tmsGpsLogPositionSource text,
  tmsGpsLogPoi text,
  tmsGpsLogGpsSignal text,
  tmsGpsLogGprs text,
  tmsGpsLogVehicleType text,
  tmsGpsLogForthtrackId text,
  tmsGpsLogSource text,
  CONSTRAINT tmsGpsLog_pkey PRIMARY KEY (tmsGpsLogId),
  CONSTRAINT tmsGpsLog_tmsGpsLogVehicleId_fkey FOREIGN KEY (tmsGpsLogVehicleId) REFERENCES public.tmsVehicle(tmsVehicleId),
  CONSTRAINT tmsGpsLog_tmsGpsLogShipmentId_fkey FOREIGN KEY (tmsGpsLogShipmentId) REFERENCES public.tmsShipment(tmsShipmentId)
);
CREATE TABLE public.tmsShipment (
  tmsShipmentId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsShipmentNumber text,
  tmsShipmentCustomerName text,
  tmsShipmentCustomerPhone text,
  tmsShipmentCustomerAddress text,
  tmsShipmentDestination text,
  tmsShipmentVehicleId uuid,
  tmsShipmentDriverId uuid,
  tmsShipmentAssistantId uuid,
  tmsShipmentSalesOrderRef text,
  tmsShipmentItemsSummary text,
  tmsShipmentNotes text,
  tmsShipmentEstimatedArrival timestamp with time zone,
  tmsShipmentStatus text DEFAULT 'pending'::text,
  tmsShipmentDate date,
  tmsShipmentCreatedBy uuid,
  tmsShipmentCreatedAt timestamp with time zone DEFAULT now(),
  tmsShipmentDispatchedAt timestamp with time zone,
  tmsShipmentDeliveredAt timestamp with time zone,
  isActive boolean NOT NULL DEFAULT true,
  tmsShipmentDriverWage numeric,
  tmsShipmentAssistantWage numeric,
  tmsShipmentDistance numeric,
  tmsShipmentFuelPricePerLiter numeric,
  tmsShipmentFuelCost numeric,
  tmsShipmentAssistants jsonb,
  tmsShipmentExtras jsonb,
  tmsShipmentStops jsonb,
  CONSTRAINT tmsShipment_pkey PRIMARY KEY (tmsShipmentId),
  CONSTRAINT tmsShipment_tmsShipmentVehicleId_fkey FOREIGN KEY (tmsShipmentVehicleId) REFERENCES public.tmsVehicle(tmsVehicleId)
);
CREATE TABLE public.tmsVehicle (
  tmsVehicleId uuid NOT NULL DEFAULT uuid_generate_v4(),
  tmsVehiclePlateNumber text,
  tmsVehicleName text,
  tmsVehicleCapacityKg numeric,
  tmsVehicleFuelType text DEFAULT 'diesel'::text,
  tmsVehicleStatus text DEFAULT 'available'::text,
  tmsVehicleCreatedAt timestamp with time zone DEFAULT now(),
  isActive boolean NOT NULL DEFAULT true,
  tmsVehicleWidth numeric,
  tmsVehicleLength numeric,
  tmsVehicleHeight numeric,
  tmsVehicleFuelConsumptionRate numeric,
  tmsVehicleForthtrackId text,
  CONSTRAINT tmsVehicle_pkey PRIMARY KEY (tmsVehicleId)
);
CREATE TABLE public.whAppVersion (
  whAppVersionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  whAppVersionCode integer,
  whAppVersionName text,
  whAppVersionDownloadUrl text,
  whAppVersionReleaseNotes text,
  whAppVersionCreatedAt timestamp with time zone DEFAULT now(),
  whAppVersionIsMandatory boolean DEFAULT false,
  CONSTRAINT whAppVersion_pkey PRIMARY KEY (whAppVersionId)
);
CREATE TABLE public.whOrderMatch (
  whOrderMatchId uuid NOT NULL DEFAULT uuid_generate_v4(),
  whOrderMatchUserId uuid,
  whOrderMatchOrderNumber text,
  whOrderMatchOrderType text,
  whOrderMatchExpectedItems jsonb,
  whOrderMatchScannedItems jsonb,
  whOrderMatchSessionId uuid,
  CONSTRAINT whOrderMatch_pkey PRIMARY KEY (whOrderMatchId),
  CONSTRAINT whOrderMatch_whOrderMatchSessionId_fkey FOREIGN KEY (whOrderMatchSessionId) REFERENCES public.whScanSession(whScanSessionId)
);
CREATE TABLE public.whScanRecord (
  whScanRecordId uuid NOT NULL DEFAULT uuid_generate_v4(),
  whScanRecordSessionId uuid,
  whScanRecordEpc text,
  whScanRecordRssi numeric,
  whScanRecordItemNumber text,
  whScanRecordItemName text,
  whScanRecordPhotoUrl text,
  whScanRecordReadCount integer DEFAULT 1,
  whScanRecordScannedAt timestamp with time zone DEFAULT now(),
  CONSTRAINT whScanRecord_pkey PRIMARY KEY (whScanRecordId),
  CONSTRAINT whScanRecord_whScanRecordSessionId_fkey FOREIGN KEY (whScanRecordSessionId) REFERENCES public.whScanSession(whScanSessionId)
);
CREATE TABLE public.whScanSession (
  whScanSessionId uuid NOT NULL DEFAULT uuid_generate_v4(),
  whScanSessionUserId uuid,
  whScanSessionName text,
  whScanSessionType text,
  whScanSessionStartedAt timestamp with time zone DEFAULT now(),
  whScanSessionEndedAt timestamp with time zone,
  whScanSessionGpsLat numeric,
  whScanSessionGpsLon numeric,
  whScanSessionTagCount integer DEFAULT 0,
  whScanSessionTotalReads integer DEFAULT 0,
  whScanSessionMetadata jsonb,
  CONSTRAINT whScanSession_pkey PRIMARY KEY (whScanSessionId)
);
CREATE TABLE public.whTransfer (
  whTransferId uuid NOT NULL DEFAULT uuid_generate_v4(),
  whTransferUserId uuid,
  whTransferNo text,
  whTransferFromLocation text,
  whTransferToLocation text,
  whTransferSessionId uuid,
  whTransferNotes text,
  whTransferGpsLat numeric,
  whTransferGpsLon numeric,
  whTransferStatus text DEFAULT 'pending'::text,
  whTransferCreatedAt timestamp with time zone DEFAULT now(),
  whTransferCompletedAt timestamp with time zone,
  CONSTRAINT whTransfer_pkey PRIMARY KEY (whTransferId),
  CONSTRAINT whTransfer_whTransferSessionId_fkey FOREIGN KEY (whTransferSessionId) REFERENCES public.whScanSession(whScanSessionId)
);